import test from 'node:test';
import assert from 'node:assert/strict';
import { ActorId, ActorKind, ActorReference, CommandId, ContentHash, CorrelationId, EvidenceId, EvidenceKind, EvidenceReference, EvidenceSnapshot, Jurisdiction, SourceId, SubjectId, SubjectKind, SubjectReference, UtcInstant, VerificationState, VerificationStateCode, VersionId } from '../../core/src/index.ts';
import { AccessDecisionReference, ApplicationExecutionContext, ApplicationOperationReference, AuditReference, OrganizationScopeReference, PurposeReference, TenantScopeReference } from '../src/index.ts';
import { AccessDisposition, TenantAccessDecision } from '../src/tenant/tenant-governance.ts';
import { DocumentIntakeId, IntakeChannelProvenance, IntakeMediaMetadata, IntakeSecurityClassification, MultiChannelIntakeSubmission } from '../src/intake/index.ts';
import { OriginalArchiveEntry, ArchiveByteIntegrityObservation, OriginalArchiveRelationship, OriginalArchiveRelationshipKind } from '../src/archive/original-document-archive.ts';
import { DerivedExtractionProposalRecord, ExtractionProcessorKind, ExtractionProcessorReference, ExtractionProposalReviewHistory, ExtractionReviewState, ExtractionReviewActorRole } from '../src/extraction/index.ts';
import { IntakeSecurityAssessment, IntakeSecurityControl, IntakeSecurityObservation, IntakeSecurityObservationOutcome, IntakeSecurityObservationReason, SecurityControlPolicy, SecurityScannerReference } from '../src/security/index.ts';
import { AuthorityRole, TrustEntity, TrustEntityId, TrustEntityKind, TrustEntityStatus, TrustRegistrySnapshot, TrustRegistrySnapshotId } from '../src/trust/index.ts';
import { VerificationMethod, VerificationRequest, VerificationRequestId, VerificationRouteDefinition, VerificationRouteId, VerificationRouteRegistrySnapshot, VerificationRouteRegistrySnapshotId, VerificationAssuranceLevel, VerificationAttemptId, VerificationProviderRequest, VerificationProviderResult, VerificationRouteResult, VerificationRouteOutcome } from '../src/verification/index.ts';
import { HumanReviewCase, HumanReviewCaseId, HumanReviewerMandate, HumanReviewPermission, HumanReviewCommand, HumanReviewAction, HumanReviewHistory } from '../src/human-review/index.ts';
import { ArchiveScope, ArchiveLifecycleGrant, ArchiveOperation, ArchiveRetentionPolicy, ArchiveLink, ArchiveLinkRelation, ArchiveHold, ArchiveLifecycle, ArchiveCommand, ArchiveEvidenceSnapshot, ArchiveDependencyInventory, ArchiveDisposalAssessment } from '../src/archive/archive-lifecycle.ts';

const uuid = (n: number) => `018f3f7e-4444-7abc-8def-${String(n).padStart(12, '0')}`;
const at = (s: string) => UtcInstant.from(s);
const T0 = at('2026-01-01T00:00:00Z'), DERIVED = at('2026-02-01T00:00:00Z'), REVIEWED = at('2026-04-01T00:00:00Z');
const OPEN = at('2026-09-01T00:00:00Z'), CAP = at('2026-09-02T00:00:00Z'), EXP = at('2026-09-03T00:00:00Z');
const NOW = at('2026-09-04T00:00:00Z'), LATE = at('2026-09-05T00:00:00Z'), END = at('2026-12-01T00:00:00Z');
const actor = (n: number) => ActorReference.create(ActorId.from(uuid(n)), ActorKind.HUMAN_USER);
const OWNER = actor(1), REVIEWER = actor(2), ADMIN = actor(3);
const TENANT = TenantScopeReference.from('tenant:s09'), ORG = OrganizationScopeReference.from('org:s09'), PURPOSE = PurposeReference.from('purpose:archive');
const SOURCE = SourceId.from(uuid(4)), VERSION = VersionId.from('s09-v1'), ACCESS = AccessDecisionReference.from('access:s09');
const A = 'credential:number';
function access(overrides: Partial<Parameters<typeof TenantAccessDecision.create>[0]> = {}) {
  return TenantAccessDecision.create({ reference: ACCESS, tenant: TENANT, purpose: PURPOSE, disposition: AccessDisposition.ALLOW, allowedFields: ['archive:metadata', A], decidedBy: ADMIN, auditReference: AuditReference.from('audit:s09-access'), ...overrides });
}
function fixture(n = 10) {
  const subject = SubjectReference.create(SubjectId.from(uuid(n + 2)), SubjectKind.PERSON);
  const original = EvidenceReference.original({ id: EvidenceId.from(uuid(n)), kind: EvidenceKind.DOCUMENT, contentReference: 'object://private/credential', mediaType: 'application/pdf', contentHash: ContentHash.sha256('a'.repeat(64)), acquiredAt: T0, acquiredBy: OWNER, verificationState: VerificationState.from(VerificationStateCode.UNVERIFIED) });
  const intake = MultiChannelIntakeSubmission.create({ id: DocumentIntakeId.from(uuid(n + 1)), originalArtifact: original, provenance: IntakeChannelProvenance.fileUpload('upload:s09'), receivedAt: T0, receivedBy: OWNER, subject, organization: ORG, media: IntakeMediaMetadata.create({ mediaType: 'application/pdf', byteLength: 100, originalFileName: 'private-name.pdf' }), securityClassification: IntakeSecurityClassification.CONFIDENTIAL });
  const archive = OriginalArchiveEntry.create({ submission: intake, storageObjectReference: 'archive://private/credential', archivedAt: T0, encryptionProfileReference: 'encryption:test', accessPolicyReference: 'access:test', retentionPolicyReference: 'retention:credential', integrity: ArchiveByteIntegrityObservation.matched({ observedContentHash: original.contentHash!, checkedAt: T0, methodReference: 'integrity:sha256' }) });
  const scope = ArchiveScope.create({ intake, archive, tenant: TENANT });
  const scanner = SecurityScannerReference.create({ adapterReference: 'scanner:test', engineReference: 'engine:test', engineVersion: '1', configurationReference: 'configuration:test' });
  const security = IntakeSecurityAssessment.evaluate({ archiveEntry: archive, policy: SecurityControlPolicy.create({ policyReference: 'security:test', requiredControls: [IntakeSecurityControl.MALWARE_SCAN] }), observations: [IntakeSecurityObservation.create({ archiveEntry: archive, control: IntakeSecurityControl.MALWARE_SCAN, outcome: IntakeSecurityObservationOutcome.PASS, reason: IntakeSecurityObservationReason.CONTROL_PASSED, observedAt: OPEN, scanner })], evaluatedAt: OPEN });
  return { original, intake, archive, scope, subject, security };
}
function context(f: ReturnType<typeof fixture>, operation: string, time = NOW, overrides: Partial<Parameters<typeof ApplicationExecutionContext.create>[0]> = {}) {
  return ApplicationExecutionContext.create({ operation: ApplicationOperationReference.from(operation), actor: REVIEWER, subject: f.subject, tenantScope: TENANT, organizationScope: ORG, purpose: PURPOSE, correlationId: CorrelationId.from(uuid(8)), requestedAt: time, contractVersion: VERSION, accessDecision: ACCESS, ...overrides });
}
function grant(f: ReturnType<typeof fixture>, overrides: Partial<Parameters<typeof ArchiveLifecycleGrant.create>[0]> = {}) {
  return ArchiveLifecycleGrant.create({ reference: 'grant:s09', scope: f.scope, actor: REVIEWER, purpose: PURPOSE, permissions: Object.values(ArchiveOperation), accessDecision: access(), validFrom: T0, validUntil: END, sourceId: SOURCE, sourceVersion: VERSION, decisionReference: 'decision:grant:s09', ...overrides });
}
function policy(overrides: Partial<Parameters<typeof ArchiveRetentionPolicy.create>[0]> = {}) {
  return ArchiveRetentionPolicy.create({ reference: 'retention:credential', version: VERSION, sourceId: SOURCE, sourceSnapshotReference: 'snapshot:retention:v1', reviewedAt: REVIEWED, retainThrough: EXP, reviewDueAt: END, ...overrides });
}
function start(f = fixture(), p = policy(), ctx = context(f, ArchiveOperation.OPEN, OPEN), g = grant(f)) { return ArchiveLifecycle.start({ scope: f.scope, policy: p, context: ctx, grant: g }); }
function link(f: ReturnType<typeof fixture>, overrides: Partial<Parameters<typeof ArchiveLink.create>[0]> = {}) {
  return ArchiveLink.create({ id: uuid(100), source: f.scope, relation: ArchiveLinkRelation.EVIDENCES_CREDENTIAL, targetKind: 'CREDENTIAL', targetReference: 'credential:123', targetTenant: TENANT, targetOrganization: ORG, scopeReference: 'scope:credential', sourceId: SOURCE, sourceVersion: VERSION, sourceSnapshotReference: 'snapshot:link:v1', recordedAt: OPEN, validFrom: OPEN, validUntil: null, ...overrides });
}
function hold(f: ReturnType<typeof fixture>, overrides: Partial<Parameters<typeof ArchiveHold.create>[0]> = {}) {
  return ArchiveHold.create({ id: uuid(110), scope: f.scope, basisReference: 'basis:legal-hold', recordedAt: OPEN, startsAt: OPEN, endsAt: null, ...overrides });
}
function command(f: ReturnType<typeof fixture>, change: Parameters<typeof ArchiveCommand.create>[0]['change'], n = 200, time = NOW) {
  return ArchiveCommand.create({ id: CommandId.from(uuid(n)), scope: f.scope, change, submittedAt: time, idempotencyKey: `command:${n}`, reasonReference: 'reason:archive-change' });
}
function apply(f: ReturnType<typeof fixture>, state: ArchiveLifecycle, change: Parameters<typeof ArchiveCommand.create>[0]['change'], n = 200, time = NOW) {
  const cmd = command(f, change, n, time);
  return state.apply({ command: cmd, expectedRevision: state.revision, context: context(f, cmd.operation, time), grant: grant(f) });
}
function snapshot(f: ReturnType<typeof fixture>, state = start(f), overrides: Partial<Parameters<typeof ArchiveEvidenceSnapshot.capture>[0]> = {}) {
  return ArchiveEvidenceSnapshot.capture({ id: uuid(120), lifecycle: state, context: context(f, ArchiveOperation.CAPTURE, CAP), grant: grant(f), security: f.security, derivedRecords: [], extractionReviews: [], verificationResults: [], humanReviews: [], preserveUntil: EXP, ...overrides });
}
function derived(f: ReturnType<typeof fixture>, n = 130, parent: OriginalArchiveEntry | DerivedExtractionProposalRecord = f.archive, time = DERIVED) {
  const parentId = parent instanceof OriginalArchiveEntry ? parent.originalArtifact.id : parent.derivedEvidence.id;
  return DerivedExtractionProposalRecord.create({ parent, derivedEvidence: EvidenceReference.derived({ id: EvidenceId.from(uuid(n)), kind: EvidenceKind.OCR_TEXT, contentReference: 'object://private/ocr', derivationParent: parentId, acquiredAt: time, acquiredBy: OWNER, verificationState: VerificationState.from(VerificationStateCode.UNVERIFIED) }), processor: ExtractionProcessorReference.create({ kind: ExtractionProcessorKind.OCR_ENGINE, processorReference: 'processor:ocr', processorVersion: '1' }) });
}
function inventory(state: ArchiveLifecycle, overrides: Partial<Parameters<typeof ArchiveDependencyInventory.create>[0]> = {}) {
  return ArchiveDependencyInventory.create({ lifecycle: state, completeness: 'COMPLETE', blockingReferences: [], observedAt: NOW, freshUntil: LATE, sourceId: SOURCE, sourceVersion: VERSION, sourceSnapshotReference: 'snapshot:dependencies', ...overrides });
}
function assess(f: ReturnType<typeof fixture>, state = start(f), inv = inventory(state), time = NOW) {
  return ArchiveDisposalAssessment.evaluate({ lifecycle: state, inventory: inv, context: context(f, ArchiveOperation.ASSESS, time), grant: grant(f) });
}
function verification(f: ReturnType<typeof fixture>, method: VerificationMethod = VerificationMethod.OFFICIAL_REGISTRY_LOOKUP, checkedAt = OPEN) {
  const entity = TrustEntity.create({ id: TrustEntityId.from(uuid(300)), legalName: 'Private Authority Name', kind: TrustEntityKind.VERIFIER, jurisdictions: [Jurisdiction.fromCode('CZ')], identifiers: [], status: TrustEntityStatus.ACTIVE, validFrom: T0, provenanceReference: 'provenance:authority' });
  const trust = TrustRegistrySnapshot.create({ id: TrustRegistrySnapshotId.from(uuid(301)), asKnownAt: OPEN, entities: [entity], authorityScopes: [], anchors: [], policyVersion: VERSION });
  const route = VerificationRouteDefinition.create({ id: VerificationRouteId.from(uuid(302)), method, capability: 'capability:verification', verifierEntity: entity, authorityRole: AuthorityRole.VERIFIER, supportedClaims: [A], jurisdictions: [Jurisdiction.fromCode('CZ')], assuranceLevel: VerificationAssuranceLevel.HIGH, priority: 1, validFrom: T0, sourceId: SOURCE, sourceVersion: VERSION, sourceSnapshotReference: 'snapshot:route', retrievedAt: T0 });
  const registry = VerificationRouteRegistrySnapshot.create({ id: VerificationRouteRegistrySnapshotId.from(uuid(303)), trustSnapshot: trust, asKnownAt: OPEN, routes: [route], policyVersion: VERSION });
  const request = VerificationRequest.create({ id: VerificationRequestId.from(uuid(304)), evidence: f.original, subjectReference: f.subject.id.toString(), claims: [A], jurisdiction: Jurisdiction.fromCode('CZ'), useCase: 'credential-review', requiredAssurance: VerificationAssuranceLevel.HIGH, acceptableMethods: [method], evaluationInstant: T0, asKnownAt: OPEN, idempotencyKey: 'verification:1' });
  const makeResult = () => VerificationRouteResult.normalize({ providerRequest: VerificationProviderRequest.create({ attemptId: VerificationAttemptId.from(uuid(305)), route, request, claims: [A], idempotencyKey: 'provider:1' }), providerResult: VerificationProviderResult.create({ outcome: VerificationRouteOutcome.INDETERMINATE, adapterReference: 'adapter:test', adapterVersion: '1', checkedClaims: [A], assertionFingerprints: { [A]: 'assertion:observed-unverified' }, sourceSnapshotReference: 'snapshot:provider', sourceVersionReference: '1', checkedAt, reasonCodes: ['PROVIDER_UNAVAILABLE'] }), authorityResolutions: [] });
  return { entity, trust, route, registry, request, makeResult };
}
function human(f: ReturnType<typeof fixture>, time = CAP) {
  const v = verification(f, VerificationMethod.HUMAN_REVIEW);
  const c = HumanReviewCase.open({ id: HumanReviewCaseId.from(uuid(310)), request: v.request, registry: v.registry, route: v.route, intake: f.intake, security: f.security, context: context(f, 'verification.human-review.open', OPEN), accessDecision: access(), claims: [A], authorityResolutions: [], priorResults: [] });
  const m = HumanReviewerMandate.create({ reference: 'mandate:human', reviewCase: c, reviewer: REVIEWER, grantedBy: ADMIN, verifierEntity: v.entity, accessDecision: access(), claims: [A], permissions: [HumanReviewPermission.REVIEW], grantedAt: OPEN, validFrom: OPEN, validUntil: END, sourceId: SOURCE, sourceVersion: VERSION, sourceSnapshotReference: 'snapshot:mandate' });
  const cmd = HumanReviewCommand.create({ id: CommandId.from(uuid(311)), reviewCase: c, action: HumanReviewAction.COMPLETE_REVIEW, claims: [A], observations: [], evidenceReferences: ['evidence:review'], rationaleReference: 'rationale:review', submittedAt: time, idempotencyKey: 'human:1' });
  return HumanReviewHistory.start(c).apply({ command: cmd, context: context(f, 'verification.human-review.record', time), mandate: m, expectedRevision: 0 });
}

test('M05S09-01 exact scope is immutable', () => { const f = fixture(); assert.equal(f.scope.archive, f.archive); assert.equal(f.scope.intake, f.intake); assert(Object.isFrozen(f.scope)); assert.equal(f.scope.toJSON().evidenceId, f.original.id.toString()); });
test('M05S09-02 foreign original or intake is rejected', () => { const f = fixture(), g = fixture(20); assert.throws(() => ArchiveScope.create({ intake: g.intake, archive: f.archive, tenant: TENANT })); });
test('M05S09-03 missing scope dimensions are rejected', () => { const f = fixture(); assert.throws(() => ArchiveScope.create({ intake: f.intake, archive: f.archive, tenant: null as never })); assert.throws(() => start(f, policy(), context(f, ArchiveOperation.OPEN, OPEN, { subject: null }))); assert.throws(() => start(f, policy(), context(f, ArchiveOperation.OPEN, OPEN, { organizationScope: null }))); });
test('M05S09-04 invocation is tenant organization subject scoped', () => { const f = fixture(), g = fixture(20); for (const overrides of [{ tenantScope: TenantScopeReference.from('tenant:other') }, { organizationScope: OrganizationScopeReference.from('org:other') }, { subject: g.subject }]) assert.throws(() => start(f, policy(), context(f, ArchiveOperation.OPEN, OPEN, overrides))); });
test('M05S09-05 another actor cannot invoke grant', () => {
  const f = fixture(); assert.throws(() => start(f, policy(), context(f, ArchiveOperation.OPEN, OPEN, { actor: OWNER })));
  assert.throws(() => grant(f, { actor: ActorReference.create(ActorId.from(uuid(900)), ActorKind.ORGANIZATION) }), /individual human or system principal/);
  const system = ActorReference.create(ActorId.from(uuid(901)), ActorKind.SYSTEM_PROCESS);
  assert.equal(start(f, policy(), context(f, ArchiveOperation.OPEN, OPEN, { actor: system }), grant(f, { actor: system })).status, 'ACTIVE');
});
test('M05S09-06 access denial and mismatched reference fail closed', () => { const f = fixture(); assert.throws(() => grant(f, { accessDecision: access({ disposition: AccessDisposition.DENY }) })); assert.throws(() => start(f, policy(), context(f, ArchiveOperation.OPEN, OPEN, { accessDecision: AccessDecisionReference.from('other') }))); });
test('M05S09-07 expired and revoked grants fail', () => { const f = fixture(); assert.throws(() => start(f, policy(), context(f, ArchiveOperation.OPEN, OPEN), grant(f, { validUntil: T0 }))); assert.throws(() => start(f, policy(), context(f, ArchiveOperation.OPEN, OPEN), grant(f, { revokedAt: OPEN }))); });
test('M05S09-08 replay still requires operation permission', () => { const f = fixture(), s = start(f), cmd = command(f, { kind: 'LINK', link: link(f) }), h = s.apply({ command: cmd, context: context(f, cmd.operation), grant: grant(f), expectedRevision: 0 }); assert.throws(() => h.apply({ command: cmd, context: context(f, cmd.operation), grant: grant(f, { permissions: [ArchiveOperation.OPEN] }), expectedRevision: 0 })); });
test('M05S09-09 retention dates and provenance are controlled', () => { assert.throws(() => policy({ reviewDueAt: T0 })); assert.throws(() => policy({ version: 'v1' as never })); assert.throws(() => policy({ retainThrough: 'yesterday' as never })); assert.throws(() => policy({ sourceSnapshotReference: '\n' })); });
test('M05S09-10 immutable policy reference must match', () => { assert.throws(() => start(fixture(), policy({ reference: 'other-policy' }))); });
test('M05S09-11 future policy cannot be applied', () => { assert.throws(() => start(fixture(), policy({ reviewedAt: NOW }))); });
test('M05S09-12 policy replacement versions history', () => {
  const f = fixture(), s = start(f); assert.throws(() => apply(f, s, { kind: 'REPLACE_POLICY', policy: policy() }));
  const p = policy({ version: VersionId.from('s09-v2'), reviewedAt: CAP, retainThrough: LATE }); const h = apply(f, s, { kind: 'REPLACE_POLICY', policy: p });
  assert.equal(h.policy, p); assert.equal(s.policy.version.toString(), 's09-v1'); assert.equal(h.records.length, 1); assert.equal(h.initialPolicy, s.policy); assert.equal(h.toJSON().initialPolicy.version, 's09-v1');
  assert.throws(() => apply(f, h, { kind: 'REPLACE_POLICY', policy: policy({ version: VersionId.from('s09-v3'), reviewedAt: T0 }) }, 201));
  assert.throws(() => apply(f, h, { kind: 'REPLACE_POLICY', policy: policy({ reviewedAt: CAP, retainThrough: null }) }, 201), /Policy version was already used/);
  const h2 = apply(f, h, { kind: 'REPLACE_POLICY', policy: policy({ version: VersionId.from('s09-v3'), reviewedAt: NOW }) }, 201);
  assert.throws(() => apply(f, h2, { kind: 'REPLACE_POLICY', policy: policy({ version: VersionId.from('s09-v2'), reviewedAt: NOW }) }, 202), /Policy version was already used/);
  assert.equal(h2.initialPolicy, s.policy);
});
test('M05S09-13 all canonical relation kinds preserve original state', () => { const f = fixture(), target = fixture(20); const kinds = { EVIDENCES_CREDENTIAL: 'CREDENTIAL', EVIDENCES_REQUIREMENT: 'REQUIREMENT', SUPPORTS_RECOGNITION: 'RECOGNITION', SUPPORTS_RENEWAL: 'RENEWAL', SUPPLEMENTS_DOCUMENT: 'DOCUMENT', SUPERSEDES_DOCUMENT: 'DOCUMENT', RELATED_TO_SUBJECT: 'SUBJECT' } as const; for (const relation of Object.values(ArchiveLinkRelation)) { const isDoc = kinds[relation] === 'DOCUMENT'; const relationship = isDoc ? OriginalArchiveRelationship.create({ source: f.archive, target: target.archive, kind: relation === 'SUPPLEMENTS_DOCUMENT' ? OriginalArchiveRelationshipKind.SUPPLEMENTS : OriginalArchiveRelationshipKind.REPLACES, recordedAt: OPEN, recordedBy: REVIEWER }) : undefined; const item = link(f, { relation, targetKind: kinds[relation], targetReference: isDoc ? target.original.id.toString() : relation === 'RELATED_TO_SUBJECT' ? f.subject.id.toString() : 'target:123', ...(isDoc ? { targetArchive: target.scope, relationship } : {}) }); assert.equal(item.relation, relation); assert.equal(item.toJSON().verificationState, 'UNVERIFIED'); } assert.equal(Object.keys(kinds).length, 7); });
test('M05S09-14 relation must match target kind', () => { const f = fixture(); assert.throws(() => link(f, { targetKind: 'SUBJECT' })); assert.throws(() => link(f, { relation: 'GRANTS_AUTHORITY' as never })); });
test('M05S09-15 cross-tenant and cross-organization targets fail', () => { const f = fixture(); assert.throws(() => link(f, { targetTenant: TenantScopeReference.from('tenant:other') })); assert.throws(() => link(f, { targetOrganization: OrganizationScopeReference.from('org:other') })); });
test('M05S09-16 document links require exact S02 relationships', () => { const f = fixture(), g = fixture(20); assert.throws(() => link(f, { relation: 'SUPERSEDES_DOCUMENT', targetKind: 'DOCUMENT', targetReference: g.original.id.toString() })); const rel = OriginalArchiveRelationship.create({ source: f.archive, target: g.archive, kind: OriginalArchiveRelationshipKind.SUPPLEMENTS, recordedAt: OPEN, recordedBy: REVIEWER }); assert.throws(() => link(f, { relation: 'SUPERSEDES_DOCUMENT', targetKind: 'DOCUMENT', targetReference: g.original.id.toString(), targetArchive: g.scope, relationship: rel })); });
test('M05S09-17 related subject must match archive subject', () => { const f = fixture(); assert.throws(() => link(f, { relation: 'RELATED_TO_SUBJECT', targetKind: 'SUBJECT', targetReference: uuid(999) })); });
test('M05S09-18 link references and time intervals are validated', () => { const f = fixture(); assert.throws(() => link(f, { validUntil: T0 })); assert.throws(() => link(f, { id: 'bad' })); assert.throws(() => link(f, { sourceSnapshotReference: '' })); assert.throws(() => apply(f, start(f), { kind: 'LINK', link: link(f, { recordedAt: END }) })); });
test('M05S09-19 link IDs cannot duplicate or rewrite history', () => { const f = fixture(), s = start(f), item = link(f), h = apply(f, s, { kind: 'LINK', link: item }); assert.throws(() => apply(f, h, { kind: 'LINK', link: item }, 201)); const unlinked = apply(f, h, { kind: 'UNLINK', reference: item.id }, 201); assert.throws(() => apply(f, unlinked, { kind: 'LINK', link: item }, 202)); });
test('M05S09-20 unlink preserves recorded and snapshotted link', () => { const f = fixture(), item = link(f), h = apply(f, start(f), { kind: 'LINK', link: item }, 200, OPEN), snap = snapshot(f, h), next = apply(f, h, { kind: 'UNLINK', reference: item.id }, 201); assert.equal(next.links.length, 0); assert.equal(snap.toJSON().links.length, 1); assert.equal(h.links[0], item); assert.equal(next.records[0], h.records[0]); });
test('M05S09-21 hold dates and basis must be valid', () => { const f = fixture(); assert.throws(() => hold(f, { endsAt: T0 })); assert.throws(() => hold(f, { basisReference: '' })); });
test('M05S09-22 active hold blocks disposal', () => { const f = fixture(), h = apply(f, start(f), { kind: 'PLACE_HOLD', hold: hold(f) }); const a = assess(f, h); assert.equal(a.outcome, 'RETAIN'); assert(a.reasonCodes.includes('HOLD_REQUIRES_RETENTION')); });
test('M05S09-23 future holds block but elapsed holds do not', () => { const f = fixture(), future = apply(f, start(f), { kind: 'PLACE_HOLD', hold: hold(f, { startsAt: LATE }) }); assert.equal(assess(f, future).outcome, 'RETAIN'); const elapsed = apply(f, start(f), { kind: 'PLACE_HOLD', hold: hold(f, { endsAt: EXP }) }); assert.equal(assess(f, elapsed).outcome, 'DISPOSAL_CANDIDATE'); });
test('M05S09-24 hold release requires permission and retains event', () => { const f = fixture(), item = hold(f), h = apply(f, start(f), { kind: 'PLACE_HOLD', hold: item }), cmd = command(f, { kind: 'RELEASE_HOLD', reference: item.id }, 201); assert.throws(() => h.apply({ command: cmd, context: context(f, cmd.operation), grant: grant(f, { permissions: [ArchiveOperation.PLACE_HOLD] }), expectedRevision: h.revision })); const next = apply(f, h, cmd.change, 201); assert.equal(next.holds.length, 0); assert.equal(next.records[0], h.records[0]); });
test('M05S09-25 snapshots reuse Core evidence snapshot', () => { const f = fixture(), s = snapshot(f); assert(s.evidenceSnapshot instanceof EvidenceSnapshot); assert.equal(s.evidenceSnapshot.entries[0]!.evidenceId, f.original.id); assert.equal(s.evidenceSnapshot.capturedAt, CAP); });
test('M05S09-26 every exact derived parent must be included', () => { const f = fixture(), d1 = derived(f), d2 = derived(f, 131, d1); assert.throws(() => snapshot(f, start(f), { derivedRecords: [d2] })); const snap = snapshot(f, start(f), { derivedRecords: [d2, d1] }); assert.equal(snap.evidenceSnapshot.entries.length, 3); const cloneParent = derived(f); assert.throws(() => snapshot(f, start(f), { derivedRecords: [cloneParent, d2] })); });
test('M05S09-27 duplicate evidence IDs are rejected', () => { const f = fixture(), d = derived(f); assert.throws(() => snapshot(f, start(f), { derivedRecords: [d, d] })); });
test('M05S09-28 foreign derived root is rejected', () => { const f = fixture(); assert.throws(() => snapshot(f, start(f), { derivedRecords: [derived(fixture(20))] })); });
test('M05S09-29 future derived evidence is rejected', () => { const f = fixture(); assert.throws(() => snapshot(f, start(f), { derivedRecords: [derived(f, 130, f.archive, LATE)] })); });
test('M05S09-30 extraction review binds exact proposal and cutoff', () => { const f = fixture(), d = derived(f), r = ExtractionProposalReviewHistory.start(d).append({ state: ExtractionReviewState.HUMAN_REVIEW_REQUIRED, reviewedBy: REVIEWER, actorRole: ExtractionReviewActorRole.REVIEWER, reviewedAt: CAP, reason: 'review:required' }); assert.throws(() => snapshot(f, start(f), { extractionReviews: [r] })); assert.equal(snapshot(f, start(f), { derivedRecords: [d], extractionReviews: [r] }).extractionReviews[0], r); const future = r.append({ state: ExtractionReviewState.HUMAN_REVIEW_REQUIRED, reviewedBy: REVIEWER, actorRole: ExtractionReviewActorRole.REVIEWER, reviewedAt: LATE, reason: 'future:review' }); assert.throws(() => snapshot(f, start(f), { derivedRecords: [d], extractionReviews: [future] })); });
test('M05S09-31 provider evidence and time are snapshot scoped', () => {
  const f = fixture(), v = verification(f), good = v.makeResult(), snap = snapshot(f, start(f), { verificationResults: [good] }); assert.equal(snap.verificationResults[0], good);
  const result = snap.toJSON().verificationResults[0]!;
  assert.equal(result.method, VerificationMethod.OFFICIAL_REGISTRY_LOOKUP); assert.equal(result.verifierEntityId, v.entity.id.toString());
  assert.deepEqual(result.assertions, [{ claim: A, fingerprint: 'assertion:observed-unverified' }]); assert.equal(result.outcome, VerificationRouteOutcome.INDETERMINATE); assert(Object.isFrozen(result.assertions)); assert.deepEqual(result.authorityResolutions, []);
  assert.throws(() => snapshot(f, start(f), { verificationResults: [verification(fixture(20)).makeResult()] })); assert.throws(() => snapshot(f, start(f), { verificationResults: [verification(f, VerificationMethod.OFFICIAL_REGISTRY_LOOKUP, LATE).makeResult()] }));
});
test('M05S09-32 human-review histories bind exact archive and cutoff', () => { const f = fixture(), h = human(f); assert.equal(snapshot(f, start(f), { humanReviews: [h] }).humanReviews[0], h); assert.throws(() => snapshot(f, start(f), { humanReviews: [human(fixture(20))] })); assert.throws(() => snapshot(f, start(f), { humanReviews: [human(f, LATE)] })); });
test('M05S09-33 snapshots cannot promote original or extraction', () => { const f = fixture(), d = derived(f), snap = snapshot(f, start(f), { derivedRecords: [d], humanReviews: [human(f)] }); for (const e of snap.evidenceSnapshot.entries) assert.equal(e.verificationState.toString(), 'UNVERIFIED'); assert.equal(f.original.verificationState.toString(), 'UNVERIFIED'); });
test('M05S09-34 snapshots are deterministic and privacy-minimized', () => { const f = fixture(), s = start(f), d1 = derived(f), d2 = derived(f, 131, d1); const a = snapshot(f, s, { derivedRecords: [d2, d1] }), b = snapshot(f, s, { derivedRecords: [d1, d2] }); assert.equal(JSON.stringify(a), JSON.stringify(b)); for (const raw of ['private-name.pdf', 'object://', 'archive://', 'Private Authority Name']) assert(!JSON.stringify(a).includes(raw)); assert(Object.isFrozen(a.toJSON().evidence)); });
test('M05S09-35 pin requires exact current lifecycle revision', () => { const f = fixture(), s = start(f), snap = snapshot(f, s), h = apply(f, s, { kind: 'LINK', link: link(f) }); assert.throws(() => apply(f, h, { kind: 'PIN_SNAPSHOT', snapshot: snap }, 201)); });
test('M05S09-36 pin preserves snapshot immutability', () => { const f = fixture(), s = start(f), snap = snapshot(f, s), before = JSON.stringify(snap), h = apply(f, s, { kind: 'PIN_SNAPSHOT', snapshot: snap }); assert.equal(h.pins[0], snap); assert.equal(JSON.stringify(snap), before); assert(Object.isFrozen(h.pins)); });
test('M05S09-37 snapshot pins require expiry before release', () => { const f = fixture(), s = start(f), snap = snapshot(f, s), h = apply(f, s, { kind: 'PIN_SNAPSHOT', snapshot: snap }, 200, CAP); assert.throws(() => apply(f, h, { kind: 'RELEASE_SNAPSHOT', reference: snap.id }, 201, EXP)); assert.equal(apply(f, h, { kind: 'RELEASE_SNAPSHOT', reference: snap.id }, 201).pins.length, 0); });
test('M05S09-38 indefinite pins cannot be silently released', () => { const f = fixture(), s = start(f), snap = snapshot(f, s, { preserveUntil: null }), h = apply(f, s, { kind: 'PIN_SNAPSHOT', snapshot: snap }); assert.throws(() => apply(f, h, { kind: 'RELEASE_SNAPSHOT', reference: snap.id }, 201)); });
test('M05S09-39 retention is inclusive through exact boundary', () => { const f = fixture(), s = start(f); assert.equal(assess(f, s, inventory(s, { observedAt: EXP }), EXP).outcome, 'RETAIN'); assert.equal(assess(f, s).outcome, 'DISPOSAL_CANDIDATE'); });
test('M05S09-40 indefinite retention cannot authorize disposal', () => { const f = fixture(), s = start(f, policy({ retainThrough: null })); assert.equal(assess(f, s).outcome, 'RETAIN'); });
test('M05S09-41 overdue policy requires review', () => { const f = fixture(), s = start(f, policy({ reviewDueAt: EXP })); const a = assess(f, s); assert.equal(a.outcome, 'REVIEW_REQUIRED'); assert(a.reasonCodes.includes('RETENTION_POLICY_REVIEW_DUE')); });
test('M05S09-42 uncertain dependency inventory fails closed', () => { const f = fixture(), s = start(f); assert.equal(assess(f, s, inventory(s, { completeness: 'INDETERMINATE' })).outcome, 'REVIEW_REQUIRED'); assert.throws(() => inventory(s, { completeness: 'ASSUMED_EMPTY' as never })); });
test('M05S09-43 stale and wrong-revision inventory fail closed', () => { const f = fixture(), s = start(f), old = inventory(s), h = apply(f, s, { kind: 'LINK', link: link(f) }); assert.throws(() => assess(f, h, old)); assert.equal(assess(f, s, inventory(s, { observedAt: OPEN, freshUntil: EXP })).outcome, 'REVIEW_REQUIRED'); });
test('M05S09-44 required external dependencies block disposal', () => { const f = fixture(), s = start(f), a = assess(f, s, inventory(s, { blockingReferences: ['audit:decision', 'derived:required'] })); assert.equal(a.outcome, 'RETAIN'); assert(a.reasonCodes.includes('EXTERNAL_DEPENDENCIES')); });
test('M05S09-45 future and expired registered links block disposal', () => { const f = fixture(); for (const item of [link(f, { validFrom: LATE }), link(f, { validUntil: EXP })]) { const h = apply(f, start(f), { kind: 'LINK', link: item }); assert.equal(assess(f, h).outcome, 'RETAIN'); } });
test('M05S09-46 registered snapshot pins block disposal', () => { const f = fixture(), s = start(f), h = apply(f, s, { kind: 'PIN_SNAPSHOT', snapshot: snapshot(f, s) }); const a = assess(f, h); assert.equal(a.outcome, 'RETAIN'); assert(a.reasonCodes.includes('SNAPSHOT_PINNED')); });
test('M05S09-47 disposal candidates never authorize physical deletion', () => { const f = fixture(), a = assess(f); assert.equal(a.outcome, 'DISPOSAL_CANDIDATE'); assert.equal(a.physicalDeletionAuthorized, false); assert.equal(a.toJSON().physicalDeletionAuthorized, false); });
test('M05S09-48 logical tombstones retain original and audit identity', () => { const f = fixture(), s = start(f), originalBefore = f.original.contentReference, a = assess(f, s), h = apply(f, s, { kind: 'TOMBSTONE', assessment: a }); assert.equal(h.status, 'TOMBSTONED'); assert.equal(h.scope.archive.originalArtifact, f.original); assert.equal(f.original.contentReference, originalBefore); assert.equal(h.records.length, 1); assert.equal(h.toJSON().archive.evidenceId, f.original.id.toString()); });
test('M05S09-49 stale foreign and noncandidate assessments cannot tombstone', () => { const f = fixture(), s = start(f), a = assess(f, s); assert.throws(() => apply(f, s, { kind: 'TOMBSTONE', assessment: a }, 200, LATE)); assert.throws(() => apply(f, s, { kind: 'TOMBSTONE', assessment: assess(fixture(20)) })); const retained = start(f, policy({ retainThrough: null })); assert.throws(() => apply(f, retained, { kind: 'TOMBSTONE', assessment: assess(f, retained) })); });
test('M05S09-50 terminal lifecycle rejects new mutations', () => { const f = fixture(), s = start(f), h = apply(f, s, { kind: 'TOMBSTONE', assessment: assess(f, s) }); assert.throws(() => apply(f, h, { kind: 'LINK', link: link(f) }, 201)); assert.throws(() => snapshot(f, h, { context: context(f, ArchiveOperation.CAPTURE, LATE) })); });
test('M05S09-51 exact replay keeps identity and revision', () => { const f = fixture(), s = start(f), cmd = command(f, { kind: 'LINK', link: link(f) }), input = { command: cmd, expectedRevision: 0, context: context(f, cmd.operation), grant: grant(f) }, h = s.apply(input); assert.equal(h.apply(input), h); assert.equal(h.revision, 1); });
test('M05S09-52 changed payload or actor collides on same key', () => { const f = fixture(), s = start(f), cmd = command(f, { kind: 'LINK', link: link(f) }), h = s.apply({ command: cmd, expectedRevision: 0, context: context(f, cmd.operation), grant: grant(f) }); const changed = ArchiveCommand.create({ id: cmd.id, scope: f.scope, change: cmd.change, submittedAt: NOW, idempotencyKey: cmd.idempotencyKey, reasonReference: 'changed' }); assert.throws(() => h.apply({ command: changed, expectedRevision: 0, context: context(f, cmd.operation), grant: grant(f) })); assert.throws(() => h.apply({ command: cmd, expectedRevision: 0, context: context(f, cmd.operation, NOW, { actor: ADMIN }), grant: grant(f, { actor: ADMIN }) })); });
test('M05S09-53 revision and reused command IDs are protected', () => { const f = fixture(), s = start(f), cmd = command(f, { kind: 'LINK', link: link(f) }); for (const revision of [-1, 0.5, NaN]) assert.throws(() => s.apply({ command: cmd, expectedRevision: revision, context: context(f, cmd.operation), grant: grant(f) })); const h = s.apply({ command: cmd, expectedRevision: 0, context: context(f, cmd.operation), grant: grant(f) }); const next = command(f, { kind: 'UNLINK', reference: uuid(100) }, 201); assert.throws(() => h.apply({ command: next, expectedRevision: 0, context: context(f, next.operation), grant: grant(f) })); const reused = ArchiveCommand.create({ id: cmd.id, scope: f.scope, change: next.change, submittedAt: NOW, idempotencyKey: 'other-key', reasonReference: 'reason:reuse' }); assert.throws(() => h.apply({ command: reused, expectedRevision: 1, context: context(f, reused.operation), grant: grant(f) })); });
test('M05S09-54 backdated command and replay are rejected', () => { const f = fixture(), s = start(f), cmd = command(f, { kind: 'LINK', link: link(f) }, 200, CAP), h = s.apply({ command: cmd, expectedRevision: 0, context: context(f, cmd.operation, NOW), grant: grant(f) }); assert.throws(() => h.apply({ command: cmd, expectedRevision: 0, context: context(f, cmd.operation, CAP), grant: grant(f) })); assert.throws(() => apply(f, h, { kind: 'UNLINK', reference: uuid(100) }, 201, OPEN)); });
test('M05S09-55 state collections and originals remain immutable', () => { const f = fixture(), s = start(f), before = JSON.stringify(f.archive), h = apply(f, s, { kind: 'LINK', link: link(f) }); assert.equal(s.revision, 0); assert.equal(s.links.length, 0); assert(Object.isFrozen(h)); assert(Object.isFrozen(h.records)); assert(Object.isFrozen(h.records[0])); assert.throws(() => (h.links as unknown[]).push({})); assert.equal(JSON.stringify(f.archive), before); assert.equal(Reflect.set(h, 'status', 'TOMBSTONED'), false); });
test('M05S09-56 foreign commands and payloads cannot cross histories', () => { const f = fixture(), g = fixture(20), s = start(f), foreign = command(g, { kind: 'LINK', link: link(g) }); assert.throws(() => s.apply({ command: foreign, expectedRevision: 0, context: context(f, foreign.operation), grant: grant(f) })); assert.throws(() => command(f, { kind: 'LINK', link: link(g) })); assert.throws(() => command(f, { kind: 'PLACE_HOLD', hold: hold(g) })); });
