import test from 'node:test';
import assert from 'node:assert/strict';
import { ActorId, ActorKind, ActorReference, AggregateId, AggregateType, ArtifactFormat, CommandId, ContentHash, CorrelationId, CredentialArtifact, CredentialArtifactId, CredentialArtifactKind, CredentialDefinitionId, CredentialDefinitionReference, DateOnly, EvidenceId, EvidenceKind, EvidenceReference, EvidenceSnapshot, ExternalArtifactReference, Jurisdiction, SourceId, SourceReference, SourceType, SubjectId, SubjectKind, SubjectReference, UtcInstant, VerificationState, VersionId } from '../../core/src/index.ts';
import { AccessDecisionReference, AccessDisposition, ApplicationExecutionContext, ApplicationOperationReference, AuditReference, OrganizationScopeReference, PurposeReference, TenantAccessDecision, TenantAccessDeniedError, TenantBoundary, TenantContext, TenantScopeReference } from '../src/index.ts';
import { CredentialLifecycleBasis } from '../src/lifecycle/credential-lifecycle-timeline.ts';
import { ExpiryRenewalPolicy, ExpiryRenewalEvaluation, LifecycleCalendarContext, EXPIRY_RENEWAL_OPERATION, EXPIRY_RENEWAL_FIELD } from '../src/lifecycle/expiry-renewal-policy.ts';
import { RecurringObligationRule, RecurringObligation, ObligationCompletionRecord, RecurringObligationProjection, RECURRING_OBLIGATION_OPERATION, RECURRING_OBLIGATION_FIELD } from '../src/lifecycle/recurring-obligation.ts';
import { RenewalCaseDefinition, RenewalEvidencePackage, RenewalCaseGrant, RenewalExternalObservation, RenewalCaseCommand, RenewalCaseHistory, RenewalRevisionConflictError, RENEWAL_CASE_OPERATION, RENEWAL_CASE_FIELD } from '../src/lifecycle/renewal-case.ts';
import type { RenewalCaseDefinitionInput, RenewalEvidencePackageInput, RenewalCaseGrantInput, RenewalExternalObservationInput, RenewalCaseCommandInput, RenewalCaseInvocation, RenewalCasePermission } from '../src/lifecycle/renewal-case.ts';

const uuid=(n:number)=>`018f3f7e-9999-7abc-8def-${String(n).padStart(12,'0')}`;
const at=(s:string)=>UtcInstant.from(s),day=(s:string)=>DateOnly.from(s),V=VersionId.from('v1');
const T0=at('2025-01-01T00:00:00Z'),CREATED=at('2025-11-01T00:00:00Z'),PKG=at('2025-12-01T10:00:00Z'),NOW=at('2025-12-01T12:00:00Z'),END=at('2027-01-01T00:00:00Z');
const human=(n:number)=>ActorReference.create(ActorId.from(uuid(n)),ActorKind.HUMAN_USER);
const APPLICANT=human(1),OPERATOR=human(2),ISSUER=human(3),REVIEWER=human(4),GRANTOR=human(5);
const SUBJECT=SubjectReference.create(SubjectId.from(uuid(6)),SubjectKind.PERSON),CZ=Jurisdiction.fromCode('CZ'),OTHER=Jurisdiction.fromCode('CZ-10');
const TENANT=TenantScopeReference.from('tenant:renewal'),ORG=OrganizationScopeReference.from('org:renewal'),PURPOSE=PurposeReference.from('purpose:renewal'),CORR=CorrelationId.from(uuid(7)),ACCESS=AccessDecisionReference.from('access:renewal');
const VERIFIED=VerificationState.from('VERIFIED'),UNVERIFIED=VerificationState.from('UNVERIFIED'),CLAIM='claim:renewal',EXTRA='claim:supplement';
const ALL:readonly RenewalCasePermission[]=['OPEN','READ','PREPARE','ATTACH_PACKAGE','MARK_READY','RECORD_EXTERNAL','RECORD_OUTCOME','CANCEL'];
const calendar=(time=NOW)=>LifecycleCalendarContext.create({evaluatedAt:time,evaluatedOn:day(time.toString().slice(0,10)),utcOffsetMinutes:0,calendarReference:'calendar:renewal:v1'});
function source(overrides:Partial<Parameters<typeof SourceReference.create>[0]>={}) {return SourceReference.create({id:SourceId.from(uuid(10)),authority:ISSUER,jurisdiction:CZ,sourceType:SourceType.ISSUER_RECORD,version:V,retrievedAt:T0,effectiveFrom:day('2025-01-01'),verificationState:VERIFIED,canonicalLocator:'https://PRIVATE-SOURCE.invalid',contentHash:ContentHash.sha256('a'.repeat(64)),...overrides});}
function evidence(time=PKG,src=source(),state=VERIFIED){return EvidenceSnapshot.capture([EvidenceReference.original({id:EvidenceId.from(uuid(11)),kind:EvidenceKind.DOCUMENT,contentReference:'s3://PRIVATE-EVIDENCE',acquiredAt:time,acquiredBy:APPLICANT,source:src,verificationState:state,contentHash:ContentHash.sha256('b'.repeat(64))})],time);}
function fixture(){const src=source(),artifact=CredentialArtifact.create({id:CredentialArtifactId.from(uuid(12)),kind:CredentialArtifactKind.CERTIFICATE,format:ArtifactFormat.DOCUMENT,subject:SUBJECT,issuer:ISSUER,issuedOn:day('2025-01-01'),effectiveFrom:day('2025-01-01'),expiresOn:day('2025-12-31'),verificationState:VERIFIED,evidenceSnapshot:evidence(T0,src),externalReference:ExternalArtifactReference.create({externalIdentifier:'PRIVATE-CREDENTIAL',locator:'s3://PRIVATE-ARTIFACT'})});return {src,artifact,basis:CredentialLifecycleBasis.bind({snapshotReference:'basis:renewal:v1',artifact,artifactVersion:V,credentialDefinition:CredentialDefinitionReference.create(CredentialDefinitionId.from(uuid(13)),V),aggregateId:AggregateId.from(uuid(14)),aggregateType:AggregateType.from('CREDENTIAL'),tenant:TENANT,organization:ORG,purpose:PURPOSE,jurisdiction:CZ,recordedAt:T0,sources:[src],ruleVersionRefs:[V]})};}
function context(overrides:Partial<Parameters<typeof ApplicationExecutionContext.create>[0]>={}){return ApplicationExecutionContext.create({operation:ApplicationOperationReference.from(RENEWAL_CASE_OPERATION),actor:OPERATOR,subject:SUBJECT,tenantScope:TENANT,organizationScope:ORG,purpose:PURPOSE,correlationId:CORR,requestedAt:NOW,contractVersion:V,accessDecision:ACCESS,...overrides});}
function reader(actor=OPERATOR){return TenantContext.create({tenant:TENANT,organization:ORG,purpose:PURPOSE,actor,correlationId:CORR});}
function access(overrides:Partial<Parameters<typeof TenantAccessDecision.create>[0]>={}){return TenantAccessDecision.create({reference:ACCESS,tenant:TENANT,purpose:PURPOSE,disposition:AccessDisposition.ALLOW,allowedFields:[RENEWAL_CASE_FIELD],decidedBy:GRANTOR,auditReference:AuditReference.from('audit:renewal'),...overrides});}
function definition(f=fixture(),overrides:Partial<RenewalCaseDefinitionInput>={}){return RenewalCaseDefinition.create({id:'renewal:1',version:V,basis:f.basis,applicant:APPLICANT,recipient:ISSUER,requiredClaims:[CLAIM],requiredOccurrences:[],planReference:'plan:renewal',planVersion:V,createdAt:CREATED,predecessorCaseReference:null,...overrides});}
function expiry(d:ReturnType<typeof definition>,overrides:Partial<Parameters<typeof ExpiryRenewalPolicy.create>[0]>={}){const policy=ExpiryRenewalPolicy.create({id:'policy:renewal',version:V,credentialDefinition:d.basis.credentialDefinition,jurisdiction:CZ,validFrom:day('2025-01-01'),validTo:null,knownAt:T0,source:source(),sourceSnapshotReference:'snapshot:policy',approvedAt:T0,approvedBy:ISSUER,approvalReference:'approval:policy',conditions:[],expiry:{kind:'DECLARED_EXPIRES_ON'},renewal:{mode:'WINDOW',opensDaysBeforeExpiry:90,dueDaysBeforeExpiry:0,graceDaysAfterDue:5},...overrides});return ExpiryRenewalEvaluation.evaluate({evaluationReference:'expiry:renewal',context:context({operation:ApplicationOperationReference.from(EXPIRY_RENEWAL_OPERATION),requestedAt:PKG}),authorizedContext:reader(),boundary:TenantBoundary.create([TENANT]),accessDecision:access({allowedFields:[EXPIRY_RENEWAL_FIELD]}),basis:d.basis,jurisdiction:CZ,calendar:calendar(PKG),policyEffectiveOn:day('2025-12-01'),selectionBasisReference:'selection:renewal',asKnownAt:PKG,policies:[policy]});}
function pack(d:ReturnType<typeof definition>,overrides:Partial<RenewalEvidencePackageInput>={}){return RenewalEvidencePackage.create({definition:d,reference:'package:1',expiry:expiry(d),evidenceSnapshot:evidence(),coveredClaims:[CLAIM],source:source(),reviewedBy:REVIEWER,reviewReference:'review:package',recordedAt:PKG,validUntil:at('2026-02-01T00:00:00Z'),obligationProjections:[],...overrides});}
function grant(d:ReturnType<typeof definition>,overrides:Partial<RenewalCaseGrantInput>={}){return RenewalCaseGrant.create({reference:'grant:renewal',version:V,definition:d,actor:OPERATOR,grantedBy:GRANTOR,permissions:ALL,grantedAt:CREATED,validFrom:CREATED,validUntil:END,revokedAt:null,approvalReference:'approval:case-access',...overrides});}
function invocation(d:ReturnType<typeof definition>,overrides:Partial<RenewalCaseInvocation>={},time=NOW,actor=OPERATOR):RenewalCaseInvocation{return {context:context({requestedAt:time,actor}),authorizedContext:reader(actor),boundary:TenantBoundary.create([TENANT]),accessDecision:access(),calendar:calendar(time),grant:grant(d,{actor}),...overrides};}
function cmd(d:ReturnType<typeof definition>,revision=0,overrides:Partial<RenewalCaseCommandInput>={}){return RenewalCaseCommand.create({id:CommandId.from(uuid(200+revision)),definition:d,expectedRevision:revision,idempotencyKey:`command:${revision}`,submittedAt:NOW,rationaleReference:'rationale:workflow',change:{kind:'PREPARE'},...overrides});}
const open=(d=definition(),i=invocation(d))=>RenewalCaseHistory.open({definition:d,invocation:i});
function step(h:RenewalCaseHistory,change:RenewalCaseCommandInput['change'],time=NOW,actor=OPERATOR){return h.apply({command:cmd(h.definition,h.revision,{change,submittedAt:time}),invocation:invocation(h.definition,{},time,actor)});}
function ready(d=definition(),p=pack(d)){let h=open(d);h=step(h,{kind:'PREPARE'});h=step(h,{kind:'ATTACH_PACKAGE',package:p});return step(h,{kind:'MARK_READY'});}
function observation(d:ReturnType<typeof definition>,overrides:Partial<RenewalExternalObservationInput>={}){const occurred=calendar(at('2025-12-02T10:00:00Z')),recordedAt=at('2025-12-02T11:00:00Z');return RenewalExternalObservation.create({definition:d,id:'external:1',kind:'SUBMISSION',submissionReference:'submission:1',packageReference:'package:1',occurred,recordedAt,source:source(),evidenceSnapshot:evidence(recordedAt),reviewedBy:REVIEWER,reviewReference:'review:external',requestedClaims:[],...overrides});}
const RECEIPT_TIME=at('2025-12-02T12:00:00Z'),OUTCOME_TIME=at('2025-12-04T12:00:00Z');
function submitted(d=definition()){return step(ready(d),{kind:'RECORD_EXTERNAL',observation:observation(d)},RECEIPT_TIME);}
function info(d:ReturnType<typeof definition>){return observation(d,{id:'external:information',kind:'INFORMATION_REQUEST',occurred:calendar(at('2025-12-03T10:00:00Z')),recordedAt:at('2025-12-03T11:00:00Z'),evidenceSnapshot:evidence(at('2025-12-03T11:00:00Z')),requestedClaims:[EXTRA]});}
function outcome(d:ReturnType<typeof definition>,kind:'RENEWAL'|'REJECTION'='RENEWAL'){return observation(d,{id:'external:outcome',kind,occurred:calendar(at('2025-12-04T10:00:00Z')),recordedAt:at('2025-12-04T11:00:00Z'),evidenceSnapshot:evidence(at('2025-12-04T11:00:00Z'))});}
function required(){const f=fixture(),rule=RecurringObligationRule.create({id:'rule:check',version:V,credentialDefinition:f.basis.credentialDefinition,jurisdiction:CZ,validFrom:day('2025-01-01'),validTo:null,knownAt:T0,source:f.src,sourceSnapshotReference:'snapshot:check',approvedAt:T0,approvedBy:ISSUER,approvalReference:'approval:check',conditions:[],kind:'EXAM',cadence:'FIXED_ANCHOR',interval:{amount:1,unit:'MONTHS',monthEnd:'CLAMP'},windowDaysBeforeDue:10,graceDaysAfterDue:0,requiredEvidenceClaims:['claim:exam']});const obligation=RecurringObligation.bind({id:'obligation:exam',version:V,basis:f.basis,rule,anchor:{kind:'ISSUED_ON'},recordedAt:T0}),d=definition(f,{requiredOccurrences:[{obligation,sequence:1}]});return {f,obligation,d};}
function projection(o:RecurringObligation,accepted=true){const record=ObligationCompletionRecord.create({id:'completion:exam',obligation:o,sequence:1,completedOn:day('2025-02-01'),recorded:calendar(PKG),disposition:'ACCEPTED',evidenceSnapshot:evidence(PKG,o.rule.source),coveredClaims:['claim:exam'],source:o.rule.source,reviewedBy:REVIEWER,reviewReference:'review:exam'});return RecurringObligationProjection.project({reference:'projection:exam',context:context({operation:ApplicationOperationReference.from(RECURRING_OBLIGATION_OPERATION),requestedAt:PKG}),authorizedContext:reader(),boundary:TenantBoundary.create([TENANT]),accessDecision:access({allowedFields:[RECURRING_OBLIGATION_FIELD]}),obligation:o,jurisdiction:CZ,calendar:calendar(PKG),asKnownAt:PKG,horizonOn:day('2025-12-31'),maxOccurrences:20,records:accepted?[record]:[]});}
const last=(h:RenewalCaseHistory)=>h.toJSON().records.at(-1)!;

test('M06S04-01 exact immutable definition preserves basis and plan',()=>{const f=fixture(),d=definition(f);assert.equal(d.basis,f.basis);assert.equal(d.planVersion,V);assert.equal(d.recipient,ISSUER);assert(Object.isFrozen(d));});
test('M06S04-02 invalid case and plan references rejected',()=>{for(const key of ['id','planReference'] as const)assert.throws(()=>definition(fixture(),{[key]:'raw text'}));});
test('M06S04-03 ungoverned definition and parties rejected',()=>{for(const key of ['version','basis','applicant','recipient','planVersion'] as const)assert.throws(()=>definition(fixture(),{[key]:{} as never}));});
test('M06S04-04 creation cannot predate basis knowledge',()=>{assert.throws(()=>definition(fixture(),{createdAt:at('2024-01-01T00:00:00Z')}));});
test('M06S04-05 claims dense bounded unique',()=>{for(const requiredClaims of [[],['x','x'],new Array<string>(2),Array(1001).fill('x')])assert.throws(()=>definition(fixture(),{requiredClaims}));});
test('M06S04-06 required S03 occurrence exact',()=>{const {d,obligation}=required();assert.equal(d.requiredOccurrences[0]!.obligation,obligation);});
test('M06S04-07 foreign occurrence basis rejected',()=>{const r=required();assert.throws(()=>definition(fixture(),{requiredOccurrences:r.d.requiredOccurrences}));});
test('M06S04-08 duplicate or invalid occurrence sequences rejected',()=>{const {f,obligation}=required();for(const sequence of [0,-1,0.5,10001])assert.throws(()=>definition(f,{requiredOccurrences:[{obligation,sequence}]}));assert.throws(()=>definition(f,{requiredOccurrences:[{obligation,sequence:1},{obligation,sequence:1}]}));});
test('M06S04-09 definition collections copied and frozen',()=>{const claims=[CLAIM],d=definition(fixture(),{requiredClaims:claims});claims.push(EXTRA);assert.deepEqual(d.requiredClaims,[CLAIM]);assert.throws(()=>(d.requiredClaims as string[]).push(EXTRA));});
test('M06S04-10 separate definition version preserves old',()=>{const f=fixture(),a=definition(f),before=JSON.stringify(a),b=definition(f,{id:'renewal:2',version:VersionId.from('v2'),predecessorCaseReference:a.id});assert.notEqual(a,b);assert.equal(JSON.stringify(a),before);});
test('M06S04-11 package preserves provenance',()=>{const d=definition(),p=pack(d);assert.equal(p.definition,d);assert.equal(p.source.authority,ISSUER);assert.equal(p.toJSON().reviewReference,'review:package');});
test('M06S04-12 foreign S02 basis rejected',()=>{const d=definition(),f=fixture(),other=definition(f,{id:'foreign:case'});assert.throws(()=>pack(d,{expiry:expiry(other)}));});
test('M06S04-13 ungoverned package evidence and evaluation rejected',()=>{const d=definition();assert.throws(()=>pack(d,{evidenceSnapshot:{} as never}));assert.throws(()=>pack(d,{expiry:{} as never}));});
test('M06S04-14 package recording and validity ordered',()=>{const d=definition();assert.throws(()=>pack(d,{validUntil:CREATED}));assert.throws(()=>pack(d,{recordedAt:T0}));});
test('M06S04-15 future-known evaluation or evidence rejected',()=>{const d=definition();assert.throws(()=>pack(d,{recordedAt:at('2025-12-01T09:00:00Z')}));assert.throws(()=>pack(d,{evidenceSnapshot:evidence(NOW)}));});
test('M06S04-16 covered claims dense bounded unique',()=>{const d=definition();for(const coveredClaims of [[CLAIM,CLAIM],new Array<string>(2),Array(1001).fill(CLAIM)])assert.throws(()=>pack(d,{coveredClaims}));});
test('M06S04-17 matching projection retained',()=>{const {d,obligation}=required(),p=projection(obligation),e=pack(d,{obligationProjections:[p]});assert.equal(e.obligationProjections[0],p);});
test('M06S04-18 foreign projection rejected',()=>{const {d}=required(),other=required();assert.throws(()=>pack(d,{obligationProjections:[projection(other.obligation)]}));});
test('M06S04-19 duplicate projection rejected',()=>{const {d,obligation}=required(),p=projection(obligation);assert.throws(()=>pack(d,{obligationProjections:[p,p]}));});
test('M06S04-20 package safe immutable metadata',()=>{const p=pack(definition());assert(Object.isFrozen(p));assert(Object.isFrozen(p.toJSON()));assert(!JSON.stringify(p).includes('PRIVATE'));});
test('M06S04-21 valid independent grant',()=>{const d=definition(),g=grant(d);assert.equal(g.actor,OPERATOR);assert.equal(g.definition,d);assert(Object.isFrozen(g.permissions));});
test('M06S04-22 nonhuman grantee rejected',()=>{assert.throws(()=>grant(definition(),{actor:ActorReference.create(OPERATOR.id,ActorKind.SYSTEM_PROCESS)}));});
test('M06S04-23 self grant rejected',()=>{assert.throws(()=>grant(definition(),{grantedBy:OPERATOR}));});
test('M06S04-24 invalid duplicate permissions rejected',()=>{for(const permissions of [[],['OPEN','OPEN'],['ADMIN']])assert.throws(()=>grant(definition(),{permissions:permissions as never}));});
test('M06S04-25 grant interval and revocation validated',()=>{const d=definition();assert.throws(()=>grant(d,{validUntil:T0}));assert.throws(()=>grant(d,{revokedAt:T0}));assert.throws(()=>grant(d,{grantedAt:T0}));});
test('M06S04-26 authorized opening draft revision0',()=>{const h=open();assert.equal(h.state,'DRAFT');assert.equal(h.revision,0);assert.deepEqual(h.toJSON().records,[]);});
test('M06S04-27 denial before sensitive processing',()=>{const d=definition(),i=invocation(d,{accessDecision:access({disposition:AccessDisposition.DENY})});assert.throws(()=>open({} as never,i),TenantAccessDeniedError);});
test('M06S04-28 cross tenant denied',()=>{const d=definition();assert.throws(()=>open(d,invocation(d,{context:context({tenantScope:TenantScopeReference.from('tenant:other')})})),TenantAccessDeniedError);});
test('M06S04-29 cross organization denied',()=>{const d=definition();assert.throws(()=>open(d,invocation(d,{context:context({organizationScope:OrganizationScopeReference.from('org:other')})})),TenantAccessDeniedError);});
test('M06S04-30 subject identity and kind mismatch denied',()=>{const d=definition();for(const subject of [SubjectReference.create(SubjectId.from(uuid(999)),SubjectKind.PERSON),SubjectReference.create(SUBJECT.id,SubjectKind.ORGANIZATION)])assert.throws(()=>open(d,invocation(d,{context:context({subject})})),TenantAccessDeniedError);});
test('M06S04-31 actor identity and kind mismatch denied',()=>{const d=definition();for(const actor of [REVIEWER,ActorReference.create(OPERATOR.id,ActorKind.SYSTEM_PROCESS)])assert.throws(()=>open(d,invocation(d,{context:context({actor})})),TenantAccessDeniedError);});
test('M06S04-32 purpose mismatch denied',()=>{const d=definition();assert.throws(()=>open(d,invocation(d,{context:context({purpose:PurposeReference.from('purpose:other')})})),TenantAccessDeniedError);});
test('M06S04-33 correlation mismatch denied',()=>{const d=definition();assert.throws(()=>open(d,invocation(d,{context:context({correlationId:CorrelationId.from(uuid(99))})})),TenantAccessDeniedError);});
test('M06S04-34 operation and field required',()=>{const d=definition();assert.throws(()=>open(d,invocation(d,{context:context({operation:ApplicationOperationReference.from('wrong.operation')})})));assert.throws(()=>open(d,invocation(d,{accessDecision:access({allowedFields:[]})})));});
test('M06S04-35 access reference mismatch denied',()=>{const d=definition();assert.throws(()=>open(d,invocation(d,{context:context({accessDecision:AccessDecisionReference.from('access:other')})})),TenantAccessDeniedError);});
test('M06S04-36 unknown tenant and foreign grant denied',()=>{const d=definition();assert.throws(()=>open(d,invocation(d,{boundary:TenantBoundary.create([TenantScopeReference.from('tenant:other')])})));assert.throws(()=>open(d,invocation(d,{grant:grant(definition())})));});
test('M06S04-37 expired revoked grants denied',()=>{const d=definition();assert.throws(()=>open(d,invocation(d,{grant:grant(d,{validUntil:PKG})})));assert.throws(()=>open(d,invocation(d,{grant:grant(d,{revokedAt:NOW})})));});
test('M06S04-38 wrong action permission denied',()=>{const d=definition(),h=open(d);assert.throws(()=>h.apply({command:cmd(d),invocation:invocation(d,{grant:grant(d,{permissions:['OPEN','READ']})})}));});
test('M06S04-39 calendar instant matches invocation',()=>{const d=definition();assert.throws(()=>open(d,invocation(d,{calendar:calendar(PKG)})));});
test('M06S04-40 guarded read rechecks permission',()=>{const d=definition(),h=open(d);assert.equal(h.read(invocation(d)).revision,0);assert.throws(()=>h.read(invocation(d,{accessDecision:access({disposition:AccessDisposition.DENY})})));});
test('M06S04-41 governed command identity and revision',()=>{const d=definition();assert.throws(()=>cmd(d,0,{id:'fake' as never}));for(const expectedRevision of [-1,0.5,Infinity])assert.throws(()=>cmd(d,0,{expectedRevision}));});
test('M06S04-42 unknown actions extra fields rejected',()=>{const d=definition();assert.throws(()=>cmd(d,0,{change:{kind:'AUTO_RENEW'} as never}));assert.throws(()=>cmd(d,0,{change:{kind:'PREPARE',extra:true} as never}));});
test('M06S04-43 foreign package observation rejected',()=>{const d=definition(),other=definition();assert.throws(()=>cmd(d,0,{change:{kind:'ATTACH_PACKAGE',package:pack(other)}}));assert.throws(()=>cmd(d,0,{change:{kind:'RECORD_EXTERNAL',observation:observation(other)}}));});
test('M06S04-44 command submission predates definition rejected',()=>{assert.throws(()=>cmd(definition(),0,{submittedAt:T0}));});
test('M06S04-45 command canonical input immutable',()=>{const d=definition(),c=cmd(d);assert(Object.isFrozen(c));assert(Object.isFrozen(c.change));assert.equal(JSON.stringify(c),JSON.stringify(cmd(d)));});
test('M06S04-46 prepare appends immutable record',()=>{const h=open(),next=step(h,{kind:'PREPARE'});assert.equal(h.revision,0);assert.equal(next.revision,1);assert.equal(next.state,'PREPARING');assert(Object.isFrozen(next.records[0]));});
test('M06S04-47 draft cannot skip preparation',()=>{const h=open();assert.throws(()=>step(h,{kind:'MARK_READY'}));assert.throws(()=>step(h,{kind:'ATTACH_PACKAGE',package:pack(h.definition)}));});
test('M06S04-48 attaching package retains earlier history',()=>{const d=definition(),h=step(open(d),{kind:'PREPARE'}),next=step(h,{kind:'ATTACH_PACKAGE',package:pack(d)});assert.equal(next.records[0],h.records[0]);assert.equal(next.state,'PREPARING');});
test('M06S04-49 missing package explicit blocker',()=>{const h=step(step(open(),{kind:'PREPARE'}),{kind:'MARK_READY'});assert.equal(h.state,'PREPARING');assert(last(h).reasonCodes.includes('EVIDENCE_PACKAGE_MISSING'));});
test('M06S04-50 qualified package marks ready',()=>{const h=ready();assert.equal(h.state,'READY');assert.equal(h.revision,3);assert.deepEqual(last(h).reasonCodes,[]);});
test('M06S04-51 missing required claim blocks ready',()=>{const d=definition(),h=ready(d,pack(d,{coveredClaims:[]}));assert.equal(h.state,'PREPARING');assert(last(h).reasonCodes.includes('REQUIRED_CLAIM_COVERAGE_MISSING'));});
test('M06S04-52 unverified package evidence blocks ready',()=>{const d=definition(),h=ready(d,pack(d,{evidenceSnapshot:evidence(PKG,source(),UNVERIFIED)}));assert.equal(h.state,'PREPARING');});
test('M06S04-53 source mismatch or unverified blocks ready',()=>{const d=definition();for(const src of [source({verificationState:UNVERIFIED}),source({id:SourceId.from(uuid(99))}),source({jurisdiction:OTHER})])assert.equal(ready(d,pack(d,{source:src})).state,'PREPARING');});
test('M06S04-54 expired package blocks ready',()=>{const d=definition(),h=ready(d,pack(d,{validUntil:PKG}));assert.equal(h.state,'PREPARING');assert(last(h).reasonCodes.includes('EVIDENCE_PACKAGE_EXPIRED'));});
test('M06S04-55 renewal before window blocks ready',()=>{const d=definition(),h=ready(d,pack(d,{expiry:expiry(d,{renewal:{mode:'WINDOW',opensDaysBeforeExpiry:10,dueDaysBeforeExpiry:0,graceDaysAfterDue:5}})}));assert.equal(h.state,'PREPARING');});
test('M06S04-56 due inclusive grace not readiness permission',()=>{const d=definition(),h=step(step(open(d),{kind:'PREPARE'}),{kind:'ATTACH_PACKAGE',package:pack(d)});assert.equal(step(h,{kind:'MARK_READY'},at('2025-12-31T12:00:00Z')).state,'READY');assert.equal(step(h,{kind:'MARK_READY'},at('2026-01-01T12:00:00Z')).state,'PREPARING');});
test('M06S04-57 unknown or unresolved policy blocks ready',()=>{const d=definition();for(const e of [expiry(d,{renewal:{mode:'UNKNOWN'}}),expiry(d,{conditions:['condition:unknown']})])assert.equal(ready(d,pack(d,{expiry:e})).state,'PREPARING');});
test('M06S04-58 missing mandatory projection blocks ready',()=>{const {d}=required();assert.equal(ready(d).state,'PREPARING');});
test('M06S04-59 unaccepted required occurrence blocks ready',()=>{const {d,obligation}=required();assert.equal(ready(d,pack(d,{obligationProjections:[projection(obligation,false)]})).state,'PREPARING');});
test('M06S04-60 accepted scoped occurrence permits ready',()=>{const {d,obligation}=required();assert.equal(ready(d,pack(d,{obligationProjections:[projection(obligation)]})).state,'READY');});
test('M06S04-61 package replacement invalidates ready',()=>{const d=definition(),h=step(ready(d),{kind:'ATTACH_PACKAGE',package:pack(d,{reference:'package:2'})});assert.equal(h.state,'PREPARING');assert.equal(h.toJSON().readyAt,null);});
test('M06S04-62 package reference cannot overwrite history',()=>{const d=definition(),h=ready(d);assert.throws(()=>step(h,{kind:'ATTACH_PACKAGE',package:pack(d,{coveredClaims:[]})}));});
test('M06S04-63 receipt required for external submission',()=>{const d=definition();assert.throws(()=>cmd(d,3,{change:{kind:'RECORD_EXTERNAL',observation:null} as never}));assert.throws(()=>step(open(d),{kind:'RECORD_EXTERNAL',observation:observation(d)},RECEIPT_TIME));});
test('M06S04-64 exact verified receipt records submitted no transport',()=>{const h=submitted();assert.equal(h.state,'SUBMITTED');assert.equal(h.toJSON().round,1);assert.equal(h.toJSON().submissionSent,false);});
test('M06S04-65 wrong recipient or unverified receipt rejected',()=>{const d=definition(),h=ready(d);for(const src of [source({authority:GRANTOR}),source({verificationState:UNVERIFIED})])assert.throws(()=>step(h,{kind:'RECORD_EXTERNAL',observation:observation(d,{source:src})},RECEIPT_TIME));});
test('M06S04-66 actual late receipt kept without extending validity',()=>{const d=definition(),time=at('2026-01-02T12:00:00Z'),o=observation(d,{occurred:calendar(at('2026-01-02T10:00:00Z')),recordedAt:at('2026-01-02T11:00:00Z'),evidenceSnapshot:evidence(at('2026-01-02T11:00:00Z'))}),h=step(ready(d),{kind:'RECORD_EXTERNAL',observation:o},time);assert.equal(h.state,'SUBMITTED');assert(last(h).reasonCodes.includes('EXTERNAL_SUBMISSION_AFTER_DUE'));assert.equal(d.basis.artifact.expiresOn!.toString(),'2025-12-31');});
test('M06S04-67 future or pre-ready occurrence rejected',()=>{const d=definition(),h=ready(d);assert.throws(()=>step(h,{kind:'RECORD_EXTERNAL',observation:observation(d)},NOW));assert.throws(()=>step(h,{kind:'RECORD_EXTERNAL',observation:observation(d,{occurred:calendar(PKG)})},RECEIPT_TIME));});
test('M06S04-68 repeated receipt not second submission',()=>{const d=definition(),h=submitted(d);assert.throws(()=>step(h,{kind:'RECORD_EXTERNAL',observation:observation(d)},RECEIPT_TIME));});
test('M06S04-69 information request adds claims with active submission',()=>{const d=definition(),h=step(submitted(d),{kind:'RECORD_EXTERNAL',observation:info(d)},at('2025-12-03T12:00:00Z'));assert.equal(h.state,'AWAITING_INFORMATION');assert(h.toJSON().requiredClaims.includes(EXTRA));});
test('M06S04-70 supplemental package must cover additional claims',()=>{const d=definition(),time=at('2025-12-03T12:00:00Z');let h=step(submitted(d),{kind:'RECORD_EXTERNAL',observation:info(d)},time);h=step(h,{kind:'ATTACH_PACKAGE',package:pack(d,{reference:'package:2'})},time);h=step(h,{kind:'MARK_READY'},time);assert.equal(h.state,'AWAITING_INFORMATION');assert(last(h).reasonCodes.includes('REQUIRED_CLAIM_COVERAGE_MISSING'));});
test('M06S04-71 supplemental submission preserves prior receipt and round',()=>{const d=definition(),time=at('2025-12-03T12:00:00Z');let h=step(submitted(d),{kind:'RECORD_EXTERNAL',observation:info(d)},time);h=step(h,{kind:'ATTACH_PACKAGE',package:pack(d,{reference:'package:2',coveredClaims:[CLAIM,EXTRA]})},time);h=step(h,{kind:'MARK_READY'},time);h=step(h,{kind:'RECORD_EXTERNAL',observation:observation(d,{id:'external:2',submissionReference:'submission:2',packageReference:'package:2',occurred:calendar(at('2025-12-04T10:00:00Z')),recordedAt:at('2025-12-04T11:00:00Z'),evidenceSnapshot:evidence(at('2025-12-04T11:00:00Z'))})},OUTCOME_TIME);assert.equal(h.state,'SUBMITTED');assert.equal(h.toJSON().round,2);assert(JSON.stringify(h).includes('submission:1'));});
test('M06S04-72 outcome requires current submission and package',()=>{const d=definition(),h=submitted(d);for(const patch of [{submissionReference:'submission:other'},{packageReference:'package:other'}])assert.throws(()=>step(h,{kind:'RECORD_EXTERNAL',observation:observation(d,{...patch,kind:'RENEWAL'})},OUTCOME_TIME,REVIEWER));});
test('M06S04-73 independent renewal recorded workflow only',()=>{const d=definition(),h=step(submitted(d),{kind:'RECORD_EXTERNAL',observation:outcome(d)},OUTCOME_TIME,REVIEWER);assert.equal(h.state,'RENEWAL_RECORDED');assert.equal(h.toJSON().authorizationAuthority,false);});
test('M06S04-74 external rejection does not revoke credential',()=>{const d=definition(),before=JSON.stringify(d.basis),h=step(submitted(d),{kind:'RECORD_EXTERNAL',observation:outcome(d,'REJECTION')},OUTCOME_TIME,REVIEWER);assert.equal(h.state,'REJECTION_RECORDED');assert.equal(JSON.stringify(d.basis),before);});
test('M06S04-75 applicant or submitting actor cannot record outcome',()=>{const d=definition(),h=submitted(d);for(const actor of [APPLICANT,OPERATOR])assert.throws(()=>step(h,{kind:'RECORD_EXTERNAL',observation:outcome(d)},OUTCOME_TIME,actor));});
test('M06S04-76 unverified outcome never becomes legal rejection',()=>{const d=definition(),h=submitted(d),o=observation(d,{kind:'REJECTION',evidenceSnapshot:evidence(at('2025-12-02T11:00:00Z'),source(),UNVERIFIED)});assert.throws(()=>step(h,{kind:'RECORD_EXTERNAL',observation:o},OUTCOME_TIME,REVIEWER));assert.equal(h.state,'SUBMITTED');});
test('M06S04-77 internal cancellation leaves external history intact',()=>{const d=definition(),h=submitted(d),next=step(h,{kind:'CANCEL'},OUTCOME_TIME);assert.equal(next.state,'CANCELLED');assert(JSON.stringify(next).includes('submission:1'));assert.equal(next.toJSON().externalWithdrawalPerformed,false);});
test('M06S04-78 terminal histories reject new commands',()=>{const h=step(open(),{kind:'CANCEL'});assert.throws(()=>step(h,{kind:'PREPARE'}));});
test('M06S04-79 exact replay retains identity revision',()=>{const d=definition(),h=open(d),c=cmd(d),next=h.apply({command:c,invocation:invocation(d)});assert.equal(next.apply({command:c,invocation:invocation(d)}),next);assert.equal(next.revision,1);});
test('M06S04-80 key collision changed command rejected',()=>{const d=definition(),h=step(open(d),{kind:'PREPARE'});assert.throws(()=>h.apply({command:cmd(d,0,{rationaleReference:'rationale:changed'}),invocation:invocation(d)}));});
test('M06S04-81 command identity new key rejected',()=>{const d=definition(),h=step(open(d),{kind:'PREPARE'});assert.throws(()=>h.apply({command:cmd(d,0,{idempotencyKey:'key:other'}),invocation:invocation(d)}));});
test('M06S04-82 stale revision distinct concurrency error',()=>{const d=definition(),h=step(open(d),{kind:'PREPARE'});assert.throws(()=>h.apply({command:cmd(d,0,{id:CommandId.from(uuid(999)),idempotencyKey:'new:key',change:{kind:'CANCEL'}}),invocation:invocation(d)}),RenewalRevisionConflictError);});
test('M06S04-83 invocation and submission chronology monotonic',()=>{const d=definition(),h=open(d);assert.throws(()=>h.apply({command:cmd(d),invocation:invocation(d,{},PKG)}));const later=step(h,{kind:'PREPARE'},RECEIPT_TIME);assert.throws(()=>step(later,{kind:'CANCEL'},NOW));});
test('M06S04-84 replay rechecks revoked grant and actor',()=>{const d=definition(),c=cmd(d),h=open(d).apply({command:c,invocation:invocation(d)});assert.throws(()=>h.apply({command:c,invocation:invocation(d,{grant:grant(d,{revokedAt:NOW})})}));assert.throws(()=>h.apply({command:c,invocation:invocation(d,{},NOW,REVIEWER)}));});
test('M06S04-85 foreign commands cannot cross history',()=>{const d=definition(),h=open(d);assert.throws(()=>h.apply({command:cmd(definition()),invocation:invocation(d)}));});
test('M06S04-86 deeply immutable metadata output',()=>{const h=submitted(),v=h.toJSON();assert(Object.isFrozen(v.records));assert(Object.isFrozen(v.records[0]));assert.throws(()=>(v.records as unknown[]).push({}));for(const bad of ['PRIVATE','s3://','https://'])assert(!JSON.stringify(v).includes(bad));});
test('M06S04-87 deterministic history and original inputs unchanged',()=>{const d=definition(),p=pack(d),before=JSON.stringify([d,p]),a=ready(d,p),b=ready(d,p);assert.equal(JSON.stringify(a),JSON.stringify(b));assert.equal(JSON.stringify([d,p]),before);});
test('M06S04-88 no automatic legal transport physical mutation',()=>{const d=definition(),h=step(submitted(d),{kind:'RECORD_EXTERNAL',observation:outcome(d)},OUTCOME_TIME,REVIEWER),v=h.toJSON();assert.equal(v.eventsEmitted,0);assert.equal(v.notificationScheduled,false);assert.equal(v.credentialStateMutated,false);assert.equal(v.renewalPerformed,false);assert.equal(v.submissionSent,false);assert.equal(v.authorizationAuthority,false);assert.equal(v.physicalDeletionAuthorized,false);});
