import test from 'node:test';
import assert from 'node:assert/strict';
import { ActorId, ActorKind, ActorReference, AggregateId, AggregateType, ArtifactFormat, ContentHash, CorrelationId, CredentialArtifact, CredentialArtifactId, CredentialArtifactKind, CredentialDefinitionId, CredentialDefinitionReference, DateOnly, EvidenceId, EvidenceKind, EvidenceReference, EvidenceSnapshot, ExternalArtifactReference, Jurisdiction, SourceId, SourceReference, SourceType, SubjectId, SubjectKind, SubjectReference, UtcInstant, VerificationState, VersionId } from '../../core/src/index.ts';
import { AccessDecisionReference, AccessDisposition, ApplicationExecutionContext, ApplicationOperationReference, AuditReference, OrganizationScopeReference, PurposeReference, TenantAccessDecision, TenantAccessDeniedError, TenantBoundary, TenantContext, TenantScopeReference } from '../src/index.ts';
import { CredentialLifecycleBasis, CredentialLifecycleTimelineReadModel, CREDENTIAL_LIFECYCLE_READ_OPERATION, CREDENTIAL_LIFECYCLE_READ_FIELD } from '../src/lifecycle/index.ts';
import { ExpiryRenewalPolicy, ExpiryRenewalEvaluation, LifecycleCalendarContext, shiftLifecycleDate, EXPIRY_RENEWAL_OPERATION, EXPIRY_RENEWAL_FIELD } from '../src/lifecycle/expiry-renewal-policy.ts';
import type { ExpiryRenewalPolicyInput, ExpiryRenewalEvaluationInput } from '../src/lifecycle/expiry-renewal-policy.ts';

const uuid=(n:number)=>`018f3f7e-7777-7abc-8def-${String(n).padStart(12,'0')}`;
const day=(s:string)=>DateOnly.from(s), at=(s:string)=>UtcInstant.from(s);
const T0=at('2025-01-01T00:00:00Z'), KNOWN=at('2026-09-01T00:00:00Z'), REQUEST=at('2028-01-01T00:00:00Z');
const V=VersionId.from('v1'), VERIFIED=VerificationState.from('VERIFIED');
const ACTOR=ActorReference.create(ActorId.from(uuid(1)),ActorKind.HUMAN_USER);
const ADMIN=ActorReference.create(ActorId.from(uuid(2)),ActorKind.HUMAN_USER);
const SUBJECT=SubjectReference.create(SubjectId.from(uuid(3)),SubjectKind.PERSON);
const TENANT=TenantScopeReference.from('tenant:renewal'), ORG=OrganizationScopeReference.from('org:renewal'), PURPOSE=PurposeReference.from('purpose:renewal');
const CZ=Jurisdiction.fromCode('CZ'), OTHER=Jurisdiction.fromCode('CZ-10');
const CORR=CorrelationId.from(uuid(4)), ACCESS=AccessDecisionReference.from('access:renewal');
type ArtifactInput=Parameters<typeof CredentialArtifact.create>[0];
type SourceInput=Parameters<typeof SourceReference.create>[0];
type ContextInput=Parameters<typeof ApplicationExecutionContext.create>[0];
function source(overrides:Partial<SourceInput>={}) {
  return SourceReference.create({id:SourceId.from(uuid(10)),authority:ADMIN,jurisdiction:CZ,sourceType:SourceType.ISSUER_RECORD,version:V,retrievedAt:T0,effectiveFrom:day('2025-01-01'),verificationState:VERIFIED,canonicalLocator:'https://PRIVATE-SOURCE.invalid',contentHash:ContentHash.sha256('a'.repeat(64)),...overrides});
}
function fixture(artifactOverrides:Partial<ArtifactInput>={}) {
  const src=source();
  const evidence=EvidenceReference.original({id:EvidenceId.from(uuid(11)),kind:EvidenceKind.DOCUMENT,contentReference:'s3://PRIVATE-DOCUMENT',acquiredAt:T0,acquiredBy:ACTOR,source:src,verificationState:VERIFIED,contentHash:ContentHash.sha256('b'.repeat(64))});
  const artifact=CredentialArtifact.create({id:CredentialArtifactId.from(uuid(12)),kind:CredentialArtifactKind.CERTIFICATE,format:ArtifactFormat.DOCUMENT,subject:SUBJECT,issuer:ADMIN,issuedOn:day('2026-01-01'),effectiveFrom:day('2026-01-01'),expiresOn:day('2026-12-31'),verificationState:VERIFIED,evidenceSnapshot:EvidenceSnapshot.capture([evidence],T0),externalReference:ExternalArtifactReference.create({externalIdentifier:'PRIVATE-CREDENTIAL',locator:'s3://PRIVATE-ARTIFACT'}),...artifactOverrides});
  const basis=CredentialLifecycleBasis.bind({snapshotReference:'basis:renewal:v1',artifact,artifactVersion:V,credentialDefinition:CredentialDefinitionReference.create(CredentialDefinitionId.from(uuid(13)),V),aggregateId:AggregateId.from(uuid(14)),aggregateType:AggregateType.from('CREDENTIAL'),tenant:TENANT,organization:ORG,purpose:PURPOSE,jurisdiction:CZ,recordedAt:KNOWN,sources:[src],ruleVersionRefs:[V]});
  return {basis,artifact,src,evidence};
}
type Fixture=ReturnType<typeof fixture>;
function policy(f:Fixture,overrides:Partial<ExpiryRenewalPolicyInput>={}) {
  return ExpiryRenewalPolicy.create({id:'policy:renewal',version:V,credentialDefinition:f.basis.credentialDefinition,jurisdiction:CZ,validFrom:day('2026-01-01'),validTo:null,knownAt:at('2026-02-01T00:00:00Z'),source:f.src,sourceSnapshotReference:'source:snapshot:v1',approvedAt:at('2026-01-01T00:00:00Z'),approvedBy:ADMIN,approvalReference:'approval:rule:v1',conditions:[],expiry:{kind:'DECLARED_EXPIRES_ON'},renewal:{mode:'WINDOW',opensDaysBeforeExpiry:60,dueDaysBeforeExpiry:30,graceDaysAfterDue:10},...overrides});
}
function calendar(s='2026-12-01') {return LifecycleCalendarContext.create({evaluatedAt:at(`${s}T12:00:00Z`),evaluatedOn:day(s),utcOffsetMinutes:60,calendarReference:'calendar:trusted-offset:v1'});}
function context(overrides:Partial<ContextInput>={}) {return ApplicationExecutionContext.create({operation:ApplicationOperationReference.from(EXPIRY_RENEWAL_OPERATION),actor:ACTOR,subject:SUBJECT,tenantScope:TENANT,organizationScope:ORG,purpose:PURPOSE,correlationId:CORR,requestedAt:REQUEST,contractVersion:V,accessDecision:ACCESS,...overrides});}
function reader(overrides:Partial<Parameters<typeof TenantContext.create>[0]>={}) {return TenantContext.create({tenant:TENANT,organization:ORG,purpose:PURPOSE,actor:ACTOR,correlationId:CORR,...overrides});}
function access(overrides:Partial<Parameters<typeof TenantAccessDecision.create>[0]>={}) {return TenantAccessDecision.create({reference:ACCESS,tenant:TENANT,purpose:PURPOSE,disposition:AccessDisposition.ALLOW,allowedFields:[EXPIRY_RENEWAL_FIELD],decidedBy:ADMIN,auditReference:AuditReference.from('audit:renewal'),...overrides});}
function query(f=fixture(),overrides:Partial<ExpiryRenewalEvaluationInput>={}):ExpiryRenewalEvaluationInput {return {evaluationReference:'evaluation:renewal:1',context:context(),authorizedContext:reader(),boundary:TenantBoundary.create([TENANT]),accessDecision:access(),basis:f.basis,jurisdiction:CZ,calendar:calendar(),policyEffectiveOn:day('2026-01-01'),selectionBasisReference:'selection:issuance-cohort:v1',asKnownAt:KNOWN,policies:[policy(f)],...overrides};}
function run(f=fixture(),overrides:Partial<ExpiryRenewalEvaluationInput>={}) {return ExpiryRenewalEvaluation.evaluate(query(f,overrides)).toJSON();}
const has=(result:ReturnType<typeof run>,reason:string)=>result.reasonCodes.includes(reason);
const finite=(overrides:Record<string,unknown>={})=>({kind:'AFTER_ANCHOR',anchor:'ISSUED_ON',amount:1,unit:'YEARS',monthEnd:'CLAMP',boundary:'ANNIVERSARY_DATE',...overrides} as const);

test('M06S02-01 policy preserves exact target source and version',()=>{const f=fixture(),p=policy(f);assert.equal(p.source,f.src);assert.equal(p.credentialDefinition,f.basis.credentialDefinition);assert.equal(p.version,V);assert(Object.isFrozen(p));});
test('M06S02-02 invalid policy references rejected',()=>{const f=fixture();for(const id of ['', 'bad reference','https://raw.invalid'])assert.throws(()=>policy(f,{id}));assert.throws(()=>policy(f,{approvalReference:' '}));assert.throws(()=>policy(f,{sourceSnapshotReference:'s3://raw'}));});
test('M06S02-03 governed policy versions and definitions required',()=>{const f=fixture();assert.throws(()=>policy(f,{version:'v1' as never}));assert.throws(()=>policy(f,{credentialDefinition:{} as never}));});
test('M06S02-04 governed source and approval actor required',()=>{const f=fixture();assert.throws(()=>policy(f,{source:{} as never}));assert.throws(()=>policy(f,{approvedBy:{} as never}));});
test('M06S02-05 future source retrieval rejected',()=>{const f=fixture();assert.throws(()=>policy(f,{source:source({retrievedAt:KNOWN})}));});
test('M06S02-06 approval after recorded knowledge rejected',()=>{const f=fixture();assert.throws(()=>policy(f,{approvedAt:KNOWN}));});
test('M06S02-07 inverted policy effectivity rejected',()=>{assert.throws(()=>policy(fixture(),{validTo:day('2025-12-31')}));});
test('M06S02-08 invalid duration quantities rejected',()=>{const f=fixture();for(const amount of [-1,0,1.5,NaN,Infinity,1001])assert.throws(()=>policy(f,{expiry:finite({amount}) as never}));});
test('M06S02-09 uncontrolled and extra expiry fields rejected',()=>{const f=fixture();for(const expiry of [{kind:'AUTO_RENEW'},{kind:'DECLARED_EXPIRES_ON',silentFallback:true},finite({anchor:'UNKNOWN'}),finite({monthEnd:'GUESS'}),finite({boundary:'AUTO'})])assert.throws(()=>policy(f,{expiry:expiry as never}));});
test('M06S02-10 invalid renewal windows rejected',()=>{const f=fixture();for(const renewal of [{mode:'WINDOW',opensDaysBeforeExpiry:-1,dueDaysBeforeExpiry:0,graceDaysAfterDue:0},{mode:'WINDOW',opensDaysBeforeExpiry:5,dueDaysBeforeExpiry:6,graceDaysAfterDue:0}])assert.throws(()=>policy(f,{renewal:renewal as never}));});
test('M06S02-11 invalid grace or extra renewal fields rejected',()=>{const f=fixture();for(const graceDaysAfterDue of [-1,NaN,1.5,365251])assert.throws(()=>policy(f,{renewal:{mode:'WINDOW',opensDaysBeforeExpiry:30,dueDaysBeforeExpiry:0,graceDaysAfterDue}}));assert.throws(()=>policy(f,{renewal:{mode:'NOT_REQUIRED',guess:true} as never}));});
test('M06S02-12 policy collections copied dense unique and frozen',()=>{const f=fixture(),conditions=['condition:review'];const p=policy(f,{conditions});conditions.push('later');assert.deepEqual(p.conditions,['condition:review']);assert(Object.isFrozen(p.expiry));assert(Object.isFrozen(p.renewal));assert.throws(()=>policy(f,{conditions:new Array(1)}));assert.throws(()=>policy(f,{conditions:['same','same']}));});
test('M06S02-13 explicit calendar offset context matches',()=>{const c=LifecycleCalendarContext.create({evaluatedAt:at('2026-12-01T23:30:00Z'),evaluatedOn:day('2026-12-02'),utcOffsetMinutes:60,calendarReference:'calendar:offset'});assert.equal(c.evaluatedOn.toString(),'2026-12-02');assert.equal(c.utcOffsetMinutes,60);});
test('M06S02-14 mismatched calendar date rejected',()=>{assert.throws(()=>LifecycleCalendarContext.create({evaluatedAt:at('2026-12-01T23:30:00Z'),evaluatedOn:day('2026-12-01'),utcOffsetMinutes:60,calendarReference:'calendar:offset'}));});
test('M06S02-15 invalid calendar offset rejected',()=>{for(const utcOffsetMinutes of [-841,841,NaN,1.5])assert.throws(()=>LifecycleCalendarContext.create({evaluatedAt:at('2026-12-01T12:00:00Z'),evaluatedOn:day('2026-12-01'),utcOffsetMinutes,calendarReference:'calendar:offset'}));});
test('M06S02-16 calendar requires governed time and date',()=>{assert.throws(()=>LifecycleCalendarContext.create({evaluatedAt:'bad' as never,evaluatedOn:day('2026-12-01'),utcOffsetMinutes:0,calendarReference:'calendar:offset'}));assert.throws(()=>LifecycleCalendarContext.create({evaluatedAt:at('2026-12-01T12:00:00Z'),evaluatedOn:'2026-12-01' as never,utcOffsetMinutes:0,calendarReference:'calendar:offset'}));});
test('M06S02-17 leap-day day arithmetic',()=>{assert.equal(shiftLifecycleDate(day('2024-02-28'),1,'DAYS','REJECT').toString(),'2024-02-29');assert.equal(shiftLifecycleDate(day('2024-02-28'),2,'DAYS','REJECT').toString(),'2024-03-01');});
test('M06S02-18 non-leap century arithmetic',()=>{assert.equal(shiftLifecycleDate(day('2100-02-28'),1,'DAYS','REJECT').toString(),'2100-03-01');});
test('M06S02-19 leap century arithmetic',()=>{assert.equal(shiftLifecycleDate(day('2000-02-28'),1,'DAYS','REJECT').toString(),'2000-02-29');});
test('M06S02-20 explicit month-end clamp',()=>{assert.equal(shiftLifecycleDate(day('2026-01-31'),1,'MONTHS','CLAMP').toString(),'2026-02-28');});
test('M06S02-21 explicit month-end rejection',()=>{assert.throws(()=>shiftLifecycleDate(day('2026-01-31'),1,'MONTHS','REJECT'),RangeError);});
test('M06S02-22 yearly leap adjustment',()=>{assert.equal(shiftLifecycleDate(day('2024-02-29'),1,'YEARS','CLAMP').toString(),'2025-02-28');assert.throws(()=>shiftLifecycleDate(day('2024-02-29'),1,'YEARS','REJECT'));});
test('M06S02-23 year boundary',()=>{assert.equal(shiftLifecycleDate(day('2026-12-31'),1,'DAYS','REJECT').toString(),'2027-01-01');});
test('M06S02-24 negative shifts',()=>{assert.equal(shiftLifecycleDate(day('2026-01-01'),-1,'DAYS','REJECT').toString(),'2025-12-31');assert.equal(shiftLifecycleDate(day('2024-03-31'),-1,'MONTHS','CLAMP').toString(),'2024-02-29');});
test('M06S02-25 range overflow and underflow',()=>{assert.throws(()=>shiftLifecycleDate(day('9999-12-31'),1,'DAYS','REJECT'));assert.throws(()=>shiftLifecycleDate(day('0001-01-01'),-1,'DAYS','REJECT'));assert.throws(()=>shiftLifecycleDate(day('9999-12-01'),1,'YEARS','CLAMP'));});
test('M06S02-26 invalid arithmetic arguments',()=>{assert.throws(()=>shiftLifecycleDate('2026-01-01' as never,1,'DAYS','CLAMP'));assert.throws(()=>shiftLifecycleDate(day('2026-01-01'),NaN,'DAYS','CLAMP'));assert.throws(()=>shiftLifecycleDate(day('2026-01-01'),1,'WEEKS' as never,'CLAMP'));assert.throws(()=>shiftLifecycleDate(day('2026-01-01'),1,'DAYS','AUTO' as never));});
test('M06S02-27 authorized scoped evaluation succeeds',()=>{const v=run();assert.equal(v.outcome,'EVALUATED');assert.equal(v.expiryOn,'2026-12-31');assert.equal(v.readerId,ACTOR.id.toString());});
test('M06S02-28 explicit denial wins',()=>{assert.throws(()=>run(fixture(),{accessDecision:access({disposition:AccessDisposition.DENY})}),TenantAccessDeniedError);});
test('M06S02-29 cross-tenant evaluation denied',()=>{assert.throws(()=>run(fixture(),{context:context({tenantScope:TenantScopeReference.from('tenant:other')})}),TenantAccessDeniedError);});
test('M06S02-30 organization mismatch denied',()=>{assert.throws(()=>run(fixture(),{context:context({organizationScope:OrganizationScopeReference.from('org:other')})}),TenantAccessDeniedError);});
test('M06S02-31 subject identity and kind mismatch denied',()=>{assert.throws(()=>run(fixture(),{context:context({subject:SubjectReference.create(SubjectId.from(uuid(99)),SubjectKind.PERSON)})}),TenantAccessDeniedError);assert.throws(()=>run(fixture(),{context:context({subject:null})}),TenantAccessDeniedError);});
test('M06S02-32 purpose mismatch denied',()=>{assert.throws(()=>run(fixture(),{context:context({purpose:PurposeReference.from('purpose:other')})}),TenantAccessDeniedError);});
test('M06S02-33 reader actor or kind mismatch denied',()=>{assert.throws(()=>run(fixture(),{authorizedContext:reader({actor:ADMIN})}),TenantAccessDeniedError);assert.throws(()=>run(fixture(),{authorizedContext:reader({actor:ActorReference.create(ACTOR.id,ActorKind.SYSTEM_PROCESS)})}),TenantAccessDeniedError);});
test('M06S02-34 correlation mismatch denied',()=>{assert.throws(()=>run(fixture(),{authorizedContext:reader({correlationId:CorrelationId.from(uuid(99))})}),TenantAccessDeniedError);});
test('M06S02-35 minimum field permission required',()=>{assert.throws(()=>run(fixture(),{accessDecision:access({allowedFields:[CREDENTIAL_LIFECYCLE_READ_FIELD]})}),TenantAccessDeniedError);});
test('M06S02-36 operation and access reference bound',()=>{assert.throws(()=>run(fixture(),{context:context({operation:ApplicationOperationReference.from('credential.issue')})}),TenantAccessDeniedError);assert.throws(()=>run(fixture(),{context:context({accessDecision:AccessDecisionReference.from('access:other')})}),TenantAccessDeniedError);});
test('M06S02-37 unknown tenant denied',()=>{assert.throws(()=>run(fixture(),{boundary:TenantBoundary.create([TenantScopeReference.from('tenant:other')])}),TenantAccessDeniedError);});
test('M06S02-38 requested jurisdiction must match',()=>{assert.throws(()=>run(fixture(),{jurisdiction:OTHER}),TenantAccessDeniedError);});
test('M06S02-39 denial precedes malformed sensitive basis',()=>{assert.throws(()=>run(fixture(),{basis:{} as never,policies:null as never,accessDecision:access({disposition:AccessDisposition.DENY})}),TenantAccessDeniedError);});
test('M06S02-40 future evaluation rejected',()=>{assert.throws(()=>run(fixture(),{calendar:calendar('2030-01-01')}),RangeError);});
test('M06S02-41 future knowledge rejected',()=>{assert.throws(()=>run(fixture(),{asKnownAt:at('2030-01-01T00:00:00Z')}),RangeError);});
test('M06S02-42 future-known basis rejected',()=>{assert.throws(()=>run(fixture(),{asKnownAt:at('2026-08-01T00:00:00Z')}),RangeError);});
test('M06S02-43 missing policy is indeterminate',()=>{const v=run(fixture(),{policies:[]});assert.equal(v.outcome,'INDETERMINATE');assert(has(v,'NO_APPLICABLE_POLICY'));assert.equal(v.expiryOn,null);});
test('M06S02-44 inclusive policy effectivity',()=>{const f=fixture(),p=policy(f,{validFrom:day('2026-01-01'),validTo:day('2026-06-30')});assert.equal(run(f,{policies:[p],policyEffectiveOn:day('2026-06-30')}).outcome,'EVALUATED');assert.equal(run(f,{policies:[p],policyEffectiveOn:day('2026-07-01')}).outcome,'INDETERMINATE');});
test('M06S02-45 exact definition ID and version',()=>{const f=fixture();for(const credentialDefinition of [CredentialDefinitionReference.create(CredentialDefinitionId.from(uuid(90)),V),CredentialDefinitionReference.create(f.basis.credentialDefinition.id,VersionId.from('v2'))])assert.equal(run(f,{policies:[policy(f,{credentialDefinition})]}).outcome,'INDETERMINATE');});
test('M06S02-46 policy jurisdiction selection',()=>{const f=fixture();assert.equal(run(f,{policies:[policy(f,{jurisdiction:OTHER})]}).outcome,'INDETERMINATE');});
test('M06S02-47 hidden future policy has no metadata contribution',()=>{const f=fixture(),p=policy(f),hidden=policy(f,{id:'PRIVATE-FUTURE-POLICY',knownAt:at('2027-01-01T00:00:00Z')});assert.deepEqual(run(f,{policies:[p,hidden]}),run(f,{policies:[p]}));});
test('M06S02-48 duplicate visible policy identity rejected',()=>{const f=fixture(),p=policy(f);assert.throws(()=>run(f,{policies:[p,p]}));});
test('M06S02-49 overlapping policies require review',()=>{const f=fixture();const v=run(f,{policies:[policy(f),policy(f,{version:VersionId.from('v2')})]});assert.equal(v.outcome,'REVIEW_REQUIRED');assert(has(v,'POLICY_AMBIGUOUS'));assert.equal(v.expiryOn,null);});
test('M06S02-50 ambiguity independent of candidate ordering',()=>{const f=fixture(),a=policy(f),b=policy(f,{version:VersionId.from('v2')});assert.deepEqual(run(f,{policies:[a,b]}),run(f,{policies:[b,a]}));});
test('M06S02-51 unverified and stale source require review',()=>{const f=fixture();for(const code of ['UNVERIFIED','STALE','FAILED']){const v=run(f,{policies:[policy(f,{source:source({verificationState:VerificationState.from(code)})})]});assert.equal(v.outcome,'REVIEW_REQUIRED');assert(has(v,'POLICY_SOURCE_UNVERIFIED'));}});
test('M06S02-52 unverified and stale artifact require review',()=>{for(const code of ['UNVERIFIED','STALE']){const v=run(fixture({verificationState:VerificationState.from(code)}));assert.equal(v.outcome,'REVIEW_REQUIRED');assert(has(v,'ARTIFACT_FACTS_UNVERIFIED'));}});
test('M06S02-53 unresolved conditions require review',()=>{const f=fixture(),v=run(f,{policies:[policy(f,{conditions:['condition:medical-review']})]});assert.equal(v.outcome,'REVIEW_REQUIRED');assert(has(v,'POLICY_CONDITIONS_UNRESOLVED'));});
test('M06S02-54 source jurisdiction and effectivity enforced',()=>{const f=fixture();for(const src of [source({jurisdiction:OTHER}),source({effectiveTo:day('2025-12-31')})])assert.equal(run(f,{policies:[policy(f,{source:src})]}).outcome,'REVIEW_REQUIRED');});
test('M06S02-55 declared expiry before-date relation',()=>{const v=run();assert.equal(v.expiryRelation,'BEFORE_EXPIRY');assert.equal(v.declaredExpiryOn,'2026-12-31');});
test('M06S02-56 declared expiry exact-date relation',()=>{assert.equal(run(fixture(),{calendar:calendar('2026-12-31')}).expiryRelation,'ON_EXPIRY_DATE');});
test('M06S02-57 after-expiry has no legal mutation',()=>{const v=run(fixture(),{calendar:calendar('2027-01-01')});assert.equal(v.expiryRelation,'AFTER_EXPIRY');assert.equal(v.legalValidityDetermined,false);assert.equal(v.eventsEmitted,0);});
test('M06S02-58 missing declared expiry remains indeterminate',()=>{const v=run(fixture({expiresOn:null}));assert.equal(v.outcome,'INDETERMINATE');assert(has(v,'DECLARED_EXPIRY_MISSING'));assert.equal(v.expiryRelation,'UNKNOWN');});
test('M06S02-59 finite duration from issuance',()=>{const f=fixture({expiresOn:null});const v=run(f,{policies:[policy(f,{expiry:finite()})]});assert.equal(v.expiryOn,'2027-01-01');assert.equal(v.calculatedExpiryOn,'2027-01-01');});
test('M06S02-60 finite duration from effectivity',()=>{const f=fixture({effectiveFrom:day('2026-03-01'),expiresOn:null});assert.equal(run(f,{policies:[policy(f,{expiry:finite({anchor:'EFFECTIVE_FROM',amount:6,unit:'MONTHS'}) as never})]}).expiryOn,'2026-09-01');});
test('M06S02-61 missing finite anchor remains unknown',()=>{const f=fixture({issuedOn:null,expiresOn:null}),v=run(f,{policies:[policy(f,{expiry:finite()})]});assert.equal(v.outcome,'INDETERMINATE');assert(has(v,'EXPIRY_ANCHOR_MISSING'));});
test('M06S02-62 computed and declared conflict requires review',()=>{const f=fixture(),v=run(f,{policies:[policy(f,{expiry:finite()})]});assert.equal(v.outcome,'REVIEW_REQUIRED');assert.equal(v.calculatedExpiryOn,'2027-01-01');assert.equal(v.declaredExpiryOn,'2026-12-31');assert.equal(v.expiryOn,null);assert(has(v,'EXPIRY_DATE_CONFLICT'));});
test('M06S02-63 explicit no-fixed-expiry is not null fallback',()=>{const f=fixture({expiresOn:null}),v=run(f,{policies:[policy(f,{expiry:{kind:'NO_FIXED_EXPIRY'},renewal:{mode:'NOT_REQUIRED'}})]});assert.equal(v.outcome,'EVALUATED');assert.equal(v.expiryRelation,'NO_FIXED_EXPIRY');assert.equal(v.renewalState,'NOT_REQUIRED');assert.equal(v.legalValidityDetermined,false);});
test('M06S02-64 no-fixed-expiry conflicts with declared expiry',()=>{const f=fixture(),v=run(f,{policies:[policy(f,{expiry:{kind:'NO_FIXED_EXPIRY'},renewal:{mode:'NOT_REQUIRED'}})]});assert.equal(v.outcome,'REVIEW_REQUIRED');assert(has(v,'EXPIRY_DATE_CONFLICT'));});
test('M06S02-65 opening boundary is inclusive',()=>{const f=fixture();assert.equal(run(f,{calendar:calendar('2026-10-31')}).renewalState,'NOT_YET_OPEN');const v=run(f,{calendar:calendar('2026-11-01')});assert.equal(v.windowOpensOn,'2026-11-01');assert.equal(v.renewalState,'OPEN');});
test('M06S02-66 renewal due boundary is inclusive',()=>{const f=fixture();assert.equal(run(f,{calendar:calendar('2026-11-30')}).renewalState,'OPEN');const v=run(f);assert.equal(v.renewalDueOn,'2026-12-01');assert.equal(v.renewalState,'DUE_TODAY');});
test('M06S02-67 grace is separate from credential expiry',()=>{const f=fixture();assert.equal(run(f,{calendar:calendar('2026-12-02')}).renewalState,'OVERDUE_WITHIN_GRACE');const atEnd=run(f,{calendar:calendar('2026-12-11')});assert.equal(atEnd.graceEndsOn,'2026-12-11');assert.equal(atEnd.renewalState,'OVERDUE_WITHIN_GRACE');assert.equal(run(f,{calendar:calendar('2026-12-12')}).renewalState,'OVERDUE');const p=policy(f,{renewal:{mode:'WINDOW',opensDaysBeforeExpiry:30,dueDaysBeforeExpiry:0,graceDaysAfterDue:10}});const late=run(f,{calendar:calendar('2027-01-01'),policies:[p]});assert.equal(late.expiryRelation,'AFTER_EXPIRY');assert.equal(late.renewalState,'OVERDUE_WITHIN_GRACE');assert.equal(late.expiryOn,'2026-12-31');});
test('M06S02-68 unknown renewal and no anchor are explicit',()=>{const f=fixture(),v=run(f,{policies:[policy(f,{renewal:{mode:'UNKNOWN'}})]});assert.equal(v.outcome,'INDETERMINATE');assert.equal(v.renewalState,'UNKNOWN');const g=fixture({expiresOn:null});assert.equal(run(g,{policies:[policy(g,{expiry:{kind:'NO_FIXED_EXPIRY'}})]}).outcome,'INDETERMINATE');});
test('M06S02-69 previous-day boundary and rejected adjustment',()=>{const f=fixture();assert.equal(run(f,{policies:[policy(f,{expiry:finite({boundary:'PREVIOUS_DAY'}) as never})]}).expiryOn,'2026-12-31');const g=fixture({issuedOn:day('2024-02-29'),expiresOn:null});const v=run(g,{policies:[policy(g,{expiry:finite({monthEnd:'REJECT'}) as never})]});assert.equal(v.outcome,'REVIEW_REQUIRED');assert(has(v,'CALENDAR_ADJUSTMENT_REQUIRED'));});
test('M06S02-70 immutable output and S01 upstream unchanged',()=>{const f=fixture(),before=JSON.stringify(f.basis),timeline=CredentialLifecycleTimelineReadModel.compose({context:context({operation:ApplicationOperationReference.from(CREDENTIAL_LIFECYCLE_READ_OPERATION)}),authorizedContext:reader(),boundary:TenantBoundary.create([TENANT]),accessDecision:access({allowedFields:[CREDENTIAL_LIFECYCLE_READ_FIELD]}),basis:f.basis,events:[],jurisdiction:CZ,evaluatedAt:calendar().evaluatedAt,asKnownAt:KNOWN});const originalTimeline=JSON.stringify(timeline);const v=run(f);assert(Object.isFrozen(v));assert(Object.isFrozen(v.trace));assert(Object.isFrozen(v.policy));assert(Object.isFrozen(v.basis));assert.equal(Reflect.set(v,'expiryOn','9999-12-31'),false);assert.equal(JSON.stringify(f.basis),before);assert.equal(JSON.stringify(timeline),originalTimeline);});
test('M06S02-71 safe metadata and reproducible calculation trace',()=>{const v=run(),serialized=JSON.stringify(v);for(const secret of ['PRIVATE-SOURCE','PRIVATE-DOCUMENT','PRIVATE-CREDENTIAL','PRIVATE-ARTIFACT'])assert(!serialized.includes(secret));assert.equal(v.policy!.version,'v1');assert.equal(v.policy!.sourceSnapshotReference,'source:snapshot:v1');assert(v.trace.some(step=>step.operation==='RENEWAL_DUE'));assert.equal(v.notificationScheduled,false);assert.equal(v.renewalPerformed,false);});
test('M06S02-72 repeatability and historical new-policy isolation',()=>{const f=fixture(),old=policy(f,{validTo:day('2026-06-30')}),fresh=policy(f,{version:VersionId.from('v2'),validFrom:day('2026-07-01'),knownAt:at('2026-10-01T00:00:00Z')});const q={policies:[old,fresh],policyEffectiveOn:day('2026-07-01')};const past=run(f,q);assert.equal(past.outcome,'INDETERMINATE');assert.equal(run(f,{...q,asKnownAt:at('2026-12-01T00:00:00Z')}).policy!.version,'v2');assert.deepEqual(run(f,q),past);assert.equal(past.policy,null);assert.throws(()=>run(f,{policies:new Array(1)}));});
