import test from 'node:test';
import assert from 'node:assert/strict';
import { ActorId, ActorKind, ActorReference, AggregateId, AggregateType, ArtifactFormat, CommandId, ContentHash, CorrelationId, CredentialArtifact, CredentialArtifactId, CredentialArtifactKind, CredentialDefinitionId, CredentialDefinitionReference, DateOnly, EvidenceId, EvidenceKind, EvidenceReference, EvidenceSnapshot, ExternalArtifactReference, Jurisdiction, SourceId, SourceReference, SourceType, SubjectId, SubjectKind, SubjectReference, UtcInstant, VerificationState, VersionId } from '../../core/src/index.ts';
import { AccessDecisionReference, AccessDisposition, ApplicationExecutionContext, ApplicationOperationReference, AuditReference, OrganizationScopeReference, PurposeReference, TenantAccessDecision, TenantAccessDeniedError, TenantBoundary, TenantContext, TenantScopeReference } from '../src/index.ts';
import { CredentialLifecycleBasis } from '../src/lifecycle/credential-lifecycle-timeline.ts';
import { ExpiryRenewalPolicy, ExpiryRenewalEvaluation, LifecycleCalendarContext, EXPIRY_RENEWAL_OPERATION, EXPIRY_RENEWAL_FIELD } from '../src/lifecycle/expiry-renewal-policy.ts';
import { RecurringObligationRule, RecurringObligation, RecurringObligationProjection, RECURRING_OBLIGATION_OPERATION, RECURRING_OBLIGATION_FIELD } from '../src/lifecycle/recurring-obligation.ts';
import { RenewalCaseDefinition, RenewalEvidencePackage, RenewalCaseGrant, RenewalExternalObservation, RenewalCaseCommand, RenewalCaseHistory, RENEWAL_CASE_OPERATION, RENEWAL_CASE_FIELD } from '../src/lifecycle/renewal-case.ts';
import { LifecycleNotificationPolicy, NotificationObservation, LifecycleNotificationProjection, NOTIFICATION_POLICY_OPERATION, NOTIFICATION_POLICY_FIELD } from '../src/lifecycle/notification-policy.ts';
import type { LifecycleNotificationPolicyInput, NotificationStageInput, NotificationObservationInput, NotificationProjectionInput } from '../src/lifecycle/notification-policy.ts';

const uuid=(n:number)=>'018f3f7e-aaaa-7abc-8def-'+String(n).padStart(12,'0');
const at=(s:string)=>UtcInstant.from(s),day=(s:string)=>DateOnly.from(s),V=VersionId.from('v1');
const T0=at('2025-01-01T00:00:00Z'),CREATED=at('2025-11-01T00:00:00Z'),CASE_NOW=at('2025-12-15T12:00:00Z'),NOW=at('2025-12-20T12:00:00Z'),END=at('2027-01-01T00:00:00Z');
const human=(n:number)=>ActorReference.create(ActorId.from(uuid(n)),ActorKind.HUMAN_USER);
const APPLICANT=human(1),OPERATOR=human(2),ISSUER=human(3),REVIEWER=human(4),GRANTOR=human(5);
const SUBJECT=SubjectReference.create(SubjectId.from(uuid(6)),SubjectKind.PERSON),CZ=Jurisdiction.fromCode('CZ'),OTHER=Jurisdiction.fromCode('CZ-10');
const TENANT=TenantScopeReference.from('tenant:notification'),ORG=OrganizationScopeReference.from('org:notification'),PURPOSE=PurposeReference.from('purpose:notification'),CORR=CorrelationId.from(uuid(7)),ACCESS=AccessDecisionReference.from('access:notification');
const VERIFIED=VerificationState.from('VERIFIED'),UNVERIFIED=VerificationState.from('UNVERIFIED'),CLAIM='claim:renewal';
const calendar=(time=NOW)=>LifecycleCalendarContext.create({evaluatedAt:time,evaluatedOn:day(time.toString().slice(0,10)),utcOffsetMinutes:0,calendarReference:'calendar:notification:v1'});
function source(overrides:Partial<Parameters<typeof SourceReference.create>[0]>={}){return SourceReference.create({id:SourceId.from(uuid(10)),authority:ISSUER,jurisdiction:CZ,sourceType:SourceType.ISSUER_RECORD,version:V,retrievedAt:T0,effectiveFrom:day('2025-01-01'),verificationState:VERIFIED,canonicalLocator:'https://PRIVATE-SOURCE.invalid',contentHash:ContentHash.sha256('a'.repeat(64)),...overrides});}
function evidence(time=T0,src=source(),state=VERIFIED){return EvidenceSnapshot.capture([EvidenceReference.original({id:EvidenceId.from(uuid(11)),kind:EvidenceKind.DOCUMENT,contentReference:'s3://PRIVATE-EVIDENCE',acquiredAt:time,acquiredBy:APPLICANT,source:src,verificationState:state,contentHash:ContentHash.sha256('b'.repeat(64))})],time);}
function fixture(marker='v1'){const src=source(),artifact=CredentialArtifact.create({id:CredentialArtifactId.from(uuid(12)),kind:CredentialArtifactKind.CERTIFICATE,format:ArtifactFormat.DOCUMENT,subject:SUBJECT,issuer:ISSUER,issuedOn:day('2025-01-01'),effectiveFrom:day('2025-01-01'),expiresOn:day('2025-12-31'),verificationState:VERIFIED,evidenceSnapshot:evidence(T0,src),externalReference:ExternalArtifactReference.create({externalIdentifier:'PRIVATE-CREDENTIAL',locator:'s3://PRIVATE-ARTIFACT'})});return {src,artifact,basis:CredentialLifecycleBasis.bind({snapshotReference:'basis:notification:'+marker,artifact,artifactVersion:V,credentialDefinition:CredentialDefinitionReference.create(CredentialDefinitionId.from(uuid(13)),V),aggregateId:AggregateId.from(uuid(14)),aggregateType:AggregateType.from('CREDENTIAL'),tenant:TENANT,organization:ORG,purpose:PURPOSE,jurisdiction:CZ,recordedAt:T0,sources:[src],ruleVersionRefs:[V]})};}
function context(operation=NOTIFICATION_POLICY_OPERATION,time=NOW,overrides:Partial<Parameters<typeof ApplicationExecutionContext.create>[0]>={}){return ApplicationExecutionContext.create({operation:ApplicationOperationReference.from(operation),actor:OPERATOR,subject:SUBJECT,tenantScope:TENANT,organizationScope:ORG,purpose:PURPOSE,correlationId:CORR,requestedAt:time,contractVersion:V,accessDecision:ACCESS,...overrides});}
function reader(actor=OPERATOR){return TenantContext.create({tenant:TENANT,organization:ORG,purpose:PURPOSE,actor,correlationId:CORR});}
function access(field=NOTIFICATION_POLICY_FIELD,overrides:Partial<Parameters<typeof TenantAccessDecision.create>[0]>={}){return TenantAccessDecision.create({reference:ACCESS,tenant:TENANT,purpose:PURPOSE,disposition:AccessDisposition.ALLOW,allowedFields:[field],decidedBy:GRANTOR,auditReference:AuditReference.from('audit:notification'),...overrides});}
function expiry(basis:CredentialLifecycleBasis,time=NOW,overrides:Partial<Parameters<typeof ExpiryRenewalPolicy.create>[0]>={},extraPolicies:readonly ExpiryRenewalPolicy[]=[]){const p=ExpiryRenewalPolicy.create({id:'policy:renewal',version:V,credentialDefinition:basis.credentialDefinition,jurisdiction:CZ,validFrom:day('2025-01-01'),validTo:null,knownAt:T0,source:source(),sourceSnapshotReference:'snapshot:renewal',approvedAt:T0,approvedBy:ISSUER,approvalReference:'approval:renewal',conditions:[],expiry:{kind:'DECLARED_EXPIRES_ON'},renewal:{mode:'WINDOW',opensDaysBeforeExpiry:90,dueDaysBeforeExpiry:0,graceDaysAfterDue:5},...overrides});return ExpiryRenewalEvaluation.evaluate({evaluationReference:'expiry:notification',context:context(EXPIRY_RENEWAL_OPERATION,time),authorizedContext:reader(),boundary:TenantBoundary.create([TENANT]),accessDecision:access(EXPIRY_RENEWAL_FIELD),basis,jurisdiction:CZ,calendar:calendar(time),policyEffectiveOn:day(time.toString().slice(0,10)),selectionBasisReference:'selection:notification',asKnownAt:time,policies:[p,...extraPolicies]});}
const baseStage=(patch:Partial<NotificationStageInput>={}):NotificationStageInput=>({id:'stage:window',level:1,trigger:{kind:'WINDOW_OPENS'},offsetDays:0,dedupWindowDays:7,audiencePurpose:'audience:holder',intentKind:'REMINDER',...patch});
function policy(f=fixture(),overrides:Partial<LifecycleNotificationPolicyInput>={}){return LifecycleNotificationPolicy.create({id:'notification:policy',version:V,basis:f.basis,validFrom:day('2025-01-01'),validTo:null,knownAt:T0,source:f.src,sourceSnapshotReference:'snapshot:notification',approvedAt:T0,approvedBy:ISSUER,approvalReference:'approval:notification',stages:[baseStage()],...overrides});}
function projectionInput(p:LifecycleNotificationPolicy,overrides:Partial<NotificationProjectionInput>={}):NotificationProjectionInput{return {context:context(),authorizedContext:reader(),boundary:TenantBoundary.create([TENANT]),accessDecision:access(),policy:p,calendar:calendar(),asKnownAt:NOW,evaluation:expiry(p.basis),history:null,obligationProjections:[],observations:[],...overrides};}
const project=(p=policy(),overrides:Partial<NotificationProjectionInput>={})=>LifecycleNotificationProjection.evaluate(projectionInput(p,overrides));
function obs(p:LifecycleNotificationPolicy,overrides:Partial<NotificationObservationInput>={}){const v=project(p).toJSON(),stageId=v.stageId??p.stages[0]!.id,triggerIdentity=v.triggerIdentity??'WINDOW_OPENS:2025-10-02',audiencePurpose=p.stages.find(s=>s.id===stageId)!.audiencePurpose;return NotificationObservation.create({policy:p,id:'observation:1',kind:'RECORDED',stageId,triggerIdentity,audiencePurpose,dedupKey:p.deduplicationKey(stageId,triggerIdentity),occurredAt:at('2025-12-18T12:00:00Z'),recordedAt:at('2025-12-18T12:05:00Z'),provenanceReference:'provider-record:1',...overrides});}
function caseDefinition(f=fixture(),id='renewal:case'){return RenewalCaseDefinition.create({id,version:V,basis:f.basis,applicant:APPLICANT,recipient:ISSUER,requiredClaims:[CLAIM],requiredOccurrences:[],planReference:'plan:renewal',planVersion:V,createdAt:CREATED,predecessorCaseReference:null});}
function caseAccess(){return access(RENEWAL_CASE_FIELD);}
function caseContext(time:UtcInstant,actor=OPERATOR){return context(RENEWAL_CASE_OPERATION,time,{actor});}
function caseGrant(d:RenewalCaseDefinition,actor=OPERATOR){return RenewalCaseGrant.create({reference:'grant:renewal',version:V,definition:d,actor,grantedBy:GRANTOR,permissions:['OPEN','READ','PREPARE','ATTACH_PACKAGE','MARK_READY','RECORD_EXTERNAL','RECORD_OUTCOME','CANCEL'],grantedAt:CREATED,validFrom:CREATED,validUntil:END,revokedAt:null,approvalReference:'approval:case'});}
function caseInvocation(d:RenewalCaseDefinition,time:UtcInstant,actor=OPERATOR){return {context:caseContext(time,actor),authorizedContext:reader(actor),boundary:TenantBoundary.create([TENANT]),accessDecision:caseAccess(),calendar:calendar(time),grant:caseGrant(d,actor)};}
let commandSeq=300;
function caseStep(h:RenewalCaseHistory,change:Parameters<typeof RenewalCaseCommand.create>[0]['change'],time:UtcInstant,actor=OPERATOR){const c=RenewalCaseCommand.create({id:CommandId.from(uuid(commandSeq++)),definition:h.definition,expectedRevision:h.revision,idempotencyKey:'case-command:'+String(commandSeq),submittedAt:time,rationaleReference:'rationale:case',change});return h.apply({command:c,invocation:caseInvocation(h.definition,time,actor)});}
function casePackage(d:RenewalCaseDefinition,time=CASE_NOW){return RenewalEvidencePackage.create({definition:d,reference:'package:case',expiry:expiry(d.basis,time),evidenceSnapshot:evidence(time),coveredClaims:[CLAIM],source:source(),reviewedBy:REVIEWER,reviewReference:'review:package',recordedAt:time,validUntil:at('2026-02-01T00:00:00Z'),obligationProjections:[]});}
function readyHistory(d:RenewalCaseDefinition){let h=RenewalCaseHistory.open({definition:d,invocation:caseInvocation(d,CASE_NOW)});h=caseStep(h,{kind:'PREPARE'},CASE_NOW);h=caseStep(h,{kind:'ATTACH_PACKAGE',package:casePackage(d)},CASE_NOW);return caseStep(h,{kind:'MARK_READY'},CASE_NOW);}
function external(d:RenewalCaseDefinition,kind:'SUBMISSION'|'INFORMATION_REQUEST'|'RENEWAL'|'REJECTION',time:UtcInstant,id:string){return RenewalExternalObservation.create({definition:d,id,kind,submissionReference:'submission:case',packageReference:'package:case',occurred:calendar(time),recordedAt:time,source:source(),evidenceSnapshot:evidence(time),reviewedBy:REVIEWER,reviewReference:'review:'+id,requestedClaims:kind==='INFORMATION_REQUEST'?['claim:supplement']:[]});}
function submittedHistory(d:RenewalCaseDefinition){return caseStep(readyHistory(d),{kind:'RECORD_EXTERNAL',observation:external(d,'SUBMISSION',at('2025-12-16T12:00:00Z'),'external:submission')},at('2025-12-16T12:00:00Z'));}
function terminalHistory(d:RenewalCaseDefinition,kind:'RENEWAL'|'REJECTION'|'CANCEL'){if(kind==='CANCEL')return caseStep(RenewalCaseHistory.open({definition:d,invocation:caseInvocation(d,CASE_NOW)}),{kind:'CANCEL'},CASE_NOW);return caseStep(submittedHistory(d),{kind:'RECORD_EXTERNAL',observation:external(d,kind,at('2025-12-17T12:00:00Z'),'external:'+kind.toLowerCase())},at('2025-12-17T12:00:00Z'),REVIEWER);}
function awaitingHistory(d:RenewalCaseDefinition){return caseStep(submittedHistory(d),{kind:'RECORD_EXTERNAL',observation:external(d,'INFORMATION_REQUEST',at('2025-12-17T12:00:00Z'),'external:info')},at('2025-12-17T12:00:00Z'));}
function obligation(f=fixture()){const rule=RecurringObligationRule.create({id:'rule:annual',version:V,credentialDefinition:f.basis.credentialDefinition,jurisdiction:CZ,validFrom:day('2025-01-01'),validTo:null,knownAt:T0,source:f.src,sourceSnapshotReference:'snapshot:obligation',approvedAt:T0,approvedBy:ISSUER,approvalReference:'approval:obligation',conditions:[],kind:'EXAM',cadence:'FIXED_ANCHOR',interval:{amount:1,unit:'YEARS',monthEnd:'CLAMP'},windowDaysBeforeDue:30,graceDaysAfterDue:5,requiredEvidenceClaims:['claim:exam']});return RecurringObligation.bind({id:'obligation:annual',version:V,basis:f.basis,rule,anchor:{kind:'ISSUED_ON'},recordedAt:T0});}
function obligationProjection(o:RecurringObligation){return RecurringObligationProjection.project({reference:'projection:annual',context:context(RECURRING_OBLIGATION_OPERATION,NOW),authorizedContext:reader(),boundary:TenantBoundary.create([TENANT]),accessDecision:access(RECURRING_OBLIGATION_FIELD),obligation:o,jurisdiction:CZ,calendar:calendar(),asKnownAt:NOW,horizonOn:day('2026-02-01'),maxOccurrences:10,records:[]});}

test('M06S05-01 exact immutable policy identity',()=>{const f=fixture(),p=policy(f);assert.equal(p.basis,f.basis);assert.equal(p.version,V);assert(Object.isFrozen(p));});
test('M06S05-02 ungoverned policy identity or version rejected',()=>{assert.throws(()=>policy(fixture(),{id:'raw text'}));assert.throws(()=>policy(fixture(),{version:{} as never}));});
test('M06S05-03 governed source and approver required',()=>{assert.throws(()=>policy(fixture(),{source:{} as never}));assert.throws(()=>policy(fixture(),{approvedBy:{} as never}));});
test('M06S05-04 source retrieval cannot postdate knowledge',()=>{assert.throws(()=>policy(fixture(),{source:source({retrievedAt:NOW})}));});
test('M06S05-05 approval cannot postdate knowledge',()=>{assert.throws(()=>policy(fixture(),{approvedAt:NOW}));});
test('M06S05-06 effectivity cannot invert',()=>{assert.throws(()=>policy(fixture(),{validFrom:day('2026-01-01'),validTo:day('2025-01-01')}));});
test('M06S05-07 target definition and jurisdiction explicit',()=>{const p=policy();assert.equal(p.toJSON().credentialDefinition.id,p.basis.credentialDefinition.id.toString());assert.equal(p.toJSON().jurisdiction,'CZ');});
test('M06S05-08 stage collection bounded dense',()=>{assert.throws(()=>policy(fixture(),{stages:new Array<NotificationStageInput>(2)}));assert.throws(()=>policy(fixture(),{stages:Array(1001).fill(baseStage())}));});
test('M06S05-09 empty stage collection rejected',()=>{assert.throws(()=>policy(fixture(),{stages:[]}));});
test('M06S05-10 duplicate stage IDs rejected',()=>{assert.throws(()=>policy(fixture(),{stages:[baseStage(),baseStage({level:2})]}));});
test('M06S05-11 stage levels unique ordered',()=>{assert.throws(()=>policy(fixture(),{stages:[baseStage(),baseStage({id:'stage:two',level:1})]}));assert.throws(()=>policy(fixture(),{stages:[baseStage({level:2}),baseStage({id:'stage:two',level:1})]}));});
test('M06S05-12 unknown stage fields rejected',()=>{assert.throws(()=>policy(fixture(),{stages:[{...baseStage(),extra:true} as never]}));});
test('M06S05-13 controlled trigger anchors only',()=>{assert.throws(()=>policy(fixture(),{stages:[baseStage({trigger:{kind:'AMBIENT_TIME'} as never})]}));});
test('M06S05-14 controlled intent kinds only',()=>{assert.throws(()=>policy(fixture(),{stages:[baseStage({intentKind:'SEND_NOW' as never})]}));});
test('M06S05-15 audience purpose bounded',()=>{assert.throws(()=>policy(fixture(),{stages:[baseStage({audiencePurpose:'bad value'})]}));});
test('M06S05-16 offset bounded',()=>{assert.throws(()=>policy(fixture(),{stages:[baseStage({offsetDays:3651})]}));});
test('M06S05-17 dedup window bounded',()=>{assert.throws(()=>policy(fixture(),{stages:[baseStage({dedupWindowDays:3651})]}));});
test('M06S05-18 stage collection copied frozen',()=>{const stages=[baseStage()],p=policy(fixture(),{stages});stages.push(baseStage({id:'stage:later',level:2}));assert.equal(p.stages.length,1);assert(Object.isFrozen(p.stages));});
test('M06S05-19 safe policy serialization',()=>{const v=JSON.stringify(policy());for(const bad of ['PRIVATE','s3://','https://'])assert(!v.includes(bad));});
test('M06S05-20 version replacement preserves prior',()=>{const f=fixture(),a=policy(f),before=JSON.stringify(a),b=policy(f,{id:'notification:policy:v2',version:VersionId.from('v2')});assert.notEqual(a,b);assert.equal(JSON.stringify(a),before);});
test('M06S05-21 observation exact identities',()=>{const p=policy(),o=obs(p);assert.equal(o.policy,p);assert.equal(o.stageId,'stage:window');});
test('M06S05-22 foreign observation policy rejected',()=>{const p=policy(),other=policy(fixture(),{id:'notification:other'});assert.throws(()=>NotificationObservation.create({...obs(other),policy:p} as never));});
test('M06S05-23 policy version mismatch rejected',()=>{const f=fixture(),p=policy(f),v2=policy(f,{id:'notification:v2',version:VersionId.from('v2')}),o=obs(v2);assert.throws(()=>project(p,{observations:[o]}));});
test('M06S05-24 foreign stage rejected',()=>{const p=policy();assert.throws(()=>obs(p,{stageId:'stage:missing'}));});
test('M06S05-25 controlled observation kind',()=>{assert.throws(()=>obs(policy(),{kind:'SENT_MAGIC' as never}));});
test('M06S05-26 observation chronology',()=>{assert.throws(()=>obs(policy(),{occurredAt:NOW,recordedAt:at('2025-12-19T00:00:00Z')}));});
test('M06S05-27 future observation rejected at horizon',()=>{const p=policy(),o=obs(p,{occurredAt:at('2025-12-21T00:00:00Z'),recordedAt:at('2025-12-21T00:00:00Z')});assert.throws(()=>project(p,{observations:[o]}));});
test('M06S05-28 dedup key must match identity',()=>{assert.throws(()=>obs(policy(),{dedupKey:'wrong'}));});
test('M06S05-29 observation audience must match stage',()=>{assert.throws(()=>obs(policy(),{audiencePurpose:'audience:other'}));});
test('M06S05-30 observation trigger identity must match dedup identity',()=>{const p=policy();assert.throws(()=>obs(p,{triggerIdentity:'WINDOW_OPENS:2099-01-01',dedupKey:'wrong'}));});
test('M06S05-31 duplicate observation identity rejected',()=>{const p=policy(),o=obs(p);assert.throws(()=>project(p,{observations:[o,o]}));});
test('M06S05-32 observation collection bounded dense',()=>{const p=policy();assert.throws(()=>project(p,{observations:new Array<NotificationObservation>(2)}));assert.throws(()=>project(p,{observations:Array(1001).fill(obs(p))}));});
test('M06S05-33 observation metadata immutable provider neutral',()=>{const o=obs(policy()),v=JSON.stringify(o);assert(Object.isFrozen(o));for(const bad of ['PRIVATE','s3://','https://'])assert(!v.includes(bad));});
test('M06S05-34 explicit scoped invocation required',()=>{const p=policy();assert.throws(()=>LifecycleNotificationProjection.evaluate({...projectionInput(p),context:{} as never}));});
test('M06S05-35 denial before projection',()=>{const p=policy();assert.throws(()=>LifecycleNotificationProjection.evaluate({...projectionInput(p),policy:{} as never,accessDecision:access(NOTIFICATION_POLICY_FIELD,{disposition:AccessDisposition.DENY})}),TenantAccessDeniedError);});
test('M06S05-36 cross tenant denied',()=>{const p=policy();assert.throws(()=>project(p,{context:context(NOTIFICATION_POLICY_OPERATION,NOW,{tenantScope:TenantScopeReference.from('tenant:other')})}),TenantAccessDeniedError);});
test('M06S05-37 cross organization denied',()=>{const p=policy();assert.throws(()=>project(p,{context:context(NOTIFICATION_POLICY_OPERATION,NOW,{organizationScope:OrganizationScopeReference.from('org:other')})}),TenantAccessDeniedError);});
test('M06S05-38 subject identity denied',()=>{const p=policy(),s=SubjectReference.create(SubjectId.from(uuid(999)),SubjectKind.PERSON);assert.throws(()=>project(p,{context:context(NOTIFICATION_POLICY_OPERATION,NOW,{subject:s})}),TenantAccessDeniedError);});
test('M06S05-39 subject kind denied',()=>{const p=policy(),s=SubjectReference.create(SUBJECT.id,SubjectKind.ORGANIZATION);assert.throws(()=>project(p,{context:context(NOTIFICATION_POLICY_OPERATION,NOW,{subject:s})}),TenantAccessDeniedError);});
test('M06S05-40 actor identity denied',()=>{const p=policy();assert.throws(()=>project(p,{context:context(NOTIFICATION_POLICY_OPERATION,NOW,{actor:REVIEWER})}),TenantAccessDeniedError);});
test('M06S05-41 actor kind denied',()=>{const p=policy(),a=ActorReference.create(OPERATOR.id,ActorKind.SYSTEM_PROCESS);assert.throws(()=>project(p,{context:context(NOTIFICATION_POLICY_OPERATION,NOW,{actor:a})}),TenantAccessDeniedError);});
test('M06S05-42 purpose denied',()=>{const p=policy();assert.throws(()=>project(p,{context:context(NOTIFICATION_POLICY_OPERATION,NOW,{purpose:PurposeReference.from('purpose:other')})}),TenantAccessDeniedError);});
test('M06S05-43 correlation denied',()=>{const p=policy();assert.throws(()=>project(p,{context:context(NOTIFICATION_POLICY_OPERATION,NOW,{correlationId:CorrelationId.from(uuid(99))})}),TenantAccessDeniedError);});
test('M06S05-44 operation required',()=>{const p=policy();assert.throws(()=>project(p,{context:context('wrong.operation')}),TenantAccessDeniedError);});
test('M06S05-45 field permission required',()=>{const p=policy();assert.throws(()=>project(p,{accessDecision:access(NOTIFICATION_POLICY_FIELD,{allowedFields:[]})}),TenantAccessDeniedError);});
test('M06S05-46 access reference mismatch denied',()=>{const p=policy();assert.throws(()=>project(p,{context:context(NOTIFICATION_POLICY_OPERATION,NOW,{accessDecision:AccessDecisionReference.from('access:other')})}),TenantAccessDeniedError);});
test('M06S05-47 calendar matches invocation',()=>{const p=policy();assert.throws(()=>project(p,{calendar:calendar(CASE_NOW)}));});
test('M06S05-48 exact S02 basis accepted',()=>{const p=policy(),v=project(p);assert.equal(v.toJSON().basisSnapshotReference,p.basis.snapshotReference);});
test('M06S05-49 foreign S02 basis rejected',()=>{const p=policy(),foreign=fixture('foreign');assert.throws(()=>project(p,{evaluation:expiry(foreign.basis)}));});
test('M06S05-50 unresolved S02 yields review required',()=>{const p=policy(),e=expiry(p.basis,NOW,{renewal:{mode:'UNKNOWN'}});assert.equal(project(p,{evaluation:e}).toJSON().outcome,'REVIEW_REQUIRED');});
test('M06S05-51 ambiguous S02 yields review required',()=>{const p=policy(),other=ExpiryRenewalPolicy.create({id:'policy:other',version:V,credentialDefinition:p.basis.credentialDefinition,jurisdiction:CZ,validFrom:day('2025-01-01'),validTo:null,knownAt:T0,source:source(),sourceSnapshotReference:'snapshot:other',approvedAt:T0,approvedBy:ISSUER,approvalReference:'approval:other',conditions:[],expiry:{kind:'DECLARED_EXPIRES_ON'},renewal:{mode:'WINDOW',opensDaysBeforeExpiry:60,dueDaysBeforeExpiry:0,graceDaysAfterDue:5}}),e=expiry(p.basis,NOW,{},[other]);assert.equal(project(p,{evaluation:e}).toJSON().outcome,'REVIEW_REQUIRED');});
test('M06S05-52 missing renewal trigger review',()=>{const p=policy(),e=expiry(p.basis,NOW,{renewal:{mode:'NOT_REQUIRED'}});assert.equal(project(p,{evaluation:e}).toJSON().outcome,'REVIEW_REQUIRED');});
test('M06S05-53 window trigger selects due',()=>{assert.equal(project().toJSON().outcome,'DUE');});
test('M06S05-54 due trigger selects due',()=>{const p=policy(fixture(),{stages:[baseStage({id:'stage:due',trigger:{kind:'RENEWAL_DUE'},offsetDays:-20})]});assert.equal(project(p).toJSON().outcome,'DUE');});
test('M06S05-55 grace trigger selects due',()=>{const p=policy(fixture(),{stages:[baseStage({id:'stage:grace',trigger:{kind:'GRACE_END'},offsetDays:-30})]});assert.equal(project(p).toJSON().outcome,'DUE');});
test('M06S05-56 future threshold suppressed',()=>{const p=policy(fixture(),{stages:[baseStage({id:'stage:due',trigger:{kind:'RENEWAL_DUE'},offsetDays:0})]});assert.equal(project(p).toJSON().outcome,'SUPPRESSED');});
test('M06S05-57 highest crossed stage wins',()=>{const p=policy(fixture(),{stages:[baseStage(),baseStage({id:'stage:due',level:2,trigger:{kind:'RENEWAL_DUE'},offsetDays:-20,intentKind:'ESCALATION'})]}),v=project(p).toJSON();assert.equal(v.stageId,'stage:due');assert.equal(v.level,2);});
test('M06S05-58 lower stages superseded reason',()=>{const p=policy(fixture(),{stages:[baseStage(),baseStage({id:'stage:due',level:2,trigger:{kind:'RENEWAL_DUE'},offsetDays:-20,intentKind:'ESCALATION'})]});assert(project(p).toJSON().reasonCodes.some(x=>x.includes('SUPERSEDED')));});
test('M06S05-59 single base stage is due',()=>{assert.equal(project().toJSON().outcome,'DUE');});
test('M06S05-60 higher stage escalates',()=>{const p=policy(fixture(),{stages:[baseStage(),baseStage({id:'stage:due',level:2,trigger:{kind:'RENEWAL_DUE'},offsetDays:-20,intentKind:'ESCALATION'})]});assert.equal(project(p).toJSON().outcome,'ESCALATED');});
test('M06S05-61 failed delivery does not escalate',()=>{const p=policy(),o=obs(p,{kind:'FAILED'});assert.equal(project(p,{observations:[o]}).toJSON().outcome,'DUE');});
test('M06S05-62 silence does not escalate',()=>{assert.equal(project().toJSON().outcome,'DUE');});
for(const [n,kind] of [[63,'RECORDED'],[64,'DELIVERED'],[65,'ACKNOWLEDGED']] as const)test('M06S05-'+String(n).padStart(2,'0')+' prior '+kind.toLowerCase()+' deduplicates',()=>{const p=policy(),o=obs(p,{kind});assert.equal(project(p,{observations:[o]}).toJSON().outcome,'SUPPRESSED');});
test('M06S05-66 observation outside dedup window not suppressed',()=>{const p=policy(),o=obs(p,{occurredAt:at('2025-12-01T12:00:00Z'),recordedAt:at('2025-12-01T12:05:00Z')});assert.equal(project(p,{observations:[o]}).toJSON().outcome,'DUE');});
test('M06S05-67 foreign dedup identity rejected',()=>{const p=policy(),other=policy(fixture(),{id:'notification:other'}),o=obs(other);assert.throws(()=>project(p,{observations:[o]}));});
test('M06S05-68 different stage does not dedup selected stage',()=>{const p=policy(fixture(),{stages:[baseStage(),baseStage({id:'stage:due',level:2,trigger:{kind:'RENEWAL_DUE'},offsetDays:-20,intentKind:'ESCALATION'})]}),stage1=LifecycleNotificationPolicy.create({...p,stages:p.stages} as never);void stage1;const trigger='WINDOW_OPENS:2025-10-02',o=NotificationObservation.create({policy:p,id:'observation:stage1',kind:'DELIVERED',stageId:'stage:window',triggerIdentity:trigger,audiencePurpose:'audience:holder',dedupKey:p.deduplicationKey('stage:window',trigger),occurredAt:at('2025-12-18T12:00:00Z'),recordedAt:at('2025-12-18T12:05:00Z'),provenanceReference:'provider:stage1'});assert.equal(project(p,{observations:[o]}).toJSON().outcome,'ESCALATED');});
test('M06S05-69 different audience does not dedup selected audience',()=>{const p=policy(fixture(),{stages:[baseStage(),baseStage({id:'stage:due',level:2,trigger:{kind:'RENEWAL_DUE'},offsetDays:-20,audiencePurpose:'audience:supervisor',intentKind:'ESCALATION'})]}),trigger='WINDOW_OPENS:2025-10-02',o=NotificationObservation.create({policy:p,id:'observation:holder',kind:'DELIVERED',stageId:'stage:window',triggerIdentity:trigger,audiencePurpose:'audience:holder',dedupKey:p.deduplicationKey('stage:window',trigger),occurredAt:at('2025-12-18T12:00:00Z'),recordedAt:at('2025-12-18T12:05:00Z'),provenanceReference:'provider:holder'});assert.equal(project(p,{observations:[o]}).toJSON().stageId,'stage:due');});
test('M06S05-70 failed observation not successful delivery',()=>{const p=policy(),o=obs(p,{kind:'FAILED'}),v=project(p,{observations:[o]}).toJSON();assert.equal(v.outcome,'DUE');assert(!v.reasonCodes.includes('DEDUPLICATED'));});
test('M06S05-71 suppressed observation preserves history only',()=>{const p=policy(),o=obs(p,{kind:'SUPPRESSED'}),before=JSON.stringify(o);assert.equal(project(p,{observations:[o]}).toJSON().outcome,'DUE');assert.equal(JSON.stringify(o),before);});
test('M06S05-72 stable dedup key deterministic',()=>{const p=policy(),a=project(p).toJSON(),b=project(p).toJSON();assert.equal(a.dedupKey,b.dedupKey);});
test('M06S05-73 policy version changes dedup identity',()=>{const f=fixture(),a=policy(f),b=policy(f,{id:'notification:v2',version:VersionId.from('v2')}),av=project(a).toJSON(),bv=project(b,{evaluation:expiry(b.basis)}).toJSON();assert.notEqual(av.dedupKey,bv.dedupKey);});
test('M06S05-74 trigger identity changes dedup identity',()=>{const p=policy(fixture(),{stages:[baseStage(),baseStage({id:'stage:due',level:2,trigger:{kind:'RENEWAL_DUE'},offsetDays:-20,intentKind:'ESCALATION'})]}),a=p.deduplicationKey('stage:window','WINDOW_OPENS:2025-10-02'),b=p.deduplicationKey('stage:due','RENEWAL_DUE:2025-12-31');assert.notEqual(a,b);});
test('M06S05-75 exact S04 history accepted',()=>{const f=fixture(),p=policy(f),d=caseDefinition(f),h=terminalHistory(d,'CANCEL');assert.equal(project(p,{history:h}).toJSON().outcome,'SUPPRESSED');});
test('M06S05-76 foreign S04 history rejected',()=>{const p=policy(),h=terminalHistory(caseDefinition(fixture('foreign'),'renewal:foreign'),'CANCEL');assert.throws(()=>project(p,{history:h}));});
test('M06S05-77 renewal-recorded suppresses obsolete reminder',()=>{const f=fixture(),p=policy(f),h=terminalHistory(caseDefinition(f),'RENEWAL');assert.equal(project(p,{history:h}).toJSON().outcome,'SUPPRESSED');});
test('M06S05-78 rejection-recorded suppresses obsolete reminder',()=>{const f=fixture(),p=policy(f),h=terminalHistory(caseDefinition(f),'REJECTION');assert.equal(project(p,{history:h}).toJSON().outcome,'SUPPRESSED');});
test('M06S05-79 cancelled case suppresses without credential mutation',()=>{const f=fixture(),p=policy(f),h=terminalHistory(caseDefinition(f),'CANCEL'),v=project(p,{history:h}).toJSON();assert.equal(v.outcome,'SUPPRESSED');assert.equal(v.credentialStateMutated,false);});
test('M06S05-80 submitted state not renewal completion',()=>{const f=fixture(),p=policy(f),h=submittedHistory(caseDefinition(f));assert.equal(project(p,{history:h}).toJSON().outcome,'DUE');});
test('M06S05-81 awaiting information does not fabricate urgency',()=>{const f=fixture(),p=policy(f),h=awaitingHistory(caseDefinition(f));assert.equal(project(p,{history:h}).toJSON().outcome,'DUE');});
test('M06S05-82 missing case history does not fabricate workflow',()=>{const v=project().toJSON();assert.equal(v.caseState,null);assert.equal(v.outcome,'DUE');});
test('M06S05-83 exact obligation projection can trigger',()=>{const f=fixture(),o=obligation(f),op=obligationProjection(o),p=policy(f,{stages:[baseStage({id:'stage:obligation',trigger:{kind:'OBLIGATION_DUE',occurrenceReference:o.occurrenceReference(1)},offsetDays:-14})]});assert.equal(project(p,{obligationProjections:[op]}).toJSON().outcome,'DUE');});
test('M06S05-84 foreign obligation projection rejected',()=>{const f=fixture(),p=policy(f),fo=obligation(fixture('foreign'));assert.throws(()=>project(p,{obligationProjections:[obligationProjection(fo)]}));});
test('M06S05-85 missing obligation occurrence requires review',()=>{const f=fixture(),o=obligation(f),p=policy(f,{stages:[baseStage({id:'stage:obligation',trigger:{kind:'OBLIGATION_DUE',occurrenceReference:o.occurrenceReference(1)},offsetDays:-14})]});assert.equal(project(p).toJSON().outcome,'REVIEW_REQUIRED');});
test('M06S05-86 exact occurrence date drives stage',()=>{const f=fixture(),o=obligation(f),op=obligationProjection(o),p=policy(f,{stages:[baseStage({id:'stage:obligation',trigger:{kind:'OBLIGATION_DUE',occurrenceReference:o.occurrenceReference(1)},offsetDays:-14})]}),v=project(p,{obligationProjections:[op]}).toJSON();assert(v.triggerIdentity!.includes(o.occurrenceReference(1)));});
test('M06S05-87 pre-effectivity observation cannot suppress',()=>{const p=policy(fixture(),{validFrom:day('2025-12-10')}),v=project(p).toJSON(),o=NotificationObservation.create({policy:p,id:'observation:old',kind:'DELIVERED',stageId:v.stageId!,triggerIdentity:v.triggerIdentity!,audiencePurpose:'audience:holder',dedupKey:v.dedupKey!,occurredAt:at('2025-12-05T12:00:00Z'),recordedAt:at('2025-12-05T12:05:00Z'),provenanceReference:'provider:old'});assert.equal(project(p,{observations:[o]}).toJSON().outcome,'REVIEW_REQUIRED');});
test('M06S05-88 future-known observation fails closed',()=>{const p=policy(),o=obs(p,{occurredAt:at('2025-12-21T12:00:00Z'),recordedAt:at('2025-12-21T12:05:00Z')});assert.throws(()=>project(p,{observations:[o]}));});
test('M06S05-89 reasons unique deterministic',()=>{const a=project().toJSON().reasonCodes,b=project().toJSON().reasonCodes;assert.deepEqual(a,b);assert.equal(new Set(a).size,a.length);});
test('M06S05-90 output deeply readonly',()=>{const v=project().toJSON();assert(Object.isFrozen(v));assert(Object.isFrozen(v.reasonCodes));assert.throws(()=>(v.reasonCodes as string[]).push('x'));});
test('M06S05-91 output omits raw evidence locators',()=>{const v=JSON.stringify(project());for(const bad of ['s3://','PRIVATE-EVIDENCE','PRIVATE-ARTIFACT'])assert(!v.includes(bad));});
test('M06S05-92 output omits contact provider message data',()=>{const v=JSON.stringify(project());for(const bad of ['@','phone','providerToken','messageBody'])assert(!v.includes(bad));});
test('M06S05-93 negative authority flags preserved',()=>{const v=project().toJSON();assert.equal(v.authorizationAuthority,false);assert.equal(v.credentialStateMutated,false);assert.equal(v.renewalPerformed,false);assert.equal(v.notificationScheduled,false);assert.equal(v.notificationSent,false);assert.equal(v.providerInvoked,false);assert.equal(v.eventsEmitted,0);assert.equal(v.physicalDeletionAuthorized,false);});
test('M06S05-94 equivalent replay byte stable',()=>{const p=policy(),input=projectionInput(p);assert.equal(JSON.stringify(LifecycleNotificationProjection.evaluate(input)),JSON.stringify(LifecycleNotificationProjection.evaluate(input)));});
test('M06S05-95 original inputs unchanged',()=>{const p=policy(),o=obs(p),before=JSON.stringify([p,o]);project(p,{observations:[o]});assert.equal(JSON.stringify([p,o]),before);});
test('M06S05-96 observation budget exact',()=>{const p=policy(),base=obs(p),many=Array.from({length:1000},(_,i)=>NotificationObservation.create({policy:p,id:'observation:'+String(i+10),kind:'FAILED',stageId:base.stageId,triggerIdentity:base.triggerIdentity,audiencePurpose:base.audiencePurpose,dedupKey:base.dedupKey,occurredAt:at('2025-12-18T12:00:00Z'),recordedAt:at('2025-12-18T12:05:00Z'),provenanceReference:'provider:'+String(i+10)}));assert.doesNotThrow(()=>project(p,{observations:many}));assert.throws(()=>project(p,{observations:[...many,base]}));});
