import test from 'node:test';
import assert from 'node:assert/strict';
import { ActorId, ActorKind, ActorReference, AggregateId, AggregateType, ArtifactFormat, ContentHash, CorrelationId, CredentialArtifact, CredentialArtifactId, CredentialArtifactKind, CredentialDefinitionId, CredentialDefinitionReference, DateOnly, EvidenceId, EvidenceKind, EvidenceReference, EvidenceSnapshot, ExternalArtifactReference, Jurisdiction, SourceId, SourceReference, SourceType, SubjectId, SubjectKind, SubjectReference, UtcInstant, VerificationState, VersionId } from '../../core/src/index.ts';
import { AccessDecisionReference, AccessDisposition, ApplicationExecutionContext, ApplicationOperationReference, AuditReference, OrganizationScopeReference, PurposeReference, TenantAccessDecision, TenantAccessDeniedError, TenantBoundary, TenantContext, TenantScopeReference } from '../src/index.ts';
import { CredentialLifecycleBasis } from '../src/lifecycle/credential-lifecycle-timeline.ts';
import { LifecycleCalendarContext, shiftLifecycleDate } from '../src/lifecycle/expiry-renewal-policy.ts';
import { RecurringObligationRule, RecurringObligation, ObligationCompletionRecord, RecurringObligationProjection, RECURRING_OBLIGATION_OPERATION, RECURRING_OBLIGATION_FIELD } from '../src/lifecycle/recurring-obligation.ts';
import type { RecurringObligationRuleInput, RecurringObligationInput, ObligationCompletionRecordInput, RecurringObligationProjectionInput } from '../src/lifecycle/recurring-obligation.ts';

const uuid=(n:number)=>`018f3f7e-8888-7abc-8def-${String(n).padStart(12,'0')}`;
const day=(s:string)=>DateOnly.from(s),at=(s:string)=>UtcInstant.from(s);
const T0=at('2025-01-01T00:00:00Z'),REQUEST=at('2028-01-01T00:00:00Z'),V=VersionId.from('v1');
const VERIFIED=VerificationState.from('VERIFIED'),UNVERIFIED=VerificationState.from('UNVERIFIED');
const ACTOR=ActorReference.create(ActorId.from(uuid(1)),ActorKind.HUMAN_USER),ADMIN=ActorReference.create(ActorId.from(uuid(2)),ActorKind.HUMAN_USER);
const SUBJECT=SubjectReference.create(SubjectId.from(uuid(3)),SubjectKind.PERSON),CZ=Jurisdiction.fromCode('CZ'),OTHER=Jurisdiction.fromCode('CZ-10');
const TENANT=TenantScopeReference.from('tenant:recurrence'),ORG=OrganizationScopeReference.from('org:recurrence'),PURPOSE=PurposeReference.from('purpose:recurrence'),CORR=CorrelationId.from(uuid(4)),ACCESS=AccessDecisionReference.from('access:recurrence');
const CLAIM='claim:periodic-check';
function source(overrides:Partial<Parameters<typeof SourceReference.create>[0]>={}) {return SourceReference.create({id:SourceId.from(uuid(10)),authority:ADMIN,jurisdiction:CZ,sourceType:SourceType.ISSUER_RECORD,version:V,retrievedAt:T0,effectiveFrom:day('2025-01-01'),verificationState:VERIFIED,canonicalLocator:'https://PRIVATE-SOURCE.invalid',contentHash:ContentHash.sha256('a'.repeat(64)),...overrides});}
function fixture(overrides:Partial<Parameters<typeof CredentialArtifact.create>[0]>={}) {
  const src=source(),evidence=EvidenceReference.original({id:EvidenceId.from(uuid(11)),kind:EvidenceKind.DOCUMENT,contentReference:'s3://PRIVATE-EVIDENCE',acquiredAt:T0,acquiredBy:ACTOR,source:src,verificationState:VERIFIED,contentHash:ContentHash.sha256('b'.repeat(64))});
  const artifact=CredentialArtifact.create({id:CredentialArtifactId.from(uuid(12)),kind:CredentialArtifactKind.CERTIFICATE,format:ArtifactFormat.DOCUMENT,subject:SUBJECT,issuer:ADMIN,issuedOn:day('2025-01-31'),effectiveFrom:day('2025-02-01'),expiresOn:day('2025-12-31'),verificationState:VERIFIED,evidenceSnapshot:EvidenceSnapshot.capture([evidence],T0),externalReference:ExternalArtifactReference.create({externalIdentifier:'PRIVATE-CREDENTIAL',locator:'s3://PRIVATE-ARTIFACT'}),...overrides});
  const basis=CredentialLifecycleBasis.bind({snapshotReference:'basis:recurrence:v1',artifact,artifactVersion:V,credentialDefinition:CredentialDefinitionReference.create(CredentialDefinitionId.from(uuid(13)),V),aggregateId:AggregateId.from(uuid(14)),aggregateType:AggregateType.from('CREDENTIAL'),tenant:TENANT,organization:ORG,purpose:PURPOSE,jurisdiction:CZ,recordedAt:T0,sources:[src],ruleVersionRefs:[V]});
  return {src,evidence,artifact,basis};
}
type Fixture=ReturnType<typeof fixture>;
function rule(f:Fixture,overrides:Partial<RecurringObligationRuleInput>={}) {return RecurringObligationRule.create({id:'rule:recurrence',version:V,credentialDefinition:f.basis.credentialDefinition,jurisdiction:CZ,validFrom:day('2025-01-01'),validTo:null,knownAt:T0,source:f.src,sourceSnapshotReference:'snapshot:rule:v1',approvedAt:T0,approvedBy:ADMIN,approvalReference:'approval:recurrence:v1',conditions:[],kind:'PERIODIC_CHECK',cadence:'FIXED_ANCHOR',interval:{amount:1,unit:'MONTHS',monthEnd:'CLAMP'},windowDaysBeforeDue:10,graceDaysAfterDue:5,requiredEvidenceClaims:[CLAIM],...overrides});}
function obligation(f=fixture(),overrides:Partial<RecurringObligationInput>={}) {return RecurringObligation.bind({id:'obligation:1',version:V,basis:f.basis,rule:rule(f),anchor:{kind:'ISSUED_ON'},recordedAt:T0,...overrides});}
function calendar(s='2025-04-15'){return LifecycleCalendarContext.create({evaluatedAt:at(`${s}T12:00:00Z`),evaluatedOn:day(s),utcOffsetMinutes:60,calendarReference:'calendar:recurrence:v1'});}
function context(overrides:Partial<Parameters<typeof ApplicationExecutionContext.create>[0]>={}){return ApplicationExecutionContext.create({operation:ApplicationOperationReference.from(RECURRING_OBLIGATION_OPERATION),actor:ACTOR,subject:SUBJECT,tenantScope:TENANT,organizationScope:ORG,purpose:PURPOSE,correlationId:CORR,requestedAt:REQUEST,contractVersion:V,accessDecision:ACCESS,...overrides});}
function reader(overrides:Partial<Parameters<typeof TenantContext.create>[0]>={}){return TenantContext.create({tenant:TENANT,organization:ORG,purpose:PURPOSE,actor:ACTOR,correlationId:CORR,...overrides});}
function access(overrides:Partial<Parameters<typeof TenantAccessDecision.create>[0]>={}){return TenantAccessDecision.create({reference:ACCESS,tenant:TENANT,purpose:PURPOSE,disposition:AccessDisposition.ALLOW,allowedFields:[RECURRING_OBLIGATION_FIELD],decidedBy:ADMIN,auditReference:AuditReference.from('audit:recurrence'),...overrides});}
function record(o:RecurringObligation,overrides:Partial<ObligationCompletionRecordInput>={}){return ObligationCompletionRecord.create({id:'completion:1',obligation:o,sequence:1,completedOn:day('2025-02-28'),recorded:calendar('2025-03-01'),disposition:'ACCEPTED',evidenceSnapshot:o.basis.artifact.evidenceSnapshot,coveredClaims:[CLAIM],source:o.rule.source,reviewedBy:ADMIN,reviewReference:'review:completion:1',...overrides});}
function query(o=obligation(),overrides:Partial<RecurringObligationProjectionInput>={}):RecurringObligationProjectionInput{return {reference:'projection:recurrence:1',context:context(),authorizedContext:reader(),boundary:TenantBoundary.create([TENANT]),accessDecision:access(),obligation:o,jurisdiction:CZ,calendar:calendar(),asKnownAt:at('2025-04-15T12:00:00Z'),horizonOn:day('2025-05-31'),maxOccurrences:20,records:[],...overrides};}
const project=(o=obligation(),overrides:Partial<RecurringObligationProjectionInput>={})=>RecurringObligationProjection.project(query(o,overrides)).toJSON();
const has=(v:ReturnType<typeof project>,code:string)=>v.reasonCodes.includes(code);
const due=(v:ReturnType<typeof project>)=>v.occurrences.map(x=>x.dueOn);
function completionEvidence(o:RecurringObligation,verificationState=VERIFIED,src=o.rule.source){return EvidenceSnapshot.capture([EvidenceReference.original({id:EvidenceId.from(uuid(90)),kind:EvidenceKind.DOCUMENT,contentReference:'s3://PRIVATE-COMPLETION',acquiredAt:T0,acquiredBy:ACTOR,source:src,verificationState,contentHash:ContentHash.sha256('c'.repeat(64))})],T0);}

test('M06S03-01 four kinds preserve exact source and version',()=>{const f=fixture();for(const kind of ['EXAM','MEDICAL_CHECK','CONTINUING_EDUCATION','PERIODIC_CHECK'] as const){const r=rule(f,{kind});assert.equal(r.kind,kind);assert.equal(r.credentialDefinition,f.basis.credentialDefinition);assert.equal(r.version,V);assert.equal(r.source,f.src);}});
test('M06S03-02 unknown kind rejected',()=>{assert.throws(()=>rule(fixture(),{kind:'OTHER' as never}));});
test('M06S03-03 ungoverned version or target rejected',()=>{assert.throws(()=>rule(fixture(),{version:'v1' as never}));assert.throws(()=>rule(fixture(),{credentialDefinition:{} as never}));});
test('M06S03-04 invalid interval quantities rejected',()=>{for(const amount of [0,-1,1.5,Infinity,12001])assert.throws(()=>rule(fixture(),{interval:{amount,unit:'MONTHS',monthEnd:'CLAMP'}}));});
test('M06S03-05 invalid units conventions and fields rejected',()=>{const f=fixture();for(const interval of [{amount:1,unit:'WEEKS',monthEnd:'CLAMP'},{amount:1,unit:'MONTHS',monthEnd:'GUESS'},{amount:1,unit:'MONTHS',monthEnd:'CLAMP',extra:true}])assert.throws(()=>rule(f,{interval:interval as never}));});
test('M06S03-06 window and grace bounds enforced',()=>{for(const n of [-1,0.5,365251]){assert.throws(()=>rule(fixture(),{windowDaysBeforeDue:n}));assert.throws(()=>rule(fixture(),{graceDaysAfterDue:n}));}});
test('M06S03-07 conditions dense unique bounded and frozen',()=>{const f=fixture(),conditions=['condition:a'],r=rule(f,{conditions});conditions.push('condition:b');assert.deepEqual(r.conditions,['condition:a']);assert(Object.isFrozen(r.conditions));for(const a of [['x','x'],new Array<string>(2),Array.from({length:1001},(_,i)=>`c:${i}`)])assert.throws(()=>rule(f,{conditions:a}));});
test('M06S03-08 source and approval knowledge checks',()=>{const f=fixture();assert.throws(()=>rule(f,{source:source({retrievedAt:at('2025-02-01T00:00:00Z')})}));assert.throws(()=>rule(f,{approvedAt:at('2025-02-01T00:00:00Z')}));});
test('M06S03-09 rule dates must be governed and ordered',()=>{assert.throws(()=>rule(fixture(),{validTo:day('2024-12-31')}));assert.throws(()=>rule(fixture(),{validFrom:'2025-01-01' as never}));});
test('M06S03-10 evidence claims required dense unique controlled',()=>{for(const requiredEvidenceClaims of [[],['x','x'],['https://raw.invalid'],new Array<string>(2)])assert.throws(()=>rule(fixture(),{requiredEvidenceClaims}));});
test('M06S03-11 rule metadata preserves approval without locator',()=>{const r=rule(fixture()),v=r.toJSON();assert.equal(v.approvalReference,'approval:recurrence:v1');assert.equal(v.source.id,r.source.id.toString());assert(!JSON.stringify(v).includes('PRIVATE'));assert(Object.isFrozen(r));});
test('M06S03-12 absent issuance anchor is explicit',()=>{const o=obligation(fixture({issuedOn:null}));assert.equal(o.anchorOn,null);});
test('M06S03-13 issuance anchor reuses artifact date',()=>{const f=fixture(),o=obligation(f);assert.equal(o.anchorOn,f.artifact.issuedOn);});
test('M06S03-14 effectivity anchor differs from issuance',()=>{const f=fixture(),o=obligation(f,{anchor:{kind:'EFFECTIVE_FROM'}});assert.equal(o.anchorOn,f.artifact.effectiveFrom);assert.notEqual(o.anchorOn,f.artifact.issuedOn);});
test('M06S03-15 explicit anchor requires provenance',()=>{const f=fixture();assert.throws(()=>obligation(f,{anchor:{kind:'EXPLICIT_DATE',on:day('2025-01-31'),reference:''}}));assert.equal(obligation(f,{anchor:{kind:'EXPLICIT_DATE',on:day('2025-01-30'),reference:'evidence:anchor'}}).anchorOn!.toString(),'2025-01-30');});
test('M06S03-16 snapshot knowledge follows basis and rule',()=>{const f=fixture();assert.throws(()=>obligation(f,{recordedAt:at('2024-12-31T00:00:00Z')}));assert.throws(()=>obligation(f,{rule:rule(f,{knownAt:at('2025-02-01T00:00:00Z')})}));});
test('M06S03-17 exact rule target version required',()=>{const f=fixture();for(const target of [CredentialDefinitionReference.create(CredentialDefinitionId.from(uuid(999)),V),CredentialDefinitionReference.create(f.basis.credentialDefinition.id,VersionId.from('v2'))])assert.throws(()=>obligation(f,{rule:rule(f,{credentialDefinition:target})}));});
test('M06S03-18 exact jurisdiction required',()=>{const f=fixture();assert.throws(()=>obligation(f,{rule:rule(f,{jurisdiction:OTHER})}));});
test('M06S03-19 cadence and anchor schema controlled',()=>{assert.throws(()=>rule(fixture(),{cadence:'AUTO' as never}));assert.throws(()=>obligation(fixture(),{anchor:{kind:'ISSUED_ON',extra:true} as never}));});
test('M06S03-20 obligation immutable separate version',()=>{const f=fixture(),o=obligation(f);assert(Object.isFrozen(o));assert.equal(Reflect.set(o,'version',VersionId.from('v2')),false);assert.equal(o.basis,f.basis);assert.throws(()=>obligation(f,{id:'unsafe value'}));});
test('M06S03-21 exact scoped evaluation succeeds',()=>{const r=project();assert.equal(r.outcome,'EVALUATED');assert.equal(r.occurrences.length,4);});
test('M06S03-22 explicit denial precedes bad sensitive data',()=>{assert.throws(()=>project(undefined as never,{accessDecision:access({disposition:AccessDisposition.DENY}),obligation:{} as never}),TenantAccessDeniedError);});
test('M06S03-23 cross tenant denied',()=>{assert.throws(()=>project(obligation(),{context:context({tenantScope:TenantScopeReference.from('tenant:other')})}),TenantAccessDeniedError);});
test('M06S03-24 cross organization denied',()=>{assert.throws(()=>project(obligation(),{context:context({organizationScope:OrganizationScopeReference.from('org:other')})}),TenantAccessDeniedError);});
test('M06S03-25 wrong subject identity and kind denied',()=>{for(const subject of [SubjectReference.create(SubjectId.from(uuid(999)),SubjectKind.PERSON),SubjectReference.create(SUBJECT.id,SubjectKind.ORGANIZATION)])assert.throws(()=>project(obligation(),{context:context({subject})}),TenantAccessDeniedError);});
test('M06S03-26 wrong purpose denied',()=>{assert.throws(()=>project(obligation(),{context:context({purpose:PurposeReference.from('purpose:other')})}),TenantAccessDeniedError);});
test('M06S03-27 actor and kind mismatches denied',()=>{for(const actor of [ADMIN,ActorReference.create(ACTOR.id,ActorKind.SYSTEM_PROCESS)])assert.throws(()=>project(obligation(),{authorizedContext:reader({actor})}),TenantAccessDeniedError);});
test('M06S03-28 correlation mismatch denied',()=>{assert.throws(()=>project(obligation(),{authorizedContext:reader({correlationId:CorrelationId.from(uuid(999))})}),TenantAccessDeniedError);});
test('M06S03-29 operation field and access reference required',()=>{const o=obligation();assert.throws(()=>project(o,{context:context({operation:ApplicationOperationReference.from('other.operation')})}));assert.throws(()=>project(o,{accessDecision:access({allowedFields:[]})}));assert.throws(()=>project(o,{context:context({accessDecision:AccessDecisionReference.from('access:other')})}));});
test('M06S03-30 unknown tenant and structural reader rejected',()=>{assert.throws(()=>project(obligation(),{boundary:TenantBoundary.create([TenantScopeReference.from('tenant:other')])}),TenantAccessDeniedError);assert.throws(()=>project(obligation(),{authorizedContext:{} as never}),TenantAccessDeniedError);});
test('M06S03-31 future evaluation and knowledge rejected',()=>{const o=obligation();assert.throws(()=>project(o,{context:context({requestedAt:T0})}));assert.throws(()=>project(o,{asKnownAt:at('2029-01-01T00:00:00Z')}));});
test('M06S03-32 future known obligation rejected',()=>{const f=fixture(),o=obligation(f,{recordedAt:at('2026-01-01T00:00:00Z')});assert.throws(()=>project(o));});
test('M06S03-33 horizon before today rejected',()=>{assert.throws(()=>project(obligation(),{horizonOn:day('2025-04-14')}));});
test('M06S03-34 invalid output budget rejected',()=>{for(const maxOccurrences of [0,-1,1.5,1001,Infinity])assert.throws(()=>project(obligation(),{maxOccurrences}));});
test('M06S03-35 completion collection exact and bounded',()=>{const o=obligation();for(const records of [new Array<ObligationCompletionRecord>(1),[{} as never],[record(obligation())],Array(10001).fill(record(o))])assert.throws(()=>project(o,{records}));});
test('M06S03-36 record identity and sequence controlled',()=>{const o=obligation();for(const sequence of [0,-1,0.5,10001])assert.throws(()=>record(o,{sequence}));assert.throws(()=>record(o,{id:'raw value'}));});
test('M06S03-37 evidence type and capture time checked',()=>{const f=fixture(),o=obligation(f);assert.throws(()=>record(o,{evidenceSnapshot:{} as never}));assert.throws(()=>record(o,{evidenceSnapshot:EvidenceSnapshot.capture([f.evidence],at('2025-04-01T00:00:00Z'))}));});
test('M06S03-38 source retrieval precedes recording',()=>{const o=obligation();assert.throws(()=>record(o,{source:source({retrievedAt:at('2025-04-01T00:00:00Z')})}));});
test('M06S03-39 accepted record requires completed date',()=>{assert.throws(()=>record(obligation(),{completedOn:null}));});
test('M06S03-40 completion cannot postdate recording',()=>{assert.throws(()=>record(obligation(),{completedOn:day('2025-03-02')}));});
test('M06S03-41 disposition and reviewer schema controlled',()=>{assert.throws(()=>record(obligation(),{disposition:'true' as never}));assert.throws(()=>record(obligation(),{reviewedBy:{} as never}));assert.throws(()=>record(obligation(),{coveredClaims:[CLAIM,CLAIM]}));});
test('M06S03-42 completion safe immutable metadata',()=>{const o=obligation(),r=record(o);assert(Object.isFrozen(r));assert(!JSON.stringify(r).includes('PRIVATE'));assert.equal(r.toJSON().evidence[0]!.id,o.basis.artifact.evidenceSnapshot.entries[0]!.evidenceId.toString());});
test('M06S03-43 fixed weekly calendar cycles',()=>{const f=fixture(),o=obligation(f,{rule:rule(f,{interval:{amount:7,unit:'DAYS',monthEnd:'REJECT'}})});const r=project(o,{calendar:calendar('2025-02-14'),horizonOn:day('2025-02-21')});assert.deepEqual(due(r),['2025-02-07','2025-02-14','2025-02-21']);});
test('M06S03-44 monthly original anchor prevents drift',()=>{assert.deepEqual(due(project()),['2025-02-28','2025-03-31','2025-04-30','2025-05-31']);});
test('M06S03-45 rejected month end returns no partial list',()=>{const f=fixture(),r=project(obligation(f,{rule:rule(f,{interval:{amount:1,unit:'MONTHS',monthEnd:'REJECT'}})}));assert.equal(r.outcome,'REVIEW_REQUIRED');assert(has(r,'CALENDAR_ADJUSTMENT_REQUIRED'));assert.deepEqual(r.occurrences,[]);});
test('M06S03-46 leap anniversary recovers original anchor',()=>{const f=fixture({issuedOn:day('2024-02-29'),effectiveFrom:day('2024-02-29')}),o=obligation(f,{rule:rule(f,{validFrom:day('2024-01-01'),interval:{amount:1,unit:'YEARS',monthEnd:'CLAMP'},source:source({effectiveFrom:day('2024-01-01')})})});const r=project(o,{horizonOn:day('2028-02-29')});assert.deepEqual(due(r),['2025-02-28','2026-02-28','2027-02-28','2028-02-29']);});
test('M06S03-47 calendar states independent from evidence',()=>{const o=obligation();for(const [today,state] of [['2025-02-17','UPCOMING'],['2025-02-18','ACTION_WINDOW'],['2025-02-28','DUE_TODAY'],['2025-03-01','OVERDUE_WITHIN_GRACE'],['2025-03-06','OVERDUE']]){const r=project(o,{calendar:calendar(today!),horizonOn:day('2025-05-31')});assert.equal(r.occurrences[0]!.calendarState,state);assert.equal(r.occurrences[0]!.completionState,'NONE_RECORDED');}});
test('M06S03-48 inclusive horizon boundary',()=>{const o=obligation();assert.equal(project(o,{calendar:calendar('2025-02-01'),horizonOn:day('2025-02-27')}).occurrences.length,0);assert.equal(project(o,{calendar:calendar('2025-02-01'),horizonOn:day('2025-02-28')}).occurrences.length,1);});
test('M06S03-49 rule end clips cycle generation only',()=>{const f=fixture(),r=project(obligation(f,{rule:rule(f,{validTo:day('2025-03-31')})}));assert.deepEqual(due(r),['2025-02-28','2025-03-31']);assert.equal(r.eventsEmitted,0);});
test('M06S03-50 anchor outside rule effectivity requires review',()=>{const f=fixture(),r=project(obligation(f,{rule:rule(f,{validFrom:day('2025-02-01')})}));assert(has(r,'ANCHOR_OUTSIDE_RULE_EFFECTIVITY'));assert.deepEqual(r.occurrences,[]);});
test('M06S03-51 unverified rule source blocks projection',()=>{const f=fixture(),r=project(obligation(f,{rule:rule(f,{source:source({verificationState:UNVERIFIED})})}));assert(has(r,'RULE_SOURCE_UNVERIFIED'));});
test('M06S03-52 source jurisdiction mismatch requires review',()=>{const f=fixture(),r=project(obligation(f,{rule:rule(f,{source:source({jurisdiction:OTHER})})}));assert(has(r,'RULE_SOURCE_JURISDICTION_MISMATCH'));});
test('M06S03-53 source effectivity covers anchor',()=>{const f=fixture(),r=project(obligation(f,{rule:rule(f,{source:source({effectiveFrom:day('2025-02-01')})})}));assert(has(r,'RULE_SOURCE_OUTSIDE_EFFECTIVITY'));});
test('M06S03-54 unresolved conditions stay review-required',()=>{const f=fixture(),r=project(obligation(f,{rule:rule(f,{conditions:['condition:unresolved']})}));assert(has(r,'RULE_CONDITIONS_UNRESOLVED'));assert.equal(r.outcome,'REVIEW_REQUIRED');});
test('M06S03-55 unverified artifact remains unverified',()=>{const r=project(obligation(fixture({verificationState:UNVERIFIED})));assert(has(r,'ARTIFACT_FACTS_UNVERIFIED'));assert.deepEqual(r.occurrences,[]);});
test('M06S03-56 missing anchor remains unknown',()=>{const r=project(obligation(fixture({issuedOn:null})));assert.equal(r.outcome,'INDETERMINATE');assert(has(r,'ANCHOR_MISSING'));assert.deepEqual(r.occurrences,[]);});
test('M06S03-57 budget overflow has no partial schedule',()=>{const r=project(obligation(),{maxOccurrences:1});assert.equal(r.outcome,'REVIEW_REQUIRED');assert(has(r,'OCCURRENCE_BUDGET_EXCEEDED'));assert.deepEqual(r.occurrences,[]);});
test('M06S03-58 calendar range overflow fails closed',()=>{const f=fixture({issuedOn:day('9999-12-31'),effectiveFrom:day('9999-12-31'),expiresOn:null}),r=project(obligation(f),{horizonOn:day('9999-12-31')});assert(has(r,'CALENDAR_ADJUSTMENT_REQUIRED'));assert.deepEqual(r.occurrences,[]);});
test('M06S03-59 cycle references collision-safe and versioned',()=>{const f=fixture(),o=obligation(f);assert.notEqual(o.occurrenceReference(1),o.occurrenceReference(2));assert.notEqual(o.occurrenceReference(1),obligation(f,{id:'obligation:2'}).occurrenceReference(1));assert.notEqual(o.occurrenceReference(1),obligation(f,{rule:rule(f,{version:VersionId.from('v2')})}).occurrenceReference(1));});
test('M06S03-60 new rule snapshot preserves old schedule',()=>{const f=fixture(),old=project(obligation(f)),saved=JSON.stringify(old),next=project(obligation(f,{version:VersionId.from('v2'),rule:rule(f,{version:VersionId.from('v2'),interval:{amount:2,unit:'MONTHS',monthEnd:'CLAMP'}})}));assert.deepEqual(due(next),['2025-03-31','2025-05-31']);assert.equal(JSON.stringify(old),saved);});
test('M06S03-61 missing record never becomes legal failure',()=>{const r=project();assert(r.occurrences.every(x=>x.completionState==='NONE_RECORDED'));assert.equal(r.legalComplianceDetermined,false);assert(!JSON.stringify(r).includes('SATISFIED'));});
test('M06S03-62 exact accepted completion retains provenance',()=>{const o=obligation(),r=project(o,{records:[record(o)]}),c=r.occurrences[0]!;assert.equal(c.completionState,'ACCEPTED_RECORD');assert.equal(c.completionTiming,'ON_OR_BEFORE_DUE');assert.equal(c.records[0]!.coveredClaims[0],CLAIM);assert.equal(c.records[0]!.reviewReference,'review:completion:1');});
test('M06S03-63 incomplete claim coverage requires review',()=>{const o=obligation(),r=project(o,{records:[record(o,{coveredClaims:[]})]});assert.equal(r.occurrences[0]!.completionState,'REVIEW_REQUIRED');assert(r.occurrences[0]!.reasonCodes.includes('REQUIRED_CLAIM_COVERAGE_MISSING'));});
test('M06S03-64 empty or unverified evidence cannot qualify',()=>{const o=obligation();assert.throws(()=>EvidenceSnapshot.capture([],T0));const r=project(o,{records:[record(o,{evidenceSnapshot:completionEvidence(o,UNVERIFIED)})]});assert.equal(r.occurrences[0]!.completionState,'REVIEW_REQUIRED');});
test('M06S03-65 completion source identity jurisdiction and effectivity bound',()=>{const o=obligation();for(const src of [source({id:SourceId.from(uuid(99))}),source({jurisdiction:OTHER}),source({effectiveTo:day('2025-02-01')}),source({verificationState:UNVERIFIED})]){const r=project(o,{records:[record(o,{source:src})]});assert.equal(r.occurrences[0]!.completionState,'REVIEW_REQUIRED');}});
test('M06S03-66 conflicting records no latest-writer rule',()=>{const o=obligation(),r=project(o,{records:[record(o),record(o,{id:'completion:2',disposition:'REJECTED'})]});assert.equal(r.occurrences[0]!.completionState,'REVIEW_REQUIRED');assert(r.occurrences[0]!.reasonCodes.includes('MULTIPLE_COMPLETION_RECORDS'));});
test('M06S03-67 duplicate visible record ID rejected',()=>{const o=obligation(),r=record(o);assert.throws(()=>project(o,{records:[r,r]}));});
test('M06S03-68 late fixed completion never shifts next deadline',()=>{const o=obligation(),r=project(o,{records:[record(o,{completedOn:day('2025-03-05'),recorded:calendar('2025-03-06')})]});assert.equal(r.occurrences[0]!.completionTiming,'AFTER_DUE');assert.equal(r.occurrences[1]!.dueOn,'2025-03-31');});
test('M06S03-69 rolling next cycle uses accepted completion',()=>{const f=fixture(),o=obligation(f,{rule:rule(f,{cadence:'AFTER_ACCEPTED_COMPLETION'})}),r=project(o,{records:[record(o,{completedOn:day('2025-03-05'),recorded:calendar('2025-03-06')})]});assert.deepEqual(due(r),['2025-02-28','2025-04-05']);assert.equal(r.stoppedAtSequence,2);});
test('M06S03-70 rolling stops missing first completion',()=>{const f=fixture(),o=obligation(f,{rule:rule(f,{cadence:'AFTER_ACCEPTED_COMPLETION'})}),r=project(o);assert.deepEqual(due(r),['2025-02-28']);assert.equal(r.stoppedAtSequence,1);assert(has(r,'NEXT_CYCLE_REQUIRES_ACCEPTED_COMPLETION'));});
test('M06S03-71 rolling stops unqualified records',()=>{const f=fixture(),o=obligation(f,{rule:rule(f,{cadence:'AFTER_ACCEPTED_COMPLETION'})});for(const disposition of ['REJECTED','REVIEW_REQUIRED'] as const){const r=project(o,{records:[record(o,{disposition})]});assert.equal(r.occurrences.length,1);assert.equal(r.outcome,'REVIEW_REQUIRED');}});
test('M06S03-72 early and nonprogressing completion rejected as scheduling anchor',()=>{const f=fixture(),o=obligation(f,{rule:rule(f,{cadence:'AFTER_ACCEPTED_COMPLETION'})});for(const completedOn of [day('2025-02-01'),day('2025-01-31')]){const r=project(o,{records:[record(o,{completedOn})]});assert.equal(r.occurrences[0]!.completionState,'REVIEW_REQUIRED');assert.equal(r.occurrences.length,1);}});
test('M06S03-73 future-known records absent from historical metadata',()=>{const o=obligation(),q={asKnownAt:at('2025-02-28T23:00:00Z')},without=project(o,q),withFuture=project(o,{...q,records:[record(o)]});assert.deepEqual(withFuture,without);});
test('M06S03-74 unassigned record is not applied to another cycle',()=>{const o=obligation(),r=project(o,{records:[record(o,{sequence:9})]});assert.equal(r.outcome,'REVIEW_REQUIRED');assert.deepEqual(r.unmatchedRecordIds,['completion:1']);assert(r.occurrences.every(x=>x.completionState==='NONE_RECORDED'));});
test('M06S03-75 grace and lateness do not extend artifact',()=>{const f=fixture({expiresOn:day('2025-02-28')}),o=obligation(f),before=JSON.stringify(f.artifact),r=project(o,{calendar:calendar('2025-03-01')});assert.equal(r.occurrences[0]!.calendarState,'OVERDUE_WITHIN_GRACE');assert.equal(JSON.stringify(f.artifact),before);assert.equal(r.authorizationAuthority,false);});
test('M06S03-76 credential expiry alone does not cancel schedule',()=>{const r=project(obligation(fixture({expiresOn:day('2025-02-28')})));assert.equal(r.occurrences.length,4);assert.equal(r.occurrences[3]!.dueOn,'2025-05-31');});
test('M06S03-77 deterministic reordered record inputs',()=>{const o=obligation(),a=record(o),b=record(o,{id:'completion:2',sequence:2,completedOn:day('2025-03-31'),recorded:calendar('2025-04-01')});assert.deepEqual(project(o,{records:[a,b]}),project(o,{records:[b,a]}));assert.deepEqual(project(o),project(o));});
test('M06S03-78 upstream Core S01 S02 data unchanged',()=>{const f=fixture(),o=obligation(f),before=JSON.stringify([f.basis,f.artifact,o.rule]),original=day('2025-01-31');project(o,{records:[record(o)]});assert.equal(JSON.stringify([f.basis,f.artifact,o.rule]),before);assert.equal(shiftLifecycleDate(original,1,'MONTHS','CLAMP').toString(),'2025-02-28');assert.equal(original.toString(),'2025-01-31');});
test('M06S03-79 deep immutable metadata-only output',()=>{const o=obligation(),r=project(o,{records:[record(o)]});assert(Object.isFrozen(r));assert(Object.isFrozen(r.occurrences));assert(Object.isFrozen(r.occurrences[0]!.records[0]!.evidence));assert.throws(()=>(r.occurrences as unknown[]).push({}));for(const bad of ['PRIVATE','s3://','https://'])assert(!JSON.stringify(r).includes(bad));});
test('M06S03-80 no side effects or legal conclusion',()=>{const r=project();assert.equal(r.eventsEmitted,0);assert.equal(r.notificationScheduled,false);assert.equal(r.authorizationAuthority,false);assert.equal(r.legalComplianceDetermined,false);assert.equal(r.historyMutated,false);assert.equal(r.coverage,'REQUESTED_HORIZON_AND_PROVIDED_RECORDS');});
