import test from 'node:test';
import assert from 'node:assert/strict';
import {expectedRecord,validateExecution,NEW_FILES,CHANGED_FILES,validateDelta,dispatchPatch,validateDispatch,validateS02Config,validateS02Index} from '../scripts/ci/m06-s02-scope.mjs';
const valid=()=>expectedRecord('https://github.com/robertdominik618/calpq-os/pull/140#issuecomment-999999');
const delta=()=>[...NEW_FILES.map(path=>({path,status:'A',mode:'100644'})),...CHANGED_FILES.map(path=>({path,status:'M',mode:'100644'}))];
const original="export const invariant=true;\nif (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();\n";
const index=Array.from({length:72},(_,i)=>`| M06S02-${String(i+1).padStart(2,'0')} | scenario |`).join('\n');
test('M06S02G-01 exact execution record accepted as consistency data',()=>{validateExecution(valid());});
test('M06S02G-02 changed approval rejected',()=>{assert.throws(()=>validateExecution({...valid(),approval_text:'approved'}));});
test('M06S02G-03 changed predecessor rejected',()=>{assert.throws(()=>validateExecution({...valid(),predecessor_merge:'a'.repeat(40)}));});
test('M06S02G-04 missing and extra fields rejected',()=>{const v=valid();delete v.state;assert.throws(()=>validateExecution(v));assert.throws(()=>validateExecution({...valid(),skip:true}));});
test('M06S02G-05 expanded authorization rejected',()=>{assert.throws(()=>validateExecution({...valid(),authorized_slices:['S02','S03']}));assert.throws(()=>validateExecution({...valid(),production_release_authorized:true}));});
test('M06S02G-06 progress inflation rejected',()=>{assert.throws(()=>validateExecution({...valid(),m06_accepted_slices:2}));assert.throws(()=>validateExecution({...valid(),v1_completed_plan_units:62}));});
test('M06S02G-07 missing or foreign evidence rejected',()=>{for(const post_merge_evidence_reference of [null,'approved','https://github.com/elsewhere/repo/pull/140#issuecomment-1',valid().owner_approval_reference])assert.throws(()=>validateExecution({...valid(),post_merge_evidence_reference}));});
test('M06S02G-08 exact current scope accepted',()=>{validateDelta(delta());});
test('M06S02G-09 unknown source or historical path rejected',()=>{assert.throws(()=>validateDelta([...delta(),{path:'packages/core/src/extra.ts',mode:'100644',status:'A'}]));});
test('M06S02G-10 deletion rename and mode rejected',()=>{for(const extra of [{status:'D'},{status:'R'},{mode:'100755'},{mode:'120000'}]){const d=delta();Object.assign(d[0],extra);assert.throws(()=>validateDelta(d));}});
test('M06S02G-11 duplicate or incomplete delta rejected',()=>{assert.throws(()=>validateDelta([...delta(),delta()[0]]));assert.throws(()=>validateDelta(delta().slice(1)));});
test('M06S02G-12 exact successor dispatch accepted',()=>{validateDispatch(original,dispatchPatch(original));});
test('M06S02G-13 legacy helper edits rejected',()=>{assert.throws(()=>validateDispatch(original,dispatchPatch(original).replace('invariant=true','invariant=false')));assert.throws(()=>dispatchPatch('missing'));});
test('M06S02G-14 additive configs accepted',()=>{validateS02Config('packages/application/package.json',{scripts:{old:'old'}},{scripts:{old:'old','test:m06s02':'node --test test/m06-s02-expiry-renewal-policy.test.ts'}});validateS02Config('packages/application/tsconfig.json',{include:['old']},{include:['old','test/m06-s02-types.compile.ts']});});
test('M06S02G-15 predecessor config mutation rejected',()=>{assert.throws(()=>validateS02Config('packages/application/package.json',{scripts:{old:'old'}},{scripts:{old:'changed','test:m06s02':'node --test test/m06-s02-expiry-renewal-policy.test.ts'}}));});
test('M06S02G-16 malformed scenario index rejected',()=>{validateS02Index(index);assert.throws(()=>validateS02Index(index.replace('M06S02-02','M06S02-01')));assert.throws(()=>validateS02Index(index.split('\n').slice(1).join('\n')));});
