import test from 'node:test';
import assert from 'node:assert/strict';
import {expectedRecord,validateExecution,validateDelta,dispatchPatch,validateDispatch,validateConfig,validateIndex,validateBarrel,NEW_FILES,CHANGED_FILES,INDEX_APPEND} from '../scripts/ci/m06-s03-scope.mjs';
const delta=()=>[...NEW_FILES.map(path=>({path,status:'A',mode:'100644'})),...CHANGED_FILES.map(path=>({path,status:'M',mode:'100644'}))];
const original="import {readFileSync} from 'node:fs';\nfunction main(){return 'original-guard';}\nif(process.argv[1] && resolve(process.argv[1])===fileURLToPath(import.meta.url))main();\n";
const index=()=>Array.from({length:80},(_,i)=>`| M06S03-${String(i+1).padStart(2,'0')} | scenario |`).join('\n');
test('M06S03G-01 exact recorded authorization passes consistency checks',()=>validateExecution(expectedRecord()));
test('M06S03G-02 altered owner approval rejected',()=>assert.throws(()=>validateExecution({...expectedRecord(),approval_text:'approved'})));
test('M06S03G-03 altered predecessor identity rejected',()=>assert.throws(()=>validateExecution({...expectedRecord(),predecessor_merge:'0'.repeat(40)})));
test('M06S03G-04 missing and extra record keys rejected',()=>{const v=expectedRecord();delete v.issue;assert.throws(()=>validateExecution(v));assert.throws(()=>validateExecution({...expectedRecord(),extra:true}));});
test('M06S03G-05 expanded slice or release permission rejected',()=>{assert.throws(()=>validateExecution({...expectedRecord(),authorized_slices:['S03','S04']}));assert.throws(()=>validateExecution({...expectedRecord(),production_release_authorized:true}));});
test('M06S03G-06 accepted progress inflation rejected',()=>assert.throws(()=>validateExecution({...expectedRecord(),m06_accepted_slices:3,v1_completed_plan_units:63})));
test('M06S03G-07 invented post-merge evidence rejected',()=>assert.throws(()=>validateExecution({...expectedRecord(),post_merge_evidence_reference:expectedRecord().owner_approval_reference})));
test('M06S03G-08 exact fifteen-file candidate scope passes',()=>{assert.equal(delta().length,15);validateDelta(delta());});
test('M06S03G-09 unknown Core and prior runtime paths rejected',()=>{for(const path of ['packages/core/src/new.ts','packages/application/test/m06-s02-expiry-renewal-policy.test.ts'])assert.throws(()=>validateDelta([...delta(),{path,status:'M',mode:'100644'}]));});
test('M06S03G-10 deletion rename and executable mode rejected',()=>{for(const change of [{status:'D'},{status:'R100'},{mode:'100755'}])assert.throws(()=>validateDelta(delta().map((v,i)=>i? v:{...v,...change})));});
test('M06S03G-11 incomplete and duplicate scope rejected',()=>{assert.throws(()=>validateDelta(delta().slice(1)));assert.throws(()=>validateDelta([...delta(),delta()[0]]));});
test('M06S03G-12 exact successor dispatch passes',()=>validateDispatch(original,dispatchPatch(original)));
test('M06S03G-13 changed old validator and ambiguous patch rejected',()=>{assert.throws(()=>validateDispatch(original,dispatchPatch(original).replace('original-guard','bypass')));assert.throws(()=>dispatchPatch(original+original));});
test('M06S03G-14 only exact additive package and compile entries pass',()=>{validateConfig('packages/application/package.json',{scripts:{old:'test'}},{scripts:{old:'test','test:m06s03':'node --test test/m06-s03-recurring-obligation.test.ts'}});validateConfig('packages/application/tsconfig.json',{include:['src/**/*.ts']},{include:['src/**/*.ts','test/m06-s03-types.compile.ts']});assert.throws(()=>validateConfig('other',{},{}));});
test('M06S03G-15 altered predecessor configuration or exports rejected',()=>{assert.throws(()=>validateConfig('packages/application/package.json',{scripts:{old:'test'}},{scripts:{old:'skip','test:m06s03':'node --test test/m06-s03-recurring-obligation.test.ts'}}));validateBarrel('original\n','original\n'+INDEX_APPEND);assert.throws(()=>validateBarrel('original\n',INDEX_APPEND));});
test('M06S03G-16 missing duplicate or reordered mandatory scenarios rejected',()=>{validateIndex(index());assert.throws(()=>validateIndex(index().replace('M06S03-02','M06S03-01')));assert.throws(()=>validateIndex(index().split('\n').reverse().join('\n')));assert.throws(()=>validateIndex(index().split('\n').slice(1).join('\n')));});
