import test from 'node:test';
import assert from 'node:assert/strict';
import {expectedRecord,validateRecord,validateChanges,adaptS10,validateS10Patch,validateMatrix,validatePackage,addedPaths,S10} from '../scripts/ci/m06-admission-preparation.mjs';
const record = () => structuredClone(expectedRecord());
const original = '#!/usr/bin/env bash\nwhile IFS= read -r path; do\n  echo "$path"\ndone < <(git diff --name-only "$base"...HEAD)\nnode --test existing.test.mjs\n';
const matrix = Array.from({length:24},(_,i)=>`| M06PREP-${String(i+1).padStart(2,'0')} | requirement |`).join('\n');
const pkg = 'PLANNING COMPLETE / IMPLEMENTATION BLOCKED\n'+Array.from({length:10},(_,i)=>`${i+1}. Slice`).join('\n');
test('M06PREPTEST-01 exact preparation manifest accepted',()=>validateRecord(record()));
test('M06PREPTEST-02 implementation permission rejected',()=>{const r=record();r.implementation_authorized=true;assert.throws(()=>validateRecord(r));});
test('M06PREPTEST-03 false-like strings rejected',()=>{const r=record();r.implementation_authorized='false';assert.throws(()=>validateRecord(r));});
test('M06PREPTEST-04 formal admission state rejected',()=>{const r=record();r.state='ADMITTED_FOR_IMPLEMENTATION';assert.throws(()=>validateRecord(r));});
test('M06PREPTEST-05 invented approval rejected',()=>{const r=record();r.admission_approval={approved:true};assert.throws(()=>validateRecord(r));});
test('M06PREPTEST-06 active execution entry rejected',()=>{const r=record();r.authorized_execution_entry=r.proposed_execution_entry;assert.throws(()=>validateRecord(r));});
test('M06PREPTEST-07 merge or release permission rejected',()=>{for(const key of ['preparation_pr_merge_authorized','production_release_authorized']){const r=record();r[key]=true;assert.throws(()=>validateRecord(r));}});
test('M06PREPTEST-08 changed anchor or acceptance reference rejected',()=>{for(const key of ['m05_accepted_merge','m05_accepted_tree','m04_reviewed_merge','m05_acceptance_comment']){const r=record();r[key]='changed';assert.throws(()=>validateRecord(r));}});
test('M06PREPTEST-09 inflated progress rejected',()=>{const r=record();r.m06_completed_slices=1;assert.throws(()=>validateRecord(r));});
test('M06PREPTEST-10 unknown or missing manifest keys rejected',()=>{const r=record();r.override=true;assert.throws(()=>validateRecord(r));const s=record();delete s.activation_condition;assert.throws(()=>validateRecord(s));assert.throws(()=>validateRecord(null));});
test('M06PREPTEST-11 missing next transition rejected',()=>{const r=record();r.next_transition_requirements.pop();assert.throws(()=>validateRecord(r));});
test('M06PREPTEST-12 exact additive scope accepted',()=>validateChanges([...addedPaths.map(path=>({path,status:'A',mode:'100644'})),{path:S10,status:'M',mode:'100644'}]));
test('M06PREPTEST-13 production and unrelated files rejected',()=>{for(const path of ['packages/application/src/lifecycle/new.ts','packages/core/src/new.ts','README.md','docs/planning/m06-admission-decision.json'])assert.throws(()=>validateChanges([{path,status:'A',mode:'100644'}]));});
test('M06PREPTEST-14 deletion rename and copy rejected',()=>{for(const status of ['D','R100','C100','M'])assert.throws(()=>validateChanges([{path:addedPaths[0],status,mode:'100644'}]));});
test('M06PREPTEST-15 executable symlink or duplicate entries rejected',()=>{for(const mode of ['100755','120000','160000'])assert.throws(()=>validateChanges([{path:addedPaths[0],status:'A',mode}]));assert.throws(()=>validateChanges(Array(2).fill({path:addedPaths[0],status:'A',mode:'100644'})));});
test('M06PREPTEST-16 exact S10 adaptation preserves runtime suffix',()=>{const adapted=adaptS10(original);validateS10Patch(original,adapted);assert(adapted.endsWith('node --test existing.test.mjs\n'));});
test('M06PREPTEST-17 removed runtime or extra bypass rejected',()=>{const adapted=adaptS10(original);assert.throws(()=>validateS10Patch(original,adapted.replace('node --test existing.test.mjs','true')));assert.throws(()=>validateS10Patch(original,'exit 0\n'+adapted));});
test('M06PREPTEST-18 ambiguous original scope markers rejected',()=>{assert.throws(()=>adaptS10('no loop'));assert.throws(()=>adaptS10(original+original));});
test('M06PREPTEST-19 missing duplicate or reordered matrix rejected',()=>{validateMatrix(matrix);assert.throws(()=>validateMatrix(matrix.split('\n').slice(1).join('\n')));assert.throws(()=>validateMatrix(matrix+'\n| M06PREP-24 | duplicate |'));assert.throws(()=>validateMatrix(matrix.split('\n').reverse().join('\n')));});
test('M06PREPTEST-20 scope count and blocked package enforced',()=>{validatePackage(pkg);assert.throws(()=>validatePackage(pkg.replace('IMPLEMENTATION BLOCKED','ADMITTED_FOR_IMPLEMENTATION')));assert.throws(()=>validatePackage(pkg+'\n11. Extra scope'));});
