import test from 'node:test';
import assert from 'node:assert/strict';
import {PREP,PREP_HEAD,M06,M04,ENTRY,ADDED,MODIFIED,S01_ADDED,S01_MODIFIED,S01_EXECUTABLE_MODIFIED,expectedDecision,validateDecision,adaptFile,validatePatch,validateScope,validateActivation,modeFor,validateIndex} from '../scripts/ci/m07-admission.mjs';
const decision=(patch={})=>({...expectedDecision(),...patch});
const files=()=>[...ADDED.map(path=>({path,status:'A',mode:'100644'})),...MODIFIED.map(path=>({path,status:'M',mode:'100644'}))];
const activation=(patch={})=>({schema_version:1,milestone:'M07',slice:'S01',state:'ACTIVE_AFTER_VERIFIED_ADMISSION',decision_id:'CALPQ-M07-ADM-DEC-0001',authorized_execution_entry:ENTRY,admission_pr:163,admission_head:'a'.repeat(40),admission_merge:'b'.repeat(40),admission_tree:'c'.repeat(40),owner_merge_approval_reference:'https://github.com/robertdominik618/calpq-os/pull/163#issuecomment-1234',post_merge_evidence_reference:'https://github.com/robertdominik618/calpq-os/pull/163#issuecomment-1235',production_release_authorized:false,legal_interpretation_authorized:false,...patch});
const matrix=()=>Array.from({length:36},(_,i)=>`| M07ADM-${String(i+1).padStart(2,'0')} | requirement |`).join('\n');
const loop=`for m in 07 08; do
  grep -q 'IMPLEMENTATION BLOCKED' "docs/planning/M\${m}_EXECUTION_PACKAGE.md" \\\n    || fail "M\${m} must remain implementation-blocked"
done`;
const oldGuard=(kind='m05')=>`prior_checks
${loop}
${kind==='m05'?'':"if grep -R -nE 'ADMITTED / IMPLEMENTATION AUTHORIZED|ADMITTED_FOR_IMPLEMENTATION' \\\n  docs/planning/M0{7,8}_EXECUTION_PACKAGE.md >/dev/null; then\n  fail 'M06-M08 admission leaked into earlier transition'\nfi\n"}runtime_call
printf 'X / M07-M08 BLOCKED\\n'`;

test('M07ADM-01 exact decision accepted',()=>validateDecision(expectedDecision()));
test('M07ADM-02 wrong approval rejected',()=>{for(const p of [{approval_text:'go'},{approved_by:'other'},{approved_at:'2026-09-20T00:00:00Z'}])assert.throws(()=>validateDecision(decision(p)));});
test('M07ADM-03 unknown or missing fields rejected',()=>{const v=expectedDecision();delete v.approval_text;assert.throws(()=>validateDecision(v));assert.throws(()=>validateDecision(decision({override:true})));});
test('M07ADM-04 wrong milestone/issue identities rejected',()=>{for(const p of [{milestone:'M08'},{issue_number:162},{transition_issue_number:0},{decision_id:'other'}])assert.throws(()=>validateDecision(decision(p)));});
test('M07ADM-05 preparation anchor drift rejected',()=>{for(const k of ['preparation_reviewed_head','preparation_reviewed_merge','preparation_tree','admitted_revision'])assert.throws(()=>validateDecision(decision({[k]:'d'.repeat(40)})));});
test('M07ADM-06 M04/M06 anchor drift rejected',()=>{for(const k of ['m04_reviewed_merge','m06_accepted_merge'])assert.throws(()=>validateDecision(decision({[k]:'d'.repeat(40)})));});
test('M07ADM-07 source governance identity drift rejected',()=>assert.throws(()=>validateDecision(decision({source_governance_id:'AI'}))));
test('M07ADM-08 wrong entry or extra slice rejected',()=>{assert.throws(()=>validateDecision(decision({authorized_execution_entry:'M07_ALL'})));assert.throws(()=>validateDecision(decision({authorized_slices:['S01','S02']})));});
test('M07ADM-09 immediate/release/legal authority rejected',()=>{for(const p of [{admission_effective_condition:'IMMEDIATE'},{production_release_authorized:true},{legal_interpretation_authorized:true},{later_slices_authorized:true}])assert.throws(()=>validateDecision(decision(p)));});
test('M07ADM-10 progress inflation rejected',()=>{for(const p of [{m07_completed_slices:1},{v1_completed_plan_units:71},{v1_total_plan_units:70}])assert.throws(()=>validateDecision(decision(p)));});
test('M07ADM-11 blocking reviews and false strings rejected',()=>{assert.throws(()=>validateDecision(decision({blocking_reviews:['x']})));assert.throws(()=>validateDecision(decision({legal_interpretation_authorized:'false'})));});
test('M07ADM-12 exact admission scope accepted',()=>{validateScope(files());assert.equal(files().length,15);});
test('M07ADM-13 product source in admission rejected',()=>{for(const path of ['packages/core/src/regulatory/x.ts','packages/application/src/x.ts','packages/adapters/src/x.ts'])assert.throws(()=>validateScope([...files(),{path,status:'A',mode:'100644'}]));});
test('M07ADM-14 missing duplicate unexpected scope rejected',()=>{assert.throws(()=>validateScope(files().slice(1)));assert.throws(()=>validateScope([...files(),files()[0]]));assert.throws(()=>validateScope([]));});
test('M07ADM-15 invalid file operations rejected',()=>{for(const patch of [{status:'D'},{status:'R100'},{status:'C100'},{mode:'100755'},{mode:'120000'}]){const v=files();v[0]={...v[0],...patch};assert.throws(()=>validateScope(v));}});
test('M07ADM-16 preparation dispatch preserves pure validator',()=>{const p='scripts/ci/m07-admission-preparation.mjs',o="import x\n  process.chdir(fileURLToPath(new URL('../../', import.meta.url)));\n  const head = git('rev-parse','HEAD').trim();\nvalidatePure();",a=adaptFile(p,o);validatePatch(p,o,a);assert(a.includes('validatePure()'));assert(a.includes("m07-admission-decision.json"));});
test('M07ADM-17 preparation runtime shell calls preserved',()=>{const p='tests/m07_admission_preparation_test.sh',o='M07 PREPARATION: 24/24 governance validator tests PASS; formal admission remains separate.\nbash tests/m04_s10_integration_evidence_test.sh\nbash tests/m06_s10_integration_evidence_test.sh\nM07 PREPARATION REGRESSION PASS / SOURCE GOVERNANCE + M04 + M06 PREREQUISITES / IMPLEMENTATION STILL BLOCKED / FULL PR MATRIX REQUIRED',a=adaptFile(p,o);for(const call of ['bash tests/m04_s10_integration_evidence_test.sh','bash tests/m06_s10_integration_evidence_test.sh'])assert(a.includes(call));});
test('M07ADM-18 M03 successor patch preserves prior checks',()=>{const p='tests/m03_admission_test.sh',o=oldGuard('m03'),a=adaptFile(p,o);assert(a.includes('prior_checks'));assert(a.includes('runtime_call'));assert(a.includes('m07-admission.mjs'));});
test('M07ADM-19 M04 successor patch preserves prior checks',()=>{const p='tests/m04_admission_test.sh',o=oldGuard('m04'),a=adaptFile(p,o);assert(a.includes('prior_checks'));assert(a.includes('M08_EXECUTION_PACKAGE.md'));});
test('M07ADM-20 M05 successor patch retains runtime',()=>{const p='tests/m05_admission_test.sh',o=oldGuard('m05'),a=adaptFile(p,o);assert(a.includes('runtime_call'));assert.throws(()=>validatePatch(p,o,a.replace('runtime_call','true')));});
test('M07ADM-21 shared readiness preserves counters',()=>{const p='tests/m03_m08_execution_readiness_test.sh',o='criteria=72; slices=60\nfor f in docs/planning/M0{7,8}_EXECUTION_PACKAGE.md; do\n  grep -q \'IMPLEMENTATION BLOCKED\' "$f" || fail "$f must remain implementation-blocked"\ndone\nprintf "X / M07-M08 BLOCKED"',a=adaptFile(p,o);assert(a.includes('criteria=72; slices=60'));assert(a.includes('M08_EXECUTION_PACKAGE.md'));});
test('M07ADM-22 M08 remains blocked in successor',()=>{const p='tests/m05_admission_test.sh',a=adaptFile(p,oldGuard('m05'));assert(a.includes("grep -q 'IMPLEMENTATION BLOCKED' docs/planning/M08_EXECUTION_PACKAGE.md"));});
test('M07ADM-23 package patch preserves original scope',()=>{const p='docs/planning/M07_EXECUTION_PACKAGE.md',o='Status: `PLANNING COMPLETE / IMPLEMENTATION BLOCKED`\n1. original\n10. integration\nDefinition of Done\nStop conditions',a=adaptFile(p,o);assert(a.includes('1. original'));assert(a.includes('Stop conditions'));assert(a.includes('Only S01'));});
test('M07ADM-24 source governance remains external immutable prerequisite',()=>{assert.equal(expectedDecision().source_governance_id,'CALPQ-REG-0001');});
test('M07ADM-25 parser AI legal authority false',()=>{assert.equal(expectedDecision().legal_interpretation_authorized,false);assert.equal(expectedDecision().production_release_authorized,false);});
test('M07ADM-26 historical versions boundary retained',()=>{assert.equal(expectedDecision().m07_completed_slices,0);});
test('M07ADM-27 activation remains post-merge conditional',()=>assert.equal(expectedDecision().admission_effective_condition,'ADMISSION_PR_MERGED_AND_POST_MERGE_VERIFIED'));
test('M07ADM-28 exact activation accepted',()=>{validateActivation(activation());assert.equal(modeFor(activation()),'S01');});
test('M07ADM-29 fake hashes/preparation rejected',()=>{for(const p of [{admission_merge:PREP},{admission_head:PREP_HEAD},{admission_merge:M06},{admission_tree:'fake'},{admission_merge:'A'.repeat(40)}])assert.throws(()=>validateActivation(activation(p)));});
test('M07ADM-30 foreign evidence references rejected',()=>{for(const p of [{owner_merge_approval_reference:'https://example.org/x'},{admission_pr:161},{post_merge_evidence_reference:'https://github.com/robertdominik618/calpq-os/pull/163#issuecomment-0'}])assert.throws(()=>validateActivation(activation(p)));});
test('M07ADM-31 wrong activation state/slice/authority rejected',()=>{for(const p of [{state:'PENDING'},{slice:'S02'},{production_release_authorized:true},{legal_interpretation_authorized:true},{decision_id:'other'}])assert.throws(()=>validateActivation(activation(p)));});
test('M07ADM-32 S01 additive and bounded successor-compatibility scope accepted',()=>{validateScope(S01_ADDED.map(path=>({path,status:'A',mode:'100644'})),'S01');for(const path of S01_MODIFIED)validateScope([{path,status:'M',mode:S01_EXECUTABLE_MODIFIED.includes(path)?'100755':'100644'}],'S01');assert.deepEqual(S01_EXECUTABLE_MODIFIED,[ 'tests/m04_s10_integration_evidence_test.sh','tests/m05_s06_trust_registry_test.sh','tests/m05_s07_verification_route_registry_test.sh','tests/m05_s08_human_review_test.sh','tests/m05_s09_archive_lifecycle_test.sh','tests/m06_s01_lifecycle_timeline_test.sh']);});
test('M07ADM-33 later/provider/UI/Application and unapproved historical governance paths rejected',()=>{for(const path of ['packages/core/src/regulatory/s02.ts','packages/application/src/regulatory/x.ts','packages/adapters/src/x.ts','apps/web/x.ts','README.md','tests/m04_s09_historical_version_replay_test.sh','tests/m05_s05_security_quarantine_test.sh','tests/m06_s02_expiry_renewal_test.sh'])assert.throws(()=>validateScope([{path,status:'M',mode:'100644'}],'S01'));});
test('M07ADM-34 activation mutation deletion and unauthorized executable mode rejected',()=>{for(const patch of [{status:'M'},{status:'D'},{status:'R100'},{mode:'100755'}])assert.throws(()=>validateScope([{path:S01_ADDED[0],status:'A',mode:'100644',...patch}],'S01'));assert.throws(()=>validateScope([{path:'scripts/ci/m07-admission.mjs',status:'M',mode:'100755'}],'S01'));assert.throws(()=>validateScope([{path:S01_EXECUTABLE_MODIFIED[0],status:'M',mode:'100644'}],'S01'));});
test('M07ADM-35 index identity completeness enforced',()=>{validateIndex(matrix());assert.throws(()=>validateIndex(matrix().split('\n').slice(1).join('\n')));assert.throws(()=>validateIndex(matrix()+'\n| M07ADM-01 | duplicate |'));assert.throws(()=>validateIndex(matrix().split('\n').reverse().join('\n')));});
test('M07ADM-36 malformed activation cannot enable product mode',()=>{assert.equal(modeFor(undefined),'ADMISSION');for(const v of [null,false,{},[],{state:'ADMISSION'}])assert.throws(()=>modeFor(v));});
